### ISSUE TITLE
Dockerise

### ISSUE THREAD

**Issue by Harjot1Singh** [supertokens/supertokens-core#1]
Nice job with this!

Do you guys plan to throw up a Docker image?

**Comment by Harjot1Singh** [comment]
Ooops, ignore me, have just found https://github.com/supertokens/supertokens-docker-postgresql 😂

**Comment by rishabhpoddar** [comment]
@Harjot1Singh thanks! We are working on updating our website UI and docs to reflect that we have these docker containers. If you have any questions about them, please feel free to comment on this issue, or contact us on [discord](https://supertokens.io/discord).
