### ISSUE TITLE
IP address of user upon signup and login

### ISSUE THREAD

**Issue by DarkNeedle** [supertokens/supertokens-core#1002]
It appears for a given signup or login there is some base user  information. It would be beneficial to log or make available upon signup and login the IP address of the individual

Is this already available?

Thanks

**Comment by rishabhpoddar** [comment]
You can get the IP address yourself from the [request object](https://supertokens.com/docs/thirdpartyemailpassword/advanced-customizations/user-context/custom-request-properties) thats available in the api override.
