### ISSUE TITLE
Your website alerts 'jo' when I click on the GitHub icon

### ISSUE THREAD

**Issue by danhumphrey** [supertokens/supertokens-core#1007]
## 🐛 Bug Report
Navigate to the home page and click on the Githib Icon:

![image](https://github.com/supertokens/supertokens-core/assets/66364/991f482d-9a24-4623-8bdb-8c55b80194a1)

## Useful informations

(Write what happened. Add screenshots, stacktraces, videos, anything that can help)

**Comment by rishabhpoddar** [comment]
Thanks for pointing this out. It has been fixed.
