### ISSUE TITLE
Try SuperTokens in under 1 Minute Fails

### ISSUE THREAD

**Issue by danhumphrey** [supertokens/supertokens-core#1008]
## 🐛 Bug Report

Executing the following from your quick start instructions fails:

1. `npx create-supertokens-app@latest`
2. `cd my-app`
3. `npm run start`

I see the following:

The app launches to a blank grey screen with no UI:

![image](https://github.com/supertokens/supertokens-core/assets/66364/ff849b66-6ad2-4759-abac-1103b09ad6c4)

I decided to try the non localhost url and it loads, however, any action on the UI (trying to sign up with email and password, or Google etc.) results in the 'Something went wrong' error and I've now lost faith and don't feel like exploring supertokens any more....

![image](https://github.com/supertokens/supertokens-core/assets/66364/aeee986a-0dd0-4288-a214-5e9a80088744)

I don't know if your intention with the quick start is only to demo what the UI looks like without it being functional, but if that's the case, then maybe you should explain this in the quick start instructions.

If there are other dependencies and/or pre-requisites, then this should also be made clear. 

Either way, I think a quick start intro to a product or service should be seamless and error free.

## Useful informations

![image](https://github.com/supertokens/supertokens-core/assets/66364/af790081-d892-4480-9ded-e0795ff97de3)
![image](https://github.com/supertokens/supertokens-core/assets/66364/6031b2d0-b3c8-4e9a-ba17-084dbee6e1a7)

**Comment by rishabhpoddar** [comment]
This is strange. Whats the error you see on the network tab when you click on the sign in button?

**Comment by rishabhpoddar** [comment]
I just tried the CLI with the same options and node version as you did, and it worked. Which OS are you using?

**Comment by danhumphrey** [comment]
Apologies, I should have given more info sooner. 

On the localhost url there are no errors in the console.

On the network URL:

At this stage, immediately after loading:

![image](https://github.com/supertokens/supertokens-core/assets/66364/fb17fded-3f6b-43de-a1d9-4b8b38743866)

I see this in the console:

![image](https://github.com/supertokens/supertokens-core/assets/66364/34a7493f-0cd8-4da2-ad10-ca14cbb9369c)

After refreshing the page (no UI interaction), I see this:

![image](https://github.com/supertokens/supertokens-core/assets/66364/c88e986c-8616-4f39-b41a-637a55febc2b)

_As an aside, weird that it mentions React when I chose Vue._

After clicking the button:

![image](https://github.com/supertokens/supertokens-core/assets/66364/4f74993c-076d-422c-8e6e-b64a498bc606)

After clicking 'Continue with Google':

![image](https://github.com/supertokens/supertokens-core/assets/66364/374c6a8b-33d8-460c-9869-deb160f2b8bb)

Bear in mind that I had already deleted the directory I created this morning, so this is a reproduction of the issue I faced earlier.

Let me know if I can help further.

Dan

**Comment by danhumphrey** [comment]
Mac OS Sonoma 14.5 M2 Chip

I tried in Brave earlier, but just tried Safari and get the same error

**Comment by rishabhpoddar** [comment]
> As an aside, weird that it mentions React when I chose Vue.

Thsi is expected. We only have pre built Ui for react, and therefore we load react and the pre built UI on the /auth page of the application.

Can you also show me the network tab response please? Perhaps send the HAR file.

Thanks

**Comment by danhumphrey** [comment]
> Thsi is expected. We only have pre built Ui for react, and therefore we load react and the pre built UI on the /auth page of the application.
Understood, thanks!

[supertokens.txt](https://github.com/user-attachments/files/16121026/supertokens.txt)


HAR file attached, although I had to change the file extension to upload it here

**Comment by rishabhpoddar** [comment]
Unfortunately, the har file deosn't show the status codes of the API calls. I suspect that the backend node server in the example didn't start for you for some reason.

Can you run `npm run start:backend` and show the output? Thanks

**Comment by danhumphrey** [comment]
If I run that independently (e.g. I'm not running the app and it isn't already running the API server on port 3001), then I get the following:

![image](https://github.com/supertokens/supertokens-core/assets/66364/f9bbd227-72c9-4c37-a60f-c39427ace8b6)

**Comment by rishabhpoddar** [comment]
Right, so this means it worked. Now if the frontend is not able to communicate to the backend, it may be an issue with your node version (try v18 or v16), or some firewall setting on your system.

**Comment by danhumphrey** [comment]
Neither of the ports are blocked - I run various different servers (vite, webpack) and can spin up http-server on the ports you use without anything being blocked.

Sorry, I don't have time to try different node versions at the moment. Feel free to close the bug if you don't think it's an issue to be solved.

**Comment by rishabhpoddar** [comment]
Will keep it open in case someone else can reproduce this issue. Thanks

**Comment by rienheuver** [comment]
I just tried `npx create-supertokens-app@latest` with the following options:
frontend: angular
backend: nestjs
auth type: passwordless

When doing `cd myapp` and `npm run start` I get the following errors in my console:
```
Error: node_modules/@types/node/stream/web.d.ts:469:56 - error TS1005: '?' expected.

469             DecompressionStream: infer T extends object;
                                                           ~


Error: node_modules/@types/node/stream/web.d.ts:484:13 - error TS2502: 'ReadableByteStreamController' is referenced directly or indirectly in its own type annotation.

484         var ReadableByteStreamController: typeof globalThis extends
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@types/node/stream/web.d.ts:503:13 - error TS2502: 'ReadableStreamBYOBReader' is referenced directly or indirectly in its own type annotation.

503         var ReadableStreamBYOBReader: typeof globalThis extends { onmessage: any; ReadableStreamBYOBReader: infer T }
                ~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@types/node/stream/web.d.ts:513:13 - error TS2502: 'ReadableStreamBYOBRequest' is referenced directly or indirectly in its own type annotation.

513         var ReadableStreamBYOBRequest: typeof globalThis extends { onmessage: any; ReadableStreamBYOBRequest: infer T }
```

**Comment by rishabhpoddar** [comment]
@rienheuver, which version of node are you using?

**Comment by rienheuver** [comment]
> @rienheuver, which version of node are you using?

v20.16.0

**Comment by rishabhpoddar** [comment]
@rienheuver we have fixed the demo app for angular. Please do try it again. I am closing this issue for now, but feel free to reopen in case needed.
