### ISSUE TITLE
Possible bug with /hello

### ISSUE THREAD

**Issue by leu** [supertokens/supertokens-core#1021]
## 🐛 Bug Report

I'm getting some errors around one of the tenants I've created, `hellotenant`

I get the following error message when invoking SuperTokens in my endpoint: `Internal Server Error: Exception: SuperTokens core threw an error for a POST request to path: /hellotenant/recipe/multitenancy/tenant/user with status code: 404 and message: Not found\n`

Additionally, when I use the SuperTokens user management dashboard, `hellotenant` comes up in the options, but when I click on it, I get the error screen shown in the attached image, and refreshing the page keeps showing that message. On my backend I get `Exception: SuperTokens core threw an error for a GET request to path: /hellotenant/users with status code: 404 and message: Not found`

![image](https://github.com/user-attachments/assets/8c05df7d-831f-414e-b40a-56f6817a32c3)

## Useful informations

I asked SuperTokens support in its Discord server, and rp replied saying this might be a bug in the core, since there is an endpoint like `/hello`.

**Comment by sattvikc** [comment]
@leu Thank you for reporting this. This is now fixed in supertokens-core version 9.1.2.
