### ISSUE TITLE
Migration missing for 9.1/9.2 Core ?

### ISSUE THREAD

**Issue by svonfelten** [supertokens/supertokens-core#1031]
## 🐛 Bug Report

Hello, 
I made a update of my dependencies last week and decided to update my Supertoken-core and backend library version. I am using supertoken core 9.2 currently (from 7.0) . When starting the core with a database that contains data from version 7 i have this error on startup : 

![SupertokenCrash](https://github.com/user-attachments/assets/8468025a-ba10-42cd-84fc-bcbdffbeb203)

I am launching mysql and the supertoken core in docker env. it is working when i delete the database but i obviously can't do this in production. I think there is a migration script missing maybe ? I only found one script to version 7 not to version 9. 

I am missing something or not ?

**Comment by rishabhpoddar** [comment]
Hi,

We do have a migration guide in the core changelog: https://github.com/supertokens/supertokens-core/blob/master/CHANGELOG.md

**Comment by svonfelten** [comment]
Oh yeah i didn't see this section in the changelog, thank you
