### ISSUE TITLE
Run the core via SSL

### ISSUE THREAD

**Issue by valtonia** [supertokens/supertokens-core#1038]
## 🚀 Feature

Is there any option or plan to allow the core to be run over HTTPS/SSL?

## Implementation details

I couldn't see anything in the documentation about how to do this.  Perhaps adding something to the `config.yaml` file to point to the certificate files, and then automatically switch to HTTPS if those settings/files are present?

**Comment by rishabhpoddar** [comment]
We recommend people to use nginx reverse proxy for this: https://supertokens.com/docs/thirdpartyemailpassword/common-customizations/core/add-ssl-via-nginx.

We dont plan on adding SSL support to the core itself cause using a reverse proxy is easy enough.
