### ISSUE TITLE
High latencies for passwordless signup API

### ISSUE THREAD

**Issue by kaustubhbabar5** [supertokens/supertokens-core#1045]
## 🐛 Bug Report

Hii, we've self hosted supertokens core and  we're experiencing high latencies for `/recipe/signinup/code` API, there was a load of approximately 100 requests per second for this api and we've seen latencies going upto 60 secs.

**Comment by kaustubhbabar5** [comment]
We observed lot of deadlock and `could not serialize access due to concurrent update` errors for following query around the same time
```
DELETE FROM passwordless_devices WHERE app_id = $1 AND tenant_id = $2 AND phone_number = $3
```

**Comment by rishabhpoddar** [comment]
Hi @kaustubhbabar5 which version of the core are you using?

**Comment by kaustubhbabar5** [comment]
it's supertokens-postgresql:6.0

**Comment by rishabhpoddar** [comment]
Closing this issue due to no response and we can't reproduce it.
