### ISSUE TITLE
The docker image requires root permission and is unable to run on a read only file system

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#1048]
## 🐛 Bug Report

At the moment, the user in the docker image requires root permission to run, and the docker image itself is unable to run on a read only root file system. This poses security risks that need to be dealt with.

**Comment by mavridiSS** [comment]
+1 - This issue came up on a pen test report and we're waiting for a fix for it to go live.

@tamassoltesz do you have any rough estimations?

**Comment by MoggyPersonal** [comment]
+1 - Will definitely be flagged within our own security reports that clients ask for

Would be great to know progress on this please

**Comment by rishabhpoddar** [comment]
We are working on this now and should have a fix for it sometime next week.

**Comment by sattvikc** [comment]
Fixed in core version 9.2.3

**Comment by tamassoltesz** [comment]
Root permission/root user is no longer needed in the container.
For --read-only (read-only root filesystem), you should mount a tmpfs to `/lib/supertokens/temp`  with `:exec` mode. (see [https://github.com/supertokens/supertokens-docker-postgresql/tree/9.2 README](https://github.com/supertokens/supertokens-docker-postgresql/blob/9.2/README.md#read-only-root-fs))
