### ISSUE TITLE
DeprecationWarning: The `punycode` module is deprecated.

### ISSUE THREAD

**Issue by wav-matt** [supertokens/supertokens-core#1049]
## 🐛 Bug Report

upon running my node server, I get this warning: 
**The `punycode` module is deprecated. Please use a userland alternative instead.**

## Useful informations

ran my node server, running node v22.7.0, did a trace and got this:
└─┬ supertokens-node@20.1.2
  └── psl@1.8.0

**Comment by rishabhpoddar** [comment]
This has been fixed in version 20.1.3
