### ISSUE TITLE
Cannot use feature: multi_tenancy, because the license key is missing, or doesn't have this feature enabled

### ISSUE THREAD

**Issue by backslash112** [supertokens/supertokens-core#1066]
## Description

I'm encountering an error when trying to use the multi-tenancy feature with a self-hosted SuperTokens instance. 

```
curl --location --request PUT 'http://localhost:3567/recipe/multitenancy/app' \
--header 'api-key: <API_KEY(if configured)>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "appId": "app1",
    "thirdPartyEnabled": true,
    "passwordlessEnabled": true,
    "emailPasswordEnabled": true,
    "coreConfig": {...}
}'
```
**Error message:**
```
Cannot use feature: multi_tenancy, because the license key is missing, or doesn't have this feature enabled
```

**Environment:**
- Deployment: Self-hosted

**Steps to reproduce:**
1. Set up a self-hosted SuperTokens instance
2. Attempt to configure or use multi-tenancy features
3. Encounter the above error

**Expected behavior:**
The multi-tenancy feature should be available and functional for self-hosted SuperTokens instances.

**Questions:**
Is a separate license required for multi-tenancy in self-hosted deployments?

Any guidance on resolving this issue would be greatly appreciated. Thank you for your help!

**Comment by rishabhpoddar** [comment]
Hi. This is not a bug. It requires you to add a license key since multi tenancy is a paid feature. You can get a license key by signing up on supertokens.com and clicking on the "enable paid features" button.

**Comment by dentro-innovation** [comment]
very odd how you advertise the self hosted version as "free"..
![image](https://github.com/user-attachments/assets/1918cfee-92d9-448a-82de-5d6700d86499)

...and display SAML login as YES...
![image](https://github.com/user-attachments/assets/ae6da50f-a3d1-4b02-973d-ef1f80344919)

But then in reality SAML has to be paid anyway
