### ISSUE TITLE
Should we change the email password recipe ID?

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#112]
- In the code and docs it's `email-password`.
- In the import statement it's `emailpassword`.

Let's keep it consistent everywhere.. Should we rename the recipeId to `emailpassword`?

@NkxxkN 

----------------
Required changes:
- [x] Frontend SDK (auth-react) https://github.com/supertokens/supertokens-auth-react/pull/29
- [x] NodeJS
- [x] Core (config)
- Database (table names)
   - [x] sqlite
   - [x] mysql
   - [x] postgresql
- [x] Docs

**Comment by NkxxkN** [comment]
Sure we better do it now. I'll take care of it

**Comment by rishabhpoddar** [comment]
> I'll take care of it

Which parts? The frontend SDK only right?

**Comment by NkxxkN** [comment]
I thought I could do the others too but maybe that will conflict with some of your current work? 

I'll do the Docs and front end for sure. Let me know if you want me to do the core too?

**Comment by rishabhpoddar** [comment]
I can do the core, db and backend SDK.
