### ISSUE TITLE
Implement anonymous Telemetry

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#116]
This will help us improve on our product. A few important points:
- Users should be able to disable it
- There should be information about this in the github wiki
- It should be anonymous
- We should only send this if a proper database is used (not in memory db)

-------
Related issue: https://github.com/supertokens/supertokens-core/issues/26 (invalid), https://github.com/supertokens/supertokens-core/issues/118 (preventing telemetry to get sent during testing)

**Comment by rishabhpoddar** [comment]
> Users should be able to disable it

If using Docker:
- Pass the DISABLE_TELEMETRY=true env variable

Without docker:
- Set `disable_telemetry: true` in the `config.yaml` file

> It should be anonymous

We will create an anonymous ID if one does not exist, store that in the key value table.

**Comment by rishabhpoddar** [comment]
Information to send:
- SuperTokens version
- Telemetry Id

**Comment by rishabhpoddar** [comment]
## API spec:
URL: `/0/st/telemetry`
Method: `POST`
Input body:
```
{
   telemetryId: string,
   superTokensVersion: string // X.Y.Z format
}
```
Output:
- 200 status code with an empty body

**Comment by rishabhpoddar** [comment]
@bhumilsarvaiya please close this issue once the API has been made & tested.

**Comment by bhumilsarvaiya** [comment]
**API Endpoint**: `/0/st/telemetry`
**Method**: `POST`
**Success Response**: `{}`
**Success Response Code**: `200`
**Possible Response Codes**: `200, 400, 408, 500`
**Required in Request**:
- headers:
    - api-version: 0
- request-body:
   ```
   {
       telemetryId: string,
       superTokensVersion: string  // X.Y.Z
   }
   ```
