### ISSUE TITLE
Email Verification flow discussion

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#124]
For the emailpassword recipe, we want to add email verification with the following properties:
1) New signed up users will not have their email verified
2) Email verification is not required by default.
3) Two ways to provide email verification:
   a) During sign up
   b) Post sign up, after they log in (a banner can be shown) (default behaviour)
4) Devs should be able to query on the backend to check if email has been verified or not
5) If the email changes, its status is turned to not verified. At this point, the dev can either enforce verification, or we show the banner again. This behaviour will match what's chosen by the dev for 3)
6) We will send a default email verification email. Just like how we send for password reset
7) Email verification will be based on a link sent in the email. Not based on OTP.
8) When the link in the email is clicked, the email is verified, regardless of a session being active on the browser on which it is opened
9) If the password is reset using a token sent via the email, then email verification also happens

## More details [here](https://github.com/supertokens/supertokens-core/issues/124#issuecomment-749356975)
----------------
Discussion
- [x] Does point number 8 make sense?
   - yes
- [x] Does point number 9 make sense?
   - yes
- [x] For the initial version, we can only have the banner version
   - no. In fact, we may not provide the banner component initially and just provide active email verification, and adding banner later on for passive email verification
- [x] Make chanes to FDI & CDI spec

**Comment by NkxxkN** [comment]
**Writing some thoughts about the above, we can clean the comment later for consistency and ease of read.**

> If the email changes, its status is turned to not verified. At this point, the dev can either enforce verification, or we show the banner again.

I don't think the banner is needed in that case, since we already have a verified email, the identity of the user is confirmed with the old email.

> When the link in the email is clicked, the email is verified, regardless of a session being active on the browser on which it is opened

That makes sense to me. The token is enough from a security point of view + You could open the email on another device (from your mobile's email notifications).

> If the password is reset using a token sent via the email, then email verification also happens

If an email is unverified, we should not send a reset password to that email. The reset password should be sent to the verified email only. We should verify the email first.

If we did send a reset password to unverified email, that would help an attacker to easily escalate, for example, a CSRF on email update endpoint to a full account takeover.

**Comment by rishabhpoddar** [comment]
## Database changes
- We will add a number `boolean` column in `emailpassword_users` table called `email_verified`. The default value of this will be `false`.

**Comment by rishabhpoddar** [comment]
@NkxxkN please have a read at the above comment, and here is my reply to your comments:

> I don't think the banner is needed in that case, since we already have a verified email, the identity of the user is confirmed with the old email.

I think we need it, cause what if the user first signs up with a legit email, verifies it, and then changes it to another email that does not belong to them.. in this case, we do not want to keep their email verified status.

> If an email is unverified, we should not send a reset password to that email. The reset password should be sent to the verified email only. We should verify the email first.
If we did send a reset password to unverified email, that would help an attacker to easily escalate, for example, a CSRF on email update endpoint to a full account takeover.

I don't think I understand this fully. But as per my comment above, email verification happens only when you have an active session first. If a user has forgotten their password, it means they are unable to login, in which case they cannot create an active session, in which case they cannot verify their email. So if we enforce email verification in order to send a reset password email, then it's a deadlock situation.

**Comment by rishabhpoddar** [comment]
## Design requirements:
@makerboiAdi @mufassirkazi 
- Email for email verification (similar to password reset email)
- UI to show post sign up / sign in to prompt the user to verify their email
   - This will contain a button to send an email
   - Once the email is sent, it will  show something like check your email (but the button is still there)
- UI to show when the user clicks on the link in their email for when the email is verified
   - Here apart from the generic error state, there is one where the token is expired.
- Banner for passive email verification (can implement later)

**Comment by NkxxkN** [comment]
>  I think we need it, cause what if the user first signs up with a legit email, verifies it, and then changes it to another email that does not belong to them.. in this case, we do not want to keep their email verified status.

What I had in mind was a different model that I've seen used in bunch of SaaS doing bug bounty hunting.
The user table contains an `unverified_email` and a verified_email` row.

- When user sign up, the `unverified_email` row is populated.
- When email is verified, the email moves from `unverified_email` to `verified_email`.
- When the user wants to change its email, the `unverified_email` is populated, while keeping the `verified_email` valid. When the user verifies the new email, the verified email is updated. The unverified is now empty.

**Comment by rishabhpoddar** [comment]
- There will be three modes:
   - Required: The user must have verified their email to use the service
   - Optional: The user can use the service without email verification, but the email is sent post sign up and a banner is shown
   - Off: Same as Optional, except no email is sent, and no banner is shown

- We will implement Required and Off. Off will be the default
- Next, we will implement Optional, and make that the default

**Comment by rishabhpoddar** [comment]
For future reference, when we change email, we must prompt the user to enter their password to prevent the attack that if a session is compromised and the attacker then changes the email to theirs

**Comment by rishabhpoddar** [comment]
The problem with "my" suggested method is that if the email is changed and there is a typo in it, and the user logs out, then they cannot login (if they have forgotten their password). But with kevin's method, they can still login using the older, verified email.

**Comment by NkxxkN** [comment]
## Researches on email update and verification


### Auth0

https://community.auth0.com/t/update-user-email-the-right-way/6285


Seems like Auth0 is going with the method with the boolean. They encourage users to enforce email verification, hence blocking accounts while email is in the process of getting updated.


> This functionality is not available in Auth0 out of the box. One way which you could implement this is to use the Force Email Verification rule. The flow would work as follows:
 > User changes email address
> You trigger the Post Verification Email 418 job via Management API v2
> If they try logging in without having verified the email, they will be blocked by the Rule. If they have verified the email, they can login.
### Firebase

Updating an email from an account (with previously verified email) will automatically mean that the new email is verified
Ref: https://stackoverflow.com/questions/57066173/send-verification-email-when-updating-email-address-in-firebase-auth
and https://firebase.google.com/docs/auth/web/manage-users
It looks like a bad design to me 🤔 
### AWS Cognito

 > Verifying When Users Change Their Email or Phone Number
When a user changes his or her email address or phone number in your app, that attribute is marked as unverified. If auto-verification was enabled for the attribute being updated, the service immediately sends the user a message containing a verification code, which the user should enter to verify the change. You can use a Custom Message Lambda trigger to customize this message. For more information, see Customizing User Pool Workflows with Lambda Triggers. Whenever the user's email address or phone number is unverified, your app should display the unverified status and provide a button or link for users to verify their new email or phone number.

**Comment by rishabhpoddar** [comment]
So to summarise the benefit of the second method of the first:

Let's take a scenario in which the user has a typo in their new email, they have logged out, and they have forgotten their password. In this case, they can use the old, verified email to reset their password, login and change their email, not locking them from their account. In the first method, they would have been locked out.

Is there any other benefit I am missing?

**Comment by rishabhpoddar** [comment]
We are going with the boolean method
