### ISSUE TITLE
Add user pagination functions

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#127]
This will allow devs to loop through the list of users in the system in a paginated manner. This only requires a backend function and no frontend UI.

Related to https://github.com/supertokens/supertokens-core/issues/96

- [x] SQLite
- [x] Postgresql
- [x] MySQL
- [x] Nodejs
- [x] Documentation

**Comment by bhumilsarvaiya** [comment]
- `/recipe/users` GET API. allowed params will be `nextToken`, `limit`. `joinedAfter`, `joinedBefore`
- response will be of format 
```ts
{
   "users": {
       "id": "string",
       "email": "string",
       "timeJoined": "number"
   }[], 
   "nextToken"?: "string"
}
```
- if no `limit` param will be passed, value will be set to 100 by default
- if no `nextToken` param is passed, the db function will fetch the first N users (N = `limit`).
- if `nextToken` is passed, it will be base64 decoded and the parsed to get the timeJoined and userId required to perform the pagination query.
- if result returned from db has less number of rows than the `limit`, nextToken will not be passed
- `/recipe/users/count` GET API will return no of users in db

Question:
- the above implementation will return users in desc order based on timeJoined.  Should we give also allow param so the user can get oldest user first (ASC order)?
- should we allow params `joinedAfter` and `joinedBefore` for `/recipe/users` GET API?

**Comment by rishabhpoddar** [comment]
> the above implementation will return users in desc order based on timeJoined. Should we give also allow param so the user can get oldest user first (ASC order)?

Yes.

> should we allow params joinedAfter and joinedBefore for /recipe/users GET API?

Can do if it doesn't make it too complex.

--------------

- Why do we need `nextToken`? Why can't we ask the user to given the last userId and the last time joined?
- What will be the funcitons exposed on the nodejs side?

**Comment by rishabhpoddar** [comment]
## NodeJS APIs:
```js

// initial get
let users: {
   id: string,
   email: string,
   timeJoined: number,
   paginationToken: string
}[] = await getUsersOldestFirst(); // will return upto 100

// further get
let users = await getUsersOldestFirst(50, users[user.length - 1].paginationToken); // will return 50 more users

// function signature:
getUsersOldestFirst(numberOfUsers?: number, paginationToken?: string) => Promise<{id: string, email: string, timeJoined: number, paginationToken: string}>
```

Very similar function signature for `getUsersNewestFirst`

**Comment by chotuchaudhary** [comment]
>     * `/recipe/users` GET API. allowed params will be `paginationToken`, `limit`, `order: ASC | DSC`.
> 
>     * response will be of format
> 
> 
> ```ts
> {
>    "status" : "OK",
>    "users": {
>        "id": "string",
>        "email": "string",
>        "timeJoined": "number"
>    }[],
>    "nextPaginationToken": "string"
> }
> ```
> 
>     * if no `limit` param will be passed, value will be set to 100 by default. The max allowed limit is 1000
> 
>     * if no `nextPaginationToken` param is passed, the db function will fetch the first N users (N = `limit`).
> 
>     * if `nextPaginationToken` is passed, it will be = `base64(timeJoined;id)`
> 
>     * There will be another API to get the number of users `/users/count` GET which will return `{status: "OK", count: number}`
> 
> 
Above pagination will work as expected @bhumilsarvaiya @rishabhpoddar 
However, I would also like to add some points, So that it can be improved further. Below are the suggested points.

  - Features of Pagination API
    * Should allow ordering by any elements or combination of elements.
    * Should provide the pagesize
    * Only provide required attributes in response
    * Also provide hasNextPage as true/false, if next page exist, otherwise, if there is no more element, user will get error in next call.
it's better to inform user, that this is the last page or not.
```js
GET /recipe/users?attrs=id:asc,email:desc,time_joined:asc&next_page_token=xyz&limit=50
will be returned response orderby id in ascending, email in descending and time_joined in ascending.
Response : {
   "items" : [
        {"id":"id1", "email":"abc@abc.com", "time_joined" : 123456543},
        ....
    ], // user's array
   "has_next_page" : true/false,
   "page_size" : n, // length of items array
   "next_page_token" : "xYxYZZZ"
}

GET /recipe/users?attrs=id:asc,email&next_page_token=xyz&limit=50
Response : {
   "items" : [
        {"id":"userId1", "email":"abc@abc.com"},
        ....
    ], // user's array
   "has_next_page" : true/false,
   "page_size" : n, // length of items array
   "next_page_token" :" xYxYZZZ"
}

By Default, result will be ordered by id in ascending orders
GET /recipe/users?attrs=time_joined,email&next_page_token=xyz&limit=50
Response : {
   "items" : [
        {"time_joined":765432, "email":"abc@abc.com"},
        ....
    ], // user's array
   "has_next_page" : true/false,
   "page_size" : n, // length of items array
   "next_page_token" : "xYxYZZZ"
}
```
*Note : 
* `has_next_page` flag can be derived easily, if we fetch limit+1 elements from database.
let's say limit is 50, So 51 records will be tried to be fetched from DB and if records size <=50, then, has_next_page = `false` otherwise `true`.
* I have combined the attributes and their order in `attrs` query param.
 i.e. `attrs=email:desc,time_joined:asc`
 for above case, `email` and `time_joined` will be returned as these are the attributes which are mentioned in `attrs` query param.
  if there is no attrs, By default, all attributes will be returned ordered by `id ASC`.

@rishabhpoddar , @bhumilsarvaiya Let me know your thoughts?

**Comment by rishabhpoddar** [comment]
Hey @chotuchaudhary ,
Thanks for the suggestions.

> Should allow ordering by any elements or combination of elements.
The attributes we store in the user table are `userId`, `email`, `timeJoined`, `passwordHash` and `is_email_verified`. From an ordering perspective, I see it only makes sense to order based on email and / or time joined. Our original plan was to only sort based on time joined (As seen by the node functions), but we can add for email too. This would require an additional index though, so not sure if this will be very valuable. If someone really requires to have this sorting, they can loop through all users, and maintain their own sorted table?

Also, how would the nodejs functions for this look like, if we were to implement this?

> Should provide the pagesize
This can be easily calculated by `items.length`, so I don't see why an additional property for this is required - unless I misunderstood what you mean by pagesize

> Only provide required attributes in response
There aren't tons of attributes, just three.. So i don't see why we need to complicate the API for this. Also, how would the nodejs functions for this look like, if we were to implement this?

> Also provide hasNextPage as true/false, if next page exist, otherwise, if there is no more element, user will get error in next call.
Agreed.

**Comment by chotuchaudhary** [comment]
@rishabhpoddar Thanks for detailed comment

> The attributes we store in the user table are userId, email, timeJoined, passwordHash and is_email_verified. From an ordering perspective, I see it only makes sense to order based on email and / or time joined. Our original plan was to only sort based on time joined (As seen by the node functions), but we can add for email too. This would require an additional index though, so not sure if this will be very valuable. If someone really requires to have this sorting, they can loop through all users, and maintain their own sorted table?

Agreed
 > Also, how would the nodejs functions for this look like, if we were to implement this?
 
Don't have any experience in `nodejs`.

>  This can be easily calculated by items.length, so I don't see why an additional property for this is required - unless 
I misunderstood what you mean by pagesize


It's exactly what you explained above, and can be derived easily using items.length. But user is expecting no. of records as `limit`
So it's better to tell the user that `pagesize` can be computed using items.length.

>There aren't tons of attributes, just three.. So i don't see why we need to complicate the API for this. Also, how would the nodejs functions for this look like, if we were to implement this?

As there are only 3 attributes, we can skip this part. This way, paginated api will be simple.
