### ISSUE TITLE
If the DB is restarted while the core is running, in certain situations, the core is unable to connect again

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#132]
The core would then have to be restarted for it to connect again. Ideally, we do not want to do that

**Comment by anugrahsinghal** [comment]
hey, @rishabhpoddar can you please assign this to me.

**Comment by rishabhpoddar** [comment]
done :)

**Comment by anugrahsinghal** [comment]
Hey, 

How can I reproduce this? As it says "certain situations"
- Are there any tests?
- Is this specific to a DB i.e. In-Mem/MySQL/Postgres

A way to reproduce would be great that way I can come up better questions/answers to debug and solve this.

**Comment by rishabhpoddar** [comment]
> Are there any tests?

No tests yet.

> Is this specific to a DB i.e. In-Mem/MySQL/Postgres

Postgresql and MySQL. The in mem db will never be down.

The last time i reproduced this was to manually connect the core to  a db, send some request which worked, then stop the db, send a request which didn't work, start the db again, and then send another request which should have worked, but doesn't.

**Comment by anugrahsinghal** [comment]
I tried a few requests for the same scenario today.
As of now, they worked, will check for more scenarios.

Few questions:
1. Is there a Swagger JSON file for the supported requests that I can import to my client say postman as it will make it easy to do these requests.
2. The last time you reproduced this was this in a specific scenario? 
   - Load Testing or general 1:1 request-response
   - What kind of env was used (might not even affect the outcome but I can try to mimic the original env)
  
I tried a few scenarios with:
MySQL: latest on docker
did you make use of any specific version or config?

**Comment by anugrahsinghal** [comment]
> Is there a Swagger JSON file
NVM found this.

**Comment by rishabhpoddar** [comment]
Hi @anugrahsinghal, unfortunately i don't recall how I ran into this issue. Maybe it was a user who had told me about it.. not sure.

If this is not reproducible, then feel free to close it. Since i haven't heard about this issue since the day this issue was opened.

**Comment by rishabhpoddar** [comment]
Closing cause we can't replicate this.
