### ISSUE TITLE
Design for email verification

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#143]
- Email for email verification
   - Will have a message to indicate that an email has been sent
   - This will contain a button to resend an email
   - Will have a logout button
- UI to show when the user clicks on the link in their email for when the email is verified
   - Here apart from the generic error state, there is one where the token is expired.
- Banner for optional email verification (can implement later)

**Comment by mufassirkazi** [comment]
Verify email address UI: https://zpl.io/bJXe439
Token expired: zpl.io/VQlkD09
Token expired wrong email id: https://zpl.io/2EXLoOe
Generic error message: https://zpl.io/2GXLvxY
Email content+design: https://zpl.io/anjxRox

These designs use the new style guides from the revamped design. You can visit my latest comment to see those designs here at https://github.com/supertokens/supertokens-auth-react/issues/45

**Comment by rishabhpoddar** [comment]
@mufassirkazi  Token expired screen just has a message.. no form or anything. The user just needs to close the page.

**Comment by rishabhpoddar** [comment]
@mufassirkazi the verify email address UI focuses on the button to resend email.. however that button should not be the focus since the email is already sent. Instead, the focus should be the text that says check your email to verify it (or something like that)

**Comment by rishabhpoddar** [comment]
@mufassirkazi "Token expired wrong email id" is not needed

**Comment by rishabhpoddar** [comment]
@mufassirkazi missing screen:
- email verification successful (this should have a button like "OK" which takes the user to the app)
- in the verify email UI, if there is an error, we need to show something went wrong there
- When the link is clicked, there is a loading state.. the UI for that. There can be a generic error too. In the error case, we can show the generic UI screen saying please reload to try again. Another error can be that the token has expired. Finally, in case of success, after the loading UI, we show the email verification successful UI (point one in this list)

**Comment by mufassirkazi** [comment]
Comment has been updated. Please let me know if any other changes

**Comment by rishabhpoddar** [comment]
I have spoken to @mufassirkazi about some more UI changes...

**Comment by mufassirkazi** [comment]
Comment updated.

**Comment by NkxxkN** [comment]
https://app.zeplin.io/project/5aaa0de98d835c7b25637f2e/screen/5ff32e6c7b94022752e42b37 

Can you make sure the success icon is exportable as SVG @mufassirkazi ?

**Comment by rishabhpoddar** [comment]
@mufassirkazi , also, the colour of the primary button in all screens, for example the colour of the "continue" button in success screen, must be the same as the orange colour.. since that's the primary colour. Does this make sense?

**Comment by mufassirkazi** [comment]
@NkxxkN updated the design. 

@rishabhpoddar Yeah. I was more along the lines of having a secondary colour but then I realised that the login ui is not going to have too many buttons anyways. Updated to orange.

**Comment by mufassirkazi** [comment]
@rishabhpoddar Had a discussion with advait and we believe that the success email verification screen is not required. Instead we can just have a normal notification message on top of the main app screen saying "email successfully verified" that goes away after 2 seconds. What are your thoughts on this?

**Comment by NkxxkN** [comment]
@mufassirkazi there are two modes of email verification.
We are currently implementing the "required" mode, which enforces email verification to use the app. That mode needs the email verification screen.
Next, we are going to add the optional mode with the banner that you described.

**Comment by rishabhpoddar** [comment]
@mufassirkazi I prefer not to do this as it adds complexity to the UI from a technical point of view. Complications like:
- What if their redirect URL is a page that does not require auth? Then that bar on top will not be shown.
- We will still need a dedicated loading page when they click on the email verification link. So doing this does not eliminate the need for 
- Having a bar on top can be unexpected to the developer as their UI may not allow for that space.

**Comment by rishabhpoddar** [comment]
@NkxxkN I think @mufassirkazi is talking only about the screen after the email verification link is clicked. That screen will be there for both "optional" and "required" methods.

The difference between the two methods is that in optional, the prompt to check or resend email is via a bar on top, unlike in the required method, which will be a page.

**Comment by NkxxkN** [comment]
I realised that and deleted my silly comment 😄

**Comment by rishabhpoddar** [comment]
Closing this issue since the design had been finalised..
