### ISSUE TITLE
[FR] provide helm chart

### ISSUE THREAD

**Issue by Hokwang** [supertokens/supertokens-core#146]
## 🚀 Feature

Hi,

I read an article about supertokens recently.
I am using keycloak for openid auth for some dev tools (eg. jenkins, ...)
I want to compare and move to supertokens if suitable.

But I can't find helm chart. Do you have a plan for how to deploy on kubernetes cluster?

Which tool is cloud native and easy to deploy on kubernetes, is my main interesting now.

**Comment by rishabhpoddar** [comment]
Hey @Hokwang, we had created a helm chart at one point in time, but it needs updating I think. @bhumilsarvaiya can help out with this.

**Comment by bhumilsarvaiya** [comment]
Hey @Hokwang , I've started working on the helm chart for supertokens-mysql in this repo: https://github.com/bhumilsarvaiya/supertokens-docker-mysql/tree/helm-chart

Please feel to have a look and share your thoughts. If you want to use any other database, please let us know here. I'll prioritize working on that first.

**Comment by Hokwang** [comment]
@bhumilsarvaiya 
sorry for late.

I think it is awesome, but I want to add
- add postgresql and user can select DB
- add ingress path so user can deploy `https://my.company.com/supertoken` not `https://supertoken.my.company.com`

**Comment by bhumilsarvaiya** [comment]
Hey @Hokwang, thanks for the suggestions. I was initially thinking of creating one helm per DB. Even the docker images for supertokens are per DB. Do you think it would be a good idea to create one helm chart that supports all the databases instead of creating one helm chart per DB?

**Comment by Hokwang** [comment]
@bhumilsarvaiya yes! one helm chart is best.
and actually managing several helm chart is hard.

you can control multiple DB in one helm chart as you know already and maybe you can make one docker image.
you can using config file or env variable.

**Comment by rishabhpoddar** [comment]
@Hokwang unfortunately, we cannot make one docker image, since we put only the relevant JARs for each DB in a docker image. That is, we do not want to put postgres plugin JARs if the user is going to use MySQL - this is to optimise for versioning and for the size of the docker image.

That being said, would you still recommend having one helm chart for all?

**Comment by Hokwang** [comment]
@rishabhpoddar yeah, understand, you think jar is big enough, but anyway you can make one helm chart and it is still best way.

**Comment by rishabhpoddar** [comment]
Sounds good. @bhumilsarvaiya please make one help chart, and put it in the supertokens-core repo.

**Comment by bhumilsarvaiya** [comment]
@rishabhpoddar okay, then I think we will go with one helm chart for all DB approach and I'll push the changes to the supertokens-core repo. @Hokwang Thanks for the suggestions. Also, do you have any reference to helm chart that supports multiple databases?

**Comment by rishabhpoddar** [comment]
- For MySQL image: https://github.com/supertokens/supertokens-docker-mysql/tree/master/helm-chart
- For PostgreSQL image: https://github.com/supertokens/supertokens-docker-postgresql/tree/master/helm-chart

Closing this issue.
