### ISSUE TITLE
Add email & password management base functions

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#16]
These functions can be used to build out a simple login / sign up API. These will probably form the basis of higher level login flows that will come next

- [ ] userId = createUserWithEmailAndPassword(email, password) else throw error if email is already exists

- [ ] userId = getUserWithEmailAndPassword(email, password) throw an error if email doesn't exist

- [ ] success = resetPassword(userId, password) throw an error if userId doesn't exist

- [ ] email =  getEmailForUserId(userId) throw an error if a user doesn't exist

- [ ] userId = getUserIdForEmail(email) or undefined if email doesn't exist

- [ ] exists = checkIfEmailExists(email)

**Comment by Adhikaribharath** [comment]
Is this till open ?

**Comment by rishabhpoddar** [comment]
Hi @Adhikaribharath ,
Yes. This is still open. However, we are still in the process of laying down the architecture, and it's discussed [in this issue](https://github.com/supertokens/supertokens-core/issues/24). Please feel free to participate in it :)

**Comment by rishabhpoddar** [comment]
Closing since this is outdated.
