### ISSUE TITLE
release auth-react 0.4.2

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#167]
# 🚀 Feature
- Fix UI for mobile responsiveness
- Fix padding in inputs
- Update focus state

# 📅 Checklist

### Dev Tag

 - [x] [supertokens-auth-react:X.Y](https://github.com/supertokens/supertokens-auth-react/tree/X.Y)
    - [x] Various browsers - Safari, Firefox, Chrome, Edge
    - [x] Mobile responsiveness

### 💻 NPM and core release

 - [x] [supertokens-auth-react:X.Y](https://github.com/supertokens/supertokens-auth-react/tree/X.Y)
   - [x] Updated tests to use `supertokens-node` from npm registry
   - [x] Updated `peerDependencies` to use `supertokens-website` from npm registry

### 🔀 Others

 - [supertokens-react-themes:X.Y](https://github.com/supertokens/supertokens-react-themes/tree/X.Y)
   - [x] Updated [PR]() with `supertokens-auth-react` from npm registry
   - [x] Release [theme demo app](https://supertokens-react-themes.surge.sh) on surge using `npm run surge`

- [supertokens-demo-react:master](https://github.com/supertokens/supertokens-nextjs-demo/tree/master)
   - [x] Updated [PR]() using `supertokens-node` and `supertokens-auth-react` npm registry.
   - [x] Deployed to [demo site](http://emailpassword.demo.supertokens.io/)

 - [supertokens-nextjs-demo:master](https://github.com/supertokens/supertokens-nextjs-demo/tree/master)
     - [x] [PR]() updated using `supertokens-node` and `supertokens-auth-react` npm registry.
     - [x] Merged to master

**Comment by NkxxkN** [comment]
I don't think we need that file for patch changes. 
The reason being that we use `^X.Y.Z` for our dependencies in package.json files and that patches usually do not require doc updates.

Only for minor and major changes to repo.

Let me know if you think otherwise or close if you agree @rishabhpoddar

**Comment by rishabhpoddar** [comment]
Actually, don't we need to update the theme apps / demo app somehow to use the latest version?

**Comment by NkxxkN** [comment]
Correct. Cleaning up the list.
