### ISSUE TITLE
Release supertokens-auth-react 0.5.X

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-core#174]
# 🚀 Feature

- Success/Error ticks displayed in input
- Show password displayed in inputs
- Better password manager handling
- Remove autofill browser styling
- User Facing typescript definitions
- setState race condition for redirecting to auth page on successful signup

# 📅 Checklist

### Dev Tag

 - [x] [supertokens-auth-react:0.5](https://github.com/supertokens/supertokens-auth-react/tree/0.5)
    - [x] Various browsers - Safari, Firefox, Chrome, Edge
    - [x] Mobile responsiveness

### Others

 - [supertokens-demo-react:master](https://github.com/supertokens/supertokens-nextjs-demo/tree/master)
     - [x] In progress
     - [x] [PR](https://github.com/supertokens/supertokens-demo-react/pull/4) Ready using supertokens/supertokens-auth-react#0.5 and supertokens/supertokens-node#0.5 github repositories in package.json

### 📚 Documentation

- [x] EmailPassword main documentation update
   - [x] In progress [PR]()
   - [x] Deployed on [test site](https://test.supertokens.io/docs/emailpassword/introduction)

- [x] NextJS main documentation update
   - [x] In progress [PR](https://github.com/supertokens/main-website/pull/227)
   - [x] Deployed on [test site](https://test.supertokens.io/docs/emailpassword/nextjs/supertokens-with-nextjs)

- [x] auth-react documentation update
   - [x] In progress [PR](https://github.com/supertokens/main-website/pull/225)
   - [x] Deployed on [test site](https://test.supertokens.io/docs/auth-react/introduction)

### 💻 NPM and core release

 - [x] [supertokens-auth-react:0.5](https://github.com/supertokens/supertokens-auth-react/tree/0.5)

### 🔀 Others

- [supertokens-demo-react:master](https://github.com/supertokens/supertokens-nextjs-demo/tree/master)
   - [x] Updated [PR]() `supertokens-auth-react` npm registry.
   - [x] Deployed to [demo site](http://emailpassword.demo.supertokens.io/)

### 📚 Documentation

- EmailPassword main documentation update
   - [x] Deployed on [production site](https://supertokens.io/docs/emailpassword/introduction)

- NextJS main documentation update
   - [x] Deployed on [production site](https://test.supertokens.io/docs/emailpassword/nextjs/supertokens-with-nextjs)

- auth-react documentation update
   - [x] Deployed on [production site](https://supertokens.io/docs/auth-react/installation)

**Comment by NkxxkN** [comment]
@rishabhpoddar You can update demo site.

**Comment by rishabhpoddar** [comment]
updated!
