### ISSUE TITLE
emailpassword + third party brainstorming + design

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#177]
## RID: `thirdpartyemailpassword`

Related to https://github.com/supertokens/supertokens-core/issues/154

- We will have a UI that is sort of in two parts. The first part will be social providers and below that will be a tab view of sorts that will contain the emailpassword UI. Maybe this will look ugly, in which case, we will have two tabs like we have in email password now, and both will contain social provider UI (either of them can be used to sign in / up).

- No account consolidation will be there.. so we treat email password as just another “third party” provider.

**Comment by mufassirkazi** [comment]
### Designs

Sign up: https://zpl.io/2vE7WLn
Sign in: https://zpl.io/a7jOEzW
Something went wrong screen: https://zpl.io/aX67qMj

@NkxxkN, the designs are basically the same as they were independently. The only thing that is important is the spacings between different elements. The hover and different feedback states will remain the same as they are in the independent social login and email password designs.
