### ISSUE TITLE
Release anti-csrf change

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#179]
# 🚀 Feature
- Related to issue https://github.com/supertokens/supertokens-node/issues/63

# 📅 Checklist

### Dev Tag
 - [x] [supertokens-core:X.Y](https://github.com/supertokens/supertokens-core/tree/X.Y)
 - [x] [supertokens-node:X.Y](https://github.com/supertokens/supertokens-node/tree/X.Y)

### Others

 - [supertokens-demo-react:master](https://github.com/supertokens/supertokens-nextjs-demo/tree/master)
     - [x] In progress
     - [x] [PR]() Ready using supertokens/supertokens-auth-react#X.Y and supertokens/supertokens-node#X.Y github repositories in package.json
     - [x] Make changes to `master` and `deploy` branch

### 💻 NPM and core release

 - [x] [supertokens-core:X.Y](https://github.com/supertokens/supertokens-core/tree/X.Y)
    - Docker update
       - [x] MySQL
       - [x] Postgres
       - [x] MongoDB
    - [x] try.supertokens.io
    - [x] Update SaaS config
 - [x] [supertokens-node:X.Y](https://github.com/supertokens/supertokens-node/tree/X.Y)

### 🔀 Others

- [supertokens-demo-react:master](https://github.com/supertokens/supertokens-nextjs-demo/tree/master)
   - [x] Updated [PR]() using `supertokens-node` and `supertokens-auth-react` npm registry.
   - [x] Deployed to [demo site](http://emailpassword.demo.supertokens.io/)
- [x] Change node version inside all examples inside supertokens-auth-react and NextJS PR

**Comment by rishabhpoddar** [comment]
@bhumilsarvaiya please update the checklist above when done the SaaS change we had discussed.

@NkxxkN please update the examples' package.json to use the latest node SDK version (v3.4.0)

**Comment by NkxxkN** [comment]
Done! Closing as it seems that everything is done.
