### ISSUE TITLE
Third party recipe design

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#181]
@mufassirkazi please upload the designs in this issue

**Comment by mufassirkazi** [comment]
## Designs Part 1 

- Popular social logins: https://zpl.io/bP6PmKL
- Custom social login: https://zpl.io/2yKOyML
- Social provider does not provider an email: https://zpl.io/VqdWwM4
- Loading state: https://zpl.io/a3AelYd
- Something went wrong screen: https://zpl.io/bP6PmAM
- Sign up UI with social login: https://zpl.io/2vE7WLn
- Sign in UI with social login: https://zpl.io/a7jOEzW

### Note: 

Designs part 1 does not include the different alternative states that we are going to handle later on (i.e, what is same email is used but a different login provider when signing in, showing the state of what login provider was used last to sign in, etc)

Also, for now we are going with the normal approach of having just a small blue link of sign in, if already registered or sign up if not registered yet in the main sign up and sign in ui with social logins. But later on we can build a tab based approach the way Auth0 does it that lets you switch between sign up and sign in. The choice to use which version rests with the user alone.

**Comment by rishabhpoddar** [comment]
> Popular social logins

- I prefer not having text like two click login as I don't think it's something that everyone will be ok with by default, and then we will have to provide a way to change it.. which I don't want to as it's more docs, more config etc.. Please see what other solution providers do for this.

> Custom social login

- What is the feedback on click for the various buttons here?

> Social provider does not provider an email

- Not a valid screen.

> Something went wrong screen

- This is going to be a message in the login screen itself.. the message can be like "Something went wrong", or it can be "The chosen login provider did not give us your email, please use another one, or contact support.". So we don't need a screen for this.

> Sign up UI with social login & Sign in UI with social login

- Both are irrelevant for this issue. Please remove them from here.

**Comment by mufassirkazi** [comment]
> I prefer not having text like two click login as I don't think it's something that everyone will be ok with by default

Alternative text's : 

Login or Create an Account
You are signed out
Home
Your App
<Company Name>
Welcome
Get started
Login / Register

Let me know which one you prefer.

**Comment by mufassirkazi** [comment]
Designs have been updated.

**Comment by rishabhpoddar** [comment]
Seems good for now. @NkxxkN 
- will these do? 
- Do you need mobile views as well?

**Comment by NkxxkN** [comment]
That looks good to me! Good job @mufassirkazi 💪 

- Button animation: Not going to introduce a new colour. We will use the same strategy as we have already:
10% darker on hover/focus with ripple propagation effect.

- For email password the text is : Sign Up / Sign In. Why changing to Login / Register ? Let's keep it consistent?

- No need for extra designs for mobile. It's all about the container resizing properly which will need to be tested by me before release.

**Comment by rishabhpoddar** [comment]
> For email password the text is : Sign Up / Sign In. Why changing to Login / Register ? Let's keep it consistent?

Agreed. @mufassirkazi please make the necessary change to the design

**Comment by rishabhpoddar** [comment]
@mufassirkazi in the sign in screen, we also don't need the "Please select an identity provider" subtext:
- It's obvious what needs to be done
- If there is only one provider being used, the text is even more useless...

**Comment by rishabhpoddar** [comment]
@mufassirkazi closing this issue.. please feel free to reopen in case you want  to
