### ISSUE TITLE
Extract email verification into its own recipe (like how session is its own recipe)

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#183]
## RID
`emailverification`

## FDI
https://github.com/supertokens/frontend-driver-interface/issues/9

## CDI
https://github.com/supertokens/core-driver-interface/issues/7

## Frontend interface for auth recipes to use
TODO:
- checking if an email is verified
- The recipe should take care of showing the UI in the right path
- The config changes (no longer need "OFF"
- A way to check if this recipe has been initialised

## Backend interface for auth recipes to us
TODO:
- Same functions that are already exposed
- Will require user to init this

## Core changes
TODO:
- Remove is_verified from user table
- Create new table for this recipe
- Change queries to use this new table
- Removing of some of the errors

## Documentation changes
- How to configure this (With EmailVerification.init({..}) on frontend and on backend)
- Migration between old core and this one

**Comment by rishabhpoddar** [comment]
@NkxxkN please see the "Frontend interface for auth recipes to use" section above and lmk if anything is missing.

**Comment by NkxxkN** [comment]
Looks good to me!

Now we have:

```js
// Without
SuperTokens.init({
  recipeList: [
    EmailPassword.init(),
    Session.init()
  ]
 }
 
 // With
SuperTokens.init({
  recipeList: [
    EmailPassword.init(),
    Session.init(),
    EmailVerification.init()
  ]
 }
```

Hence, no configs needed for the mode?

**Comment by rishabhpoddar** [comment]
> Hence, no configs needed for the mode?

Yes. But we still need to have the various styling / API hooks etc config that we have right now.

**Comment by rishabhpoddar** [comment]
@NkxxkN as per our discussion, we will try and not change any of the user-facing configs related to email verification and see how it goes.
