### ISSUE TITLE
Email verification recipe as per CDI 2.7

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#185]
## Related issue
- https://github.com/supertokens/core-driver-interface/issues/7
- https://github.com/supertokens/supertokens-core/issues/183

----------
- [x] SQLite
- [x] PostgreSQL
- [x] MySQL
- [x] MongoDB
- [x] Docker
   - [x] Table names

**Comment by rishabhpoddar** [comment]
@NkxxkN one consequence of extracting this into its own recipe is that now a user can be associated with multiple email addresses and a variable number of those can be verified / unverified. I think this is OK from a security point of view. What are your thoughts?

**Comment by NkxxkN** [comment]
- How does the driver choose which email to send for verification to the core?
- Is there a primary/secondary email attribute?

Looks good! It's a good optimisation for the future.

**Comment by rishabhpoddar** [comment]
> How does the driver choose which email to send for verification to the core?

The recipe will get the session, and then from there we can get the user's email ID and use that email.

> Is there a primary/secondary email attribute?

No. This is an auth recipe thing... for email verification, everything is tied to {userId, email} pair.
