### ISSUE TITLE
ThirdParty release

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#197]
# 📝 Notes

# 🚀 Feature

Description of the new feature

# 📅 Checklist

### Dev Tag
 - [x] [supertokens-core:3.3](https://github.com/supertokens/supertokens-core/tree/3.3)
 - [x] [supertokens-node:4.0](https://github.com/supertokens/supertokens-node/tree/4.0)
 - [x] [supertokens-website:X.Y](https://github.com/supertokens/supertokens-website/X.Y)
 - [x] [supertokens-auth-react:0.6](https://github.com/supertokens/supertokens-auth-react/tree/0.6)
    - [x] Various browsers - Safari, Firefox, Chrome, Edge
    - [x] Mobile responsiveness
    - [x] Make sure using with-typescript example that types are correct for every new configs exposed to users

### Others

 - [supertokens-demo-react:master](https://github.com/supertokens/supertokens-demo-react/tree/master)
     - [x] In progress
     - [x] [PR]() Ready using `supertokens/supertokens-auth-react#0.6` and `supertokens/supertokens-node#4.0` github repositories in `package.json`
     - [x] Make changes to `emailpassword` and `thirdparty` branch

### 📚 Documentation

- [x] EmailPassword main documentation update
   - [x] If UI changes, make sure to update the themes netlify link.
   - [x] In progress [PR]()
   - [x] Deployed on [test site](https://test.supertokens.io/docs/emailpassword/introduction)

- [x] NextJS main documentation update
   - [x] In progress [PR]()
   - [x] Deployed on [test site](https://test.supertokens.io/docs/emailpassword/nextjs/supertokens-with-nextjs)

- [x] nodejs documentation update
   - [x] In progress [PR]()
   - [x] Deployed on [test site](https://test.supertokens.io/docs/nodejs/installation)

- [x] auth-react documentation update
   - [x] In progress [PR]()
   - [x] Deployed on [test site](https://test.supertokens.io/docs/auth-react/introduction)

- [x] supertokens-website documentation update
   - [x] In progress [PR]()
   - [x] Deployed to [test site](https://test.supertokens.io/docs/website/introduction)

- [x] website changes (test.supertokens.io)
   - [x] homepage
   - [x] pricing page feature list
   - [x] comparison chart in the pricing page

### 💻 NPM and core release

 - [x] [supertokens-core:X.Y](https://github.com/supertokens/supertokens-core/tree/X.Y)
    - Docker update
       - [x] MySQL
       - [x] Postgres
       - [x] MongoDB
    - [x] try.supertokens.io
    - [x] Update SaaS config
 - [x] [supertokens-node:4.0](https://github.com/supertokens/supertokens-node/tree/4.0)
 - [x] [supertokens-website:X.Y](https://github.com/supertokens/supertokens-website/tree/X.Y)
 - [x] [supertokens-auth-react:0.6](https://github.com/supertokens/supertokens-auth-react/tree/0.6)
   - [x] Updated tests to use `supertokens-node` from npm registry
   - [x] Updated `peerDependencies` to use `supertokens-website` from npm registry

### 🔀 Others

- [supertokens-demo-react:master](https://github.com/supertokens/supertokens-demo-react/tree/master)
   - [x] Updated [PR]() using `supertokens-node` and `supertokens-auth-react` npm registry.
   - [x] Deployed to [emailpassword demo site](http://emailpassword.demo.supertokens.io/)
   - [x] Deployed to [thirdparty demo site](http://thirdparty.demo.supertokens.io/)

- [supertokens-auth-react:master](https://github.com/supertokens/supertokens-auth-react/tree/master)
   - [x] Update examples to use latest `supertokens-node` and `supertokens-auth-react`
   - [x] Update all examples for any breaking changes (like for multi tenancy callbacks?)

- [next.js:canary](https://github.com/vercel/next.js/tree/canary)
   - [x] Update `with-supertokens` examples to use latest `supertokens-node:4.0` and `supertokens-auth-react:0.6` [PR](https://github.com/vercel/next.js/pull/22223)
   
### 📚 Documentation

- EmailPassword main documentation update
   - [x] Deployed on [production site](https://supertokens.io/docs/emailpassword/introduction)

- NextJS main documentation update
   - [x] Deployed on [production site](https://test.supertokens.io/docs/emailpassword/nextjs/supertokens-with-nextjs)

- nodejs documentation update
   - [x] Deployed on [production site](https://supertokens.io/docs/nodejs/installation)

- auth-react documentation update
   - [x] Deployed on [production site](https://supertokens.io/docs/auth-react/installation)

- supertokens-website documentation update
   - [x] Deployed to [production site](https://supertokens.io/docs/website/introduction)
   
- website changes (supertokens.io)
   - [x] homepage
   - [x] pricing page feature list
   - [x] comparison chart in the pricing page

**Comment by NkxxkN** [comment]
Closing. Only thing left is the PR to next.js to update dependencies. I have added to the already existing updating the docs.
