### ISSUE TITLE
Access control recipe

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#204]
- set multiple roles for a user
- fetch / edit roles for a user
- define permissions for a role
- fetch / edit permissions for a role
- organise roles into a heirarchy?
- provide a way to fetch permissions/ roles within an API, and also protect an API based on a role
- Checkout "google Zanzibar"
- Perhaps we can use https://casbin.org/ in the core to provide this feature.

**Comment by rishabhpoddar** [comment]
Closing this in favour of https://github.com/supertokens/for-zenhub/issues/98

**Comment by 7hibault** [comment]
This feature would be essential for us to use supertokens, which looks very promising in all other aspects !

@rishabhpoddar the link you provided leads to a 404, in favor of what issue did you close this ?

**Comment by rishabhpoddar** [comment]
@7hibault oops. Sorry.. that link is to a private repo. Reopening this. But essentially, that link points to https://github.com/supertokens/supertokens-core/issues/382 (which is also wip)

**Comment by iAziz786** [comment]
@rishabhpoddar I see #382 is closed, I was wondering what are the pending tasks for this issue to state completed?

**Comment by rishabhpoddar** [comment]
@iAziz786 whilst the core has the APIs for roles and permissions, we need to modify the backend SDKs to add helper functions and to a way to easily add roles and permissions to the session's access token payload.

**Comment by iAziz786** [comment]
Understood, if we can do that natively by APIs so we can start using it now?

**Comment by rishabhpoddar** [comment]
> Understood, if we can do that natively by APIs so we can start using it now?

Yes. You can always call the APIs of the core yourself. Here is the API spec: https://app.swaggerhub.com/apis/supertokens/CDI/2.14.0#/User%20Roles%20Recipe

**Comment by iAziz786** [comment]
Thanks Rishabh!

**Comment by ThomasKraaibeek** [comment]
@rishabhpoddar I'm currently trying to talk to the CDI API you mentioned in your comment above. I'm using FastAPI as my backend and i'm trying to set user roles as a new user registers by overriding the `emailpassword_sign_up_post` method. In the API docs there's no mention of how the API expects the API_Token to be presented in the HTTP request. Could you clarify on how to talk to the API from backend code?

**Comment by rishabhpoddar** [comment]
@ThomasKraaibeek You can use any networking library to talk to the core. The API Token should be passed as a header in the http request, the key of the header is `api-key`.

**Comment by ThomasKraaibeek** [comment]
@rishabhpoddar Thank you so much!

**Comment by rishabhpoddar** [comment]
@Dan6erbond the node sdk and the core has been updated fro this. Other SDKs are still in the process and will take 1-2 months.

**Comment by rishabhpoddar** [comment]
We now have user roles functions in all the backend SDKs:
- node SDK >= 9.3.0
- golang SDK >= 0.7.2
- python SDK >= 0.9.1

**Comment by Dan6erbond** [comment]
Has documentation or a recipe guide already been released?

**Comment by rishabhpoddar** [comment]
> Has documentation or a recipe guide already been released?

Should be done by the weekend or early next week.
