### ISSUE TITLE
Issue with running docker image on Mac M1 chip

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#210]
<img width="1362" alt="Screen_Shot_2021-04-08_at_12 08 13_PM" src="https://user-images.githubusercontent.com/2976287/114009554-de6f3d00-9880-11eb-973b-5b75737ddf2d.png">

**Comment by rishabhpoddar** [comment]
We need to move to JDK 15 for this. Steps involved are:
TODO

**Comment by rishabhpoddar** [comment]
@bhumilsarvaiya please let me know the changes required to docker build process.

**Comment by rishabhpoddar** [comment]
@Infi-Knight we need to change the use-oss page to detect if the current computer is ARM based and if yes, then pass that option when downloading the binary. If we cannot detect that automatically, then we need to provide that option to the user in the UI so that they can download the right version for their computer. Something like how [this site](https://jdk.java.net/archive/) does - if you notice how they say "Linux/AArch64" and "Linux/x64".

**Comment by mufassirkazi** [comment]
## Version A

![Screen Shot 2021-04-23 at 3 20 33 PM](https://user-images.githubusercontent.com/46087290/115854196-a141a800-a447-11eb-9a8b-7e010b1a0aa0.png)


## Version B

![Screen Shot 2021-04-23 at 3 21 19 PM](https://user-images.githubusercontent.com/46087290/115854208-a3a40200-a447-11eb-9359-ea547306bff4.png)

Which version is preferred?

**Comment by Infi-Knight** [comment]
version A

**Comment by rishabhpoddar** [comment]
Neither.. I prefer an idea where we use a popup after someone clicks on linux in which we explain there are two versions...

**Comment by mufassirkazi** [comment]
https://zpl.io/agwENjA

@Infi-Knight , this popup will only be visible  if the selected core version is >= 3.4. If it is lesser than 3.4 than show the current UI (the one with only 3 download buttons) which automatically downloads the binary for linux.
