### ISSUE TITLE
Using argon instead of bcrypt for password hashing.

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#215]
More information here: https://news.ycombinator.com/item?id=15646743#:~:text=forum%20writte...-,I'd%20recommend%20you%20to%20use%20Argon2%20instead%20of%20bcrypt,does%20not%20have%20insecure%20parameters.

**Comment by rishabhpoddar** [comment]
We added argon2 hashing in v3.12. It is not the default however, because in order to use it, one must configure the right settings for their hardware.

**Comment by ejabu** [comment]
👍🏻 Recently I also got a problem when my coworkers using mac, and I'm using Linux.

I found the password_hash value filled in differently
