### ISSUE TITLE
Allow passing of full connection string for dbs along with providing all the fields individually.

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#221]
If this is passed, we use that, else we look at each field individually. This applies to:
- [x] MySQL
- [x] PostgreSQL
- [x] Mongodb 
- [x] Docker:
    - [x] MySQL
    - [x] PostgreSQL
    - [x] MongoDB 
- [x] Also allow users to not pass a password for all the dbs

**Comment by cerino-ligutom** [comment]
+1
