### ISSUE TITLE
Extract error message to be displayed from 400 response

### ISSUE THREAD

**Issue by ankitjena** [supertokens/supertokens-core#233]
## 🚀 Feature
We need to extract the error message from 400 response to be displayed by the supertokens frontend. 
Usecase in my case being customising the signinup api and sending an error if email exists.

From the signinup API of thirdparty recipe

**Comment by rishabhpoddar** [comment]
I have released a new version of our SDKs to give you the feature you requested:
- supertokens-auth-react: v0.9.1
- supertokens-node: v4.3.2


To send a custom error message that displays on the frontend, you can throw the following error from your signinup API:
```
    throw new STError(
        {
            type: "FIELD_ERROR",
            message: "Some custom message"
        },
        recipeInstance
    );
```

This will show "Some custom message" on the signup screen when the user tries to login using a social provider.
