### ISSUE TITLE
Support user metadata

### ISSUE THREAD

**Issue by tobiasdiez** [supertokens/supertokens-core#239]
## 🚀 Feature

It would be nice if one could store/receive additional metadata associated to a user. This could be for example some external user ids (e.g. stripe customerId) or additional infos such as the full name etc. This is especially helpful if one uses supertokens as a complete user authentication solution and doesn't have an additional database.

## Implementation details

As a reference, here is the documentation for auth0: https://auth0.com/docs/users/metadata

**Comment by rishabhpoddar** [comment]
@tobiasdiez that is a good idea. Though we would add this as a separate recipe that can be added to an existing login recipe so that users who do not need this, won't get this feature. This would enable us to keep providing the minimum required db schema from our side.

**Comment by rishabhpoddar** [comment]
This feature has been released: https://supertokens.com/docs/thirdpartyemailpassword/common-customizations/usermetadata/about
