### ISSUE TITLE
Describing a login / sign up architecture

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#24]
# This conversation has been moved [to this document](https://www.notion.so/Login-architecture-943fad3da436476787421706839c0f9c).

Please feel free to ignore the remainder of this issue thread.

**Comment by rishabhpoddar** [comment]
- Logging in to a single website is a subset of allowing SSO into multiple sites. Hence, our architecture must be developed for SSO, however, by default, we must make it extremely simple to add simple login to a website.
- Single login to a site should not involve using OAuth since there is no third part involved. However, that's not the case for SSO login where the SSO provider is treated as a third party.
- Moving from a single website login to a SSO login should be supported such that there is no disturbance to the end user's experience.
- We must use `httpOnly` cookies to maintain a session across the backend and frontend. This has some side effects that in SSO, the different applications must be talking to different APIs such that:
  - The API domains are different (one cannot be a substring of the other); or
  - The API paths are different - no common paths + one cannot be a substring of the other
- For SSO, each app must have its own database space. A database space is defined by the db location and set of tables. So, all apps can share the same database, but have different tables, or each app can have it's on a separate database. There will have to also be a database space to manage the SSO logins themselves.
- The SSO page should be completely controlled by SuperTokens. This means that there will have to be a webserver in ST that's exposed to the client (or some reverse proxy). However, in case of simple login, there is no such page, and everything goes through the api layer?
- The same react component should be used for providing the login / sign up form with, or without SSO.
- For each action that requires storing user information in the db (for an app), provide an alternate callback that the user can use to store/retrieve that information however they want - within the client SDK.
- Provide several default external login providers. Allow the user to drop in a plugin JAR of another social provider - However, how would this work exactly? For example, how would the login button of that provider reach the frontend login form? 
---------
Research points:

- [ ] How does embedded login work with alternate on premises and SaaS auth solutions?

- [ ] How to allow the user to easily expose a subdomain that's controlled by SuperTokens?

**Comment by rishabhpoddar** [comment]
# Logging into a single website architecture:

![Uploading IMG_1531.jpg…]()

**Comment by rishabhpoddar** [comment]
### Login / Sign up widget on the frontend
- To give maximum flexibility to the user, we should let them directly customise the `html / css` of the widget - not by overriding the class, but directly making changes to the files. Hence, we cannot simply have a widget component in our frontend lib that we tell them to use. We need to generate the component for them somewhere, which they can edit directly.
- One idea is to allow them to change the widget in a dashboard provided by SuperTokens. However, that code becomes outside their main frontend code - which can be annoying to maintain.
- Another idea is to provide a cli on the frontend (via the frontend package), that will generate the relevant components for them.. However, the code style of the files generated may not be the code style they would like. Furthermore, it adds the need to use another CLI (which is not the main SuperTokens CLI)
- A combination of the above means that we can let them generate a widget on the dashboard, and give them the code for it there, which they can put into their project. This would mean, there is no need for a CLI as such.
- If the SSO layer is fully controlled by us, how will we give them the same flexibility for the login / sign up form? Perhaps, it's a better idea to not control the full SSO layer, and treat it like any other part of their website.
-

**Comment by kjaisingh** [comment]
Spoke to a few people who own companies that operate their websites, through both contacts and the internet, and the general consensus was this - having a login/signup widget provided by a third-party is generally not very appealing because (a) apparently ad-blockers often prevent these from loading, (b) users sometimes have their Javascript disabled and (c) existing login/signup flows are very easy to integrate.

**Comment by rishabhpoddar** [comment]
@kjaisingh A few quesitons:
- What kind of companies (startups, tech / non tech?) did you ask, and who in them (engineering people?)?

- When you say "login/signup widget provided by a third-party", what do you mean by "provided by". Like how Auth0 provides it?

- > apparently ad-blockers often prevent these from loading

   Ad-blockers prevent Auth0 style logins from loading? I don't think so.. If not, then what kind of login are you talking about?

- > users sometimes have their Javascript disabled

   Won't this be a much bigger issue in general? For example, it would mostly prevent the whole site from working anyway...

- > existing login/signup flows are very easy to integrate

   Which existing ones - ones provided by the frameworks themselves? If so, then why do people use Auth0 / Okta in the first place?

**Comment by rishabhpoddar** [comment]
Here is some more (random) info. Firebase usage
```
// REACT CODE
export const AuthAppRouter = () => {
  const [user, loading, error] = useAuthState(firebase.auth());
  useEffect(() => {
    if (!loading && !error && !user) {
      firebase.auth().signInWithRedirect(provider);
    }
  }, [user, loading, error]);
  if (loading || error)
    return (
      <div className={styles.loadingWrapper}>
        <Spinner />
      </div>
    );
  return <AuthAdminRouter />;
};

// GOLANG CODE
token := r.Header.Get("token")
t, err := AuthClient.VerifyIDToken(context.Background(), token)
if err != nil {
	http.Error(w, e.Wrap(err, "invalid id token").Error(), http.StatusInternalServerError)
	return
}

ctx := context.WithValue(r.Context(), "uid", t.UID)
next(w, r.WithContext(ctx))

```

**Comment by rishabhpoddar** [comment]
Related discussion on #51

**Comment by rishabhpoddar** [comment]
# The need for a formal specification language.

It seems that to provide amazing flexibility to a developer for how they want to build out their *login & signup experience*, we need to have some sort of a formal language that they can use to specify their needs. Something like [teraform](https://www.terraform.io/), but for login & sign up flows. 

### Terminology:
- **Flow**: This guides the overall login / sign up experience. Flows can comprise of other flows. Some flows MUST have certain elements (which can be customised in a fixed manner). Example of flows:
   - Sign-in flow: Can have subflows for password or social sign in
   - Signup flow: Can have subflows of needing email verfication on sign up or not.
   - Email verification flow: Can have via OTP or magic link
   - The whole sign up / in experience flow: Comprises of the above flows.

- **Element**: A flow comprises of elements. An element is defined as its own, complete module, such that there is no other element that can be inside it (not entirely sure about the definition at the moment). Some elements have a UI, whilst others don't. Examples:
   - Password sign in form
   - Logic for verifying passwords
   - Logic for storing passwords
   - Google sign in redirect page UI
   - Password reset page UI
   - Password reset backend logic
Elements can have multiple outputs. For example, the logic for verifying password can have a success boolean or an error output (in case a database lookup fails). Therefore, flows can have multiple outputs.

- **Element enhancement**: Given an existing element, adding some behaviour on top of it to create a wrapper element. For example, if we have a "login via email & password" element, we can create a new *enhanced element* that adds the "remember me" functionality to it. In this specific case, this functionality would change the output of the underlying login element which can be consumed by the next element. The remember me feature would also enhance the *session element* to take in the "remember me" boolean and create a different type of session (that's longed lived).

- **Links**: These connect elements with each other. They can be of types:
   - Pass through links: Pass the output of one element to the input of another
   - If links: Depending on certain conditions, the output of an element can be routed to a specific element.


### Customisations:
- Flow customisations via the dashboard. Think of this as a drag and drop flow chart that can be built. Or a script file that they can specify (like in teraform).

- UI level element customisation via the dashboard or code. For example:
   - Changing the colour of the login form

- Logic level element customisation via code. For example:
   - Sign up field validation logic on the frontend
   - Fetching information to format the slack notification to send after a user signs up.
   - This would be done via configuration params and callbacks.

- Creation of an element / enhanced element:
   - An element can be either a UI, frontend logic, or backend logic element. If there is a need to define something across these layers, then that is a flow.
   - UI elements:
       - Since these are defined in the dashboard, there needs to be a way for the frontend UI to communicate with the SuperTokens core. This can be done via a "proxy API" that is implicitly defined by the user in their API layer. This proxy API is completely defined and handled by us.
       - TBD
   - frontend logic: TBD
   - backend logic element: TBD

--------------
Discussion points:
- Is the above too much of an overkill (even medium term)?
- Is the above way too complex? Maybe this is the only way to actually provide good flexibility?
- If there are many frontend elements, would they all be packaged into one repo? Or would we have one repo per frontend element? That would be a nightmare to manage and too many import statements for the user? On the other hand, if there is only one repo, that would eventually become HUGE? (same for backend elements)
- How can the above be simplified?
- Can we define user experiences and see what kind of a flow makes sense? From there, we can work backwards to making this idea more concrete.

**Comment by NkxxkN** [comment]
> Are there any solutions like this already? One is arengu

This makes me think of the approach taken by Intercom for their messenger apps: https://app.intercom.com/a/canvas-kit-builder

**Comment by rishabhpoddar** [comment]
A few conclusions:
- Not going to focus on SSO at the moment
- On the frontend, users will use a component that will do an initial handshake with the core (via a proxy API). This handshake will tell the UI element what needs to be rendered.
- The UI of the form can be customised by overriding the CSS. Simple customisations can be provided by props to the react component.
- Social logins will be their own package which will be installed by the user if they need it. By default, they will not get them
- We will plug into the route of the react app (similar to Auth0). So that we can automatically add things like a forgot password page.

**Comment by rishabhpoddar** [comment]
@NkxxkN 

> This makes me think of the approach taken by Intercom for their messenger apps: https://app.intercom.com/a/canvas-kit-builder

This is a good way to allow modification of the login form via a dashboard! Thanks for the reference.

**Comment by rishabhpoddar** [comment]
We should have a "powered by SuperTokens" somewhere. Not in the login / sign up page. But perhaps the email verification / forgot password flows.

**Comment by rishabhpoddar** [comment]
We want to provide a React component on the frontend. This means that we also must have its CSS:
- Where will the CSS be? In the library we provide as a `.css` file which will be imported into the react component file? 
- How do we make sure that our CSS doesn't spoil theirs and vice versa?
   - Using an iFrame: This is the safest option. However, it's not a component anymore.
   - Using shadow-root: This will prevent CSS clashing, however, if they want to override the CSS, how will they do that?
   - Using scoped CSS (wrap our component in a `div` with a unique ID. All CSS is then within that ID. While this is easy to override, this can cause CSS clashing?

@NkxxkN can you please see how to best solve this issue?

**Comment by rishabhpoddar** [comment]
@bhumilsarvaiya , can you please read up about [this](https://aws.amazon.com/cloud-directory/) and summarise what this is?

**Comment by rishabhpoddar** [comment]
## How sign up with email & password work:

### Frontend:
We can provide a package `supertokens-auth-react` which will have a `SignupWithEmailAndPassword` component.
Then someone can make a `MySignup` component which is a child to `SignupWithEmailAndPassword` like:
```
<SignupWithEmailAndPassword>
  <MySignup title="...", primaryColour="..." />
</SignupWithEmailAndPassword>
```
Here, `MySignup` is a sign up form which allows the user to change the title of the form and the primary colour of the form. The actual sign up form asks for an email and a password, with some validation logic. It also has a button that says "Sign up".

Once that button is clicked, that component will call something like:
```
this.props.signUpClicked(email, password);
```
The `SignupWithEmailAndPassword` will pass the `signUpClicked` function to `MySignup` since we are talking about sign up with email/password protocol.

This way, users, and others can create their own component like `MySignup`.
`MySignup` can be very complex as well. full page, part of a page, showing just one box at a time, vs all at the same time. So this way, we can add themes for sign up with email & password.

And then we have one that is `SuperTokensSignupWithOAuth` or `SuperTokensSignupWithMobileOTP` etc.

### Networking:
TODO

### Backend logic:
TODO

### Making this into an element:
TODO

### Making this into a flow:
TODO

**Comment by rishabhpoddar** [comment]
## How sign in with email & password work:
TODO

**Comment by rishabhpoddar** [comment]
## How password reset will work

**Comment by rishabhpoddar** [comment]
## How will the above flows be put together into one big flow for full user experience
TODO

**Comment by NkxxkN** [comment]
Building on the above, and by leverage [React composition](https://reactjs.org/docs/composition-vs-inheritance.html), [styled components](https://styled-components.com/docs/basics#getting-started), [and theming](https://styled-components.com/docs/advanced#theming), we could obtain something like:


In `App.js` (example of what a real world app could look like)

```js
import React from 'react';
import {SuperTokensSignupWithPasswordAndEmail} from 'supertokens-auth-react';

// Optional, if the user wants to define his own theme or take it from one of the theme we provide.
import SuperTokensTheme from './my/personal/theme.js';

(...)

function App() {
  return (
    <ErrorBoundary>
        <BrowserRouter>

            // This would be the wrapper that helps define React Routing for SuperTokens
            // i.e. takes precedence of routes such as `/forgot-password` `/email-verification` etc...
            <SuperTokensRoute>


                <Suspense fallback={<Fragment />}>
                    <Switch>

                    <Route path="/app">
                        <LoggedInComponent />
                    </Route>

                    <Route>
                        <LandingPage />
                        // Somewhere here...


                        <SuperTokensProvider theme={SuperTokensTheme} >
                            <SuperTokensSignupWithPasswordAndEmail
                                header={<h1>SignUpFormForMycompany</h1>} // Optional
                                footer={<h1>Powered By SuperTokens (Feel free to override)</h1>} // Optional
                            />
                        </SuperTokensProvider>
                        
                    </Route>

                    </Switch>
                </Suspense>

            </SuperTokens>

        </BrowserRouter>

    </ErrorBoundary>
  );
}

export default App;

```

Where: `SuperTokensSignupWithPasswordAndEmail.js`

```js

import React from 'react';
import styled from 'styled-components';
const SuperTokensSignupWithPasswordAndEmailWrapper = styled.div`
	border-radius: ${props => props.theme.signupContainerBorderRadius || "#fff"};
	color: ${props => props.theme.textColor || "#000"};
        (...)
`;

function SuperTokensSignupWithPasswordAndEmail(props) {
	return (<SuperTokensSignupWithPasswordAndEmailWrapper>
        {props.header}
        <SuperTokensSignupWithPasswordAndEmailForm style={props.style} />
        {props.footer}
    </SuperTokensSignupWithPasswordAndEmailWrapper >);
}

export default SuperTokensSignupWithPasswordAndEmail;
```

Where `SuperTokensSignupWithPasswordAndEmailForm.js`


```js

import React from 'react';
import styled from 'styled-components';
const SuperTokensSignupWithPasswordAndEmailWrapper = styled.div`
	backgroundColor: ${props => props.theme.secondaryBackground || "#FFF"};
        (...)
`;

function SuperTokensSignupWithPasswordAndEmailForm(props) {
	return (<SuperTokensSignupWithPasswordAndEmailFormWrapper>
        <StyledInput name="email" value="name" className={this.style.emailLabel} /> // Will either use what we defined in StyledInput (Out of scope here), or what is defined in className 
        <StyledInput name="password" className={this.style.passwordLabel} />
    </SuperTokensSignupWithPasswordAndEmailWrapper>);
}

export default SuperTokensSignupWithPasswordAndEmailForm;
```

We could then provide different themes, and maybe the community will provide their own. A theme would essentially look like: 

`my.theme.js`
```js
import { createSuperTokensTheme, responsiveFontSizes } from "@material-ui/core";

// colors
const primary = "#d5dfe9";//"#b3294e";
const secondary = "#829bc1";
const darkBlack = "rgb(36, 40, 44)";
const background = "#193055";
const contentBackground = "#2f4566";
const warningLight = "rgb(81, 100, 129)";
const warningMain = secondary;
const linkColor = "#ff3434";

// border
const borderWidth = 2;
const borderColor = "rgba(0, 0, 0, 0.13)";

// breakpoints
const xl = 1920;
const lg = 1280;
const md = 960;
const sm = 600;
const xs = 0;

const theme = {
  palette: {
    primary: { main: primary },
    secondary: { main: secondary },
    common: {
      black,
      darkBlack
    },
    warning: {
      light: warningLight,
      main: warningMain,
      dark: warningDark
    },
    background: {
      default: background,
      secondary: contentBackground
    },
    secondaryBackground: background,
  },
  border: {
    borderColor: borderColor,
    borderWidth: borderWidth
  },
  overrides: {
    SuperTokensDivider: {
      root: {
        backgroundColor: borderColor,
        height: borderWidth
      }
    },
    SuperTokensFormHelperText: {
      root: {
        color: primary
      }
    },
    SuperTokensDialog: {
      paper: {
        width: "100%",
        maxWidth: 430,
        marginLeft: spacing,
        marginRight: spacing
      }
    },
    SuperTokensFormLabel: {
      root: {
        color: secondary,
        "&$disabled": {
          color: secondary
        }
      }
    },
    SuperTokensLink: {
      root: {
        color: linkColor
      }
    },
    SuperTokensAccordion: {
      rounded: {
        borderRadius: "8px"
      }
    },
    SuperTokensEmailLabel: {
      root: {
        paddingLeft: 2,
        paddingRight: 2,
        paddingTop:  2,
        paddingBottom: 2,
        borderTopColor: secondary,
        borderBottomColor: secondary,
        borderBottom: `${borderWidth}px solid ${borderColor}`,
        [`@media (max-width:  ${sm}px)`]: {
          paddingLeft: spacing,
          paddingRight: spacing
        }
      },
      body: {
        cursor: "pointer",
        color: primary
      }
    }
  }
};

export default theme;
```



This solution with styled components and themes is used by React libraries as popular as [material-ui](https://material-ui.com/) which makes it a very good candidate to help us let the users override styling of components. The advantage is that React developers are already used to those styled components (most of them), and will not need extensive docs from us. They will use docs that are provided by styled components library.

**Comment by NkxxkN** [comment]
> The SignupWithEmailAndPassword would also use a shadow-root to protect the CSS of the webpage and the child widget.

I found https://apearce.github.io/react-shadow-root/ which appears to help shadow Routing React styled components

**Comment by rishabhpoddar** [comment]
@NkxxkN excellent! One point about:
```js
 <SuperTokensProvider theme={SuperTokensTheme} >
    <SuperTokensSignupWithPasswordAndEmail
        header={<h1>SignUpFormForMycompany</h1>} // Optional
        footer={<h1>Powered By SuperTokens (Feel free to override)</h1>} // Optional
    />
</SuperTokensProvider>
```

I was imagining as `SuperTokensSignupWithPasswordAndEmail` === `SuperTokensProvider`, and `SuperTokensTheme` would take the `header` and `footer` props. One missing part is also a completion handler, that will be called on successful sign up. So, this code would look like:
```js
<SuperTokensSignupWithPasswordAndEmail
        onSignupComplete={this.onSignupComplete}>
    <SuperTokensTheme
        header={<h1>SignUpFormForMycompany</h1>} // Optional
        footer={<h1>Powered By SuperTokens (Feel free to override)</h1>} // Optional
    />
</SuperTokensSignupWithPasswordAndEmail>

```

In the above, the `SuperTokensTheme` component is what will take define the styling & UI of the actual form.

Please correct me if I have misunderstood something.

**Comment by NkxxkN** [comment]
`SuperTokensProvider` is a wrapper that provides access to all its child components to the theme. It would essentially be:

```js
import React from 'react';
import  {ThemeProvider} from 'styled-components';

default function SuperTokensProvider(props) {
  return (
    <ThemeProvider theme={props.theme}>
       {props.children}
    </ThemeProvider>
  );
}
```

We could also take another approach of defining `SuperTokensSignupWithPasswordAndEmail` directly with the theme (to make it more magical for end user):

```js
import React from 'react';
import styled from 'styled-components';
import  {ThemeProvider} from 'styled-components';

const SuperTokensSignupWithPasswordAndEmailWrapper = styled.div`
	border-radius: ${props => props.theme.signupContainerBorderRadius || "#fff"};
	color: ${props => props.theme.textColor || "#000"};
        (...)
`;

function SuperTokensSignupWithPasswordAndEmail(props) {
	return (
            <ThemeProvider theme={props.theme}>
                  <SuperTokensSignupWithPasswordAndEmailWrapper>
                       {props.header}
                      <SuperTokensSignupWithPasswordAndEmailForm style={props.style} />
                      {props.footer}
                  </SuperTokensSignupWithPasswordAndEmailWrapper >
          </ThemeProvider>
       );
}

export default SuperTokensSignupWithPasswordAndEmail;
```

And used as follows:


```js
<SuperTokensSignupWithPasswordAndEmail
        theme={theme}
        onSignupComplete={this.onSignupComplete}
        onSignupFailure={this.onSignupFailure}>
        (...)
        header={<h1>SignUpFormForMycompany</h1>} // Optional
        footer={<h1>Powered By SuperTokens (Feel free to override)</h1>} // Optional
/>
```

I don't think there is a need for a `SuperTokensTheme`, since the theme and styling can be applied to all child components of the one that defines the theme. 
Does that make sense to you?

**Comment by rishabhpoddar** [comment]
I think there is a misunderstanding of what "a Theme" means (bad naming from my side maybe 😅). To me, a theme is defined by:
- UX Behaviour: Some examples:
   - Showing email & password fields, and sign up button in one go
   - Showing email & password field. Once those are filled and proper, then we show the sign up button
   - Showing just an email field with a next button. Then showing the password field with a sign up button
   - The theme designed for a full-page experience 
   - The theme designed for a widget experience
   - A theme that shows the number of users signed up in the past 1 hour (social proof?)
- UI behaviour: This would be things like the animation effects if any, or showing errors like a popup vs next to the fields etc..
- UI styling: The would be the CSS layer.

So when I say `SuperTokensTheme`, I mean a component that defines all of the above. This component can be written by us, or others.
