### ISSUE TITLE
Create tables based on the recipes that are used

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#246]
We can do this by creating sets of tables right when they are needed, and not upfront. So when a query comes for a certain recipe, all the tables of that recipe are created if they don't already exist.

On core start, we keep track of which tables are already created to cache that info.

When creating a table, we check if that table exists already, and gracefully handle errors in case of race condition on creating tables.

**Comment by angelbelmon** [comment]
Bien

**Comment by jscyo** [comment]
Closing since this is not required
