### ISSUE TITLE
Support set database scheme for tables [postgres]

### ISSUE THREAD

**Issue by chenkaiC4** [supertokens/supertokens-core#251]
## 🚀 Feature

(A clear and concise description of what the feature is.)

now, tables is created in public schema. but i want to create tables at schema like 'supertokens', and let the public to be used by normal business logic tables.

**Comment by rishabhpoddar** [comment]
You can specify the db name you want SuperTokens to create its tables in. You can do this by:

## If using docker:
Specify the `POSTGRESQL_DATABASE_NAME` env var
```
docker run \
    -p 3567:3567 \
    ...
    -e POSTGRESQL_DATABASE_NAME="supertokens" \
    -d supertokens/supertokens-postgresql
```

## If not using docker:
You will need to edit the `config.yaml` file to have:
```
postgresql_database_name: "supertokens"
```

**NOTE: You will need to provide a user that has permissions to write to this table.**

---------------
If you do not want to create a separate db, an alternate method is to add a prefix to all table names created by SuperTokens. You can do this by following [this guide](https://supertokens.io/recipe-redirect?to=/quick-setup/database-setup/rename-database-tables).

**Comment by chenkaiC4** [comment]
@rishabhpoddar just one table, and i read the doc, but not found some env to make it work. The prifix name is work, but i just want to give a schema to collect the tables created by supertokens. can some env support it?

**Comment by rishabhpoddar** [comment]
Can you please elaborate more on what "but i just want to give a schema to collect the tables created by supertokens" means? Perhaps an example of what you would like?

**Comment by chenkaiC4** [comment]
for example:
```
docker run -d -it --name tokens \
    -p 3567:3567 \
    -e POSTGRESQL_USER="postgres" \
    -e POSTGRESQL_PASSWORD="123456" \
    -e POSTGRESQL_HOST="172.17.0.1" \
    -e POSTGRESQL_PORT="5432" \
    -e POSTGRESQL_DATABASE_NAME="postgres" \
    -e POSTGRESQL_TABLE_NAMES_PREFIX='st' \
    -d supertokens/supertokens-postgresql
```
db images like below:

![image](https://user-images.githubusercontent.com/7543145/120294490-d23fb300-c2f8-11eb-8ff9-e952dd658738.png)
 

all the tables is in `schema: public`. i want to make them to another `schema` like `supertokens`.

**Comment by chenkaiC4** [comment]
create table "supertokens"."emailpassword_users" (
....
)

**Comment by chenkaiC4** [comment]
the schema i used is this: https://www.postgresql.org/docs/current/ddl-schemas.html

**Comment by rishabhpoddar** [comment]
Understood. I'll add this to our roadmap. However, since this isn't an essential feature for SuperTokens, it may be pushed down a bit.

**Comment by chenkaiC4** [comment]
i'd like to contribute this little feature, let me have a try :)

**Comment by chenkaiC4** [comment]
@rishabhpoddar https://github.com/supertokens/supertokens-postgresql-plugin/pull/11

can you help me to run the test? I am not familiar with the java development, but from the code level, I think I have found the right place to add this feature.

**Comment by rishabhpoddar** [comment]
Thanks for the two PRs @chenkaiC4. You will need to also change the java code, specifically [this file](https://github.com/supertokens/supertokens-postgresql-plugin/blob/master/src/main/java/io/supertokens/storage/postgresql/ConnectionPool.java) to take into account the config.

If you are not familiar with Java, then no worries.. when we have a look at this issue, we will build on top of your PR :)

**Comment by chenkaiC4** [comment]
@rishabhpoddar i have read the code of [file](https://github.com/supertokens/supertokens-postgresql-plugin/blob/master/src/main/java/io/supertokens/storage/postgresql/ConnectionPool.java), but i don't know what have to be changed, this ConnectionPool.java seems have no relationship with this feature.

**Comment by rishabhpoddar** [comment]
@chenkaiC4 so I assume that a schema is something that you need to create in your db, and then point supertokens to use that schema. Am I correct?

If so, then in this file, you will need to specify the `currentSchema=myschema` query param in the `jdbc` URL [here](https://github.com/supertokens/supertokens-postgresql-plugin/blob/master/src/main/java/io/supertokens/storage/postgresql/ConnectionPool.java#L64). The value of this would be read from the config file, and by default it should be `public`?

**Comment by rishabhpoddar** [comment]
@chenkaiC4 I'll add this feature in 1-3 days and release a new version of the core and docker image

**Comment by rishabhpoddar** [comment]
@chenkaiC4 I had misunderstood some part of your PR - my bad. It seems that you added the schema to the table name which means there is no need to change ConnectionPool.java. Thanks!

**Comment by chenkaiC4** [comment]
> @chenkaiC4 I had misunderstood some part of your PR - my bad. It seems that you added the schema to the table name which means there is no need to change ConnectionPool.java. Thanks!

:clinking_glasses: waitting for the new release~ this feature can separate core user data of supertokens from business data at schema level.  Avoid misoperation of data.

**Comment by rishabhpoddar** [comment]
Repoening until it has been released

**Comment by rishabhpoddar** [comment]
@chenkaiC4 this feature has been released. We have not bumped the core's version for this feature, so you will need redownload version 3.4 for postgresql. If you are using docker, be sure to delete the docker image from your system first, and then try again. 

You can see docs changes for this as well: https://supertokens.io/recipe-redirect?to=/quick-setup/database-setup/postgresql (pick your recipe -> scroll down, and under "Connect SuperTokens to your database" section, there is a point about table schemas.

 Finally, I have added you as a contributor to supertokens-core (in its readme). Thank you.

**Comment by chenkaiC4** [comment]
@rishabhpoddar thank you! amazy speed! i will go on to give a doc update PR.
