### ISSUE TITLE
Change to email verification / reset password email design

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#254]
Below the main CTA button in the email, we should also show the actual URL in case someone wants to copy / paste that in their browser (The URL should also be clickable). An example:

<img width="546" alt="Screenshot 2021-06-03 at 17 21 38" src="https://user-images.githubusercontent.com/2976287/120640683-6728e480-c490-11eb-8920-3d92afda96a1.png">

-----------
TODO:
- [x] New design
- [x] Change to API
- [x] Change to docs

**Comment by rishabhpoddar** [comment]
@mufassirkazi

**Comment by rishabhpoddar** [comment]
@bhumilsarvaiya

**Comment by mufassirkazi** [comment]
## Design: 
https://zpl.io/29GjXAd
https://zpl.io/amLeGEr

Note: The url part is a placeholder.
