### ISSUE TITLE
Email OTP recipe design

### ISSUE THREAD

**Issue by mufassirkazi** [supertokens/supertokens-core#260]
### Screen 1 (Sign In)
Sign in: https://zpl.io/bPB8RqL
Write state: https://zpl.io/25zv5ee
Something went wrong: https://zpl.io/VqzerOJ
Email is invalid: https://zpl.io/bLq0XNY
Email doesn't exist error: https://zpl.io/aRRJAZK

### Screen 2 (Enter OTP)
OTP screen: https://zpl.io/bzdepnE
Writing state (OTP screen): https://zpl.io/2yDe5lq
Something went wrong (OTP screen): https://zpl.io/29GR9PB
Invalid OTP error: zpl.io/aNO8Wpe
OTP resent: https://zpl.io/bWGJ5qx - (The OTP resent message banner should stay for 2 seconds after which it should go away)
If the email entered doesn't exist: https://zpl.io/bePEm6l

During sign up, if email already exists: https://zpl.io/2jqnO34

Actual email: https://zpl.io/blOEB8k

Note: Most of the components designs have been replicated from other recipes to ease development.

**Comment by rishabhpoddar** [comment]
Feedback:
- I prefer if the email doesn't exist error is how it's done in emailpassword recipe -> it just shows the error in the UI under the enter email screen asking them to sign up
- In Enter OTP screen there are two errors that have been missed. Either way, there should be a way to go back.
    - email doesn't exist while signing in (assuming OTP is valid)
    - email exists while while signing up (assuming OTP is valid)
- Actual email -> please clearly provide the subject of the email.

**Comment by mufassirkazi** [comment]
> email doesn't exist while signing in (assuming OTP is valid)
> email exists while while signing up (assuming OTP is valid)

In both scenarios, if true, the user should not be able to see the "Enter OTP" screen. We say in the sign in / sign up form itself that "Email doesn't exist, please sign up instead" or "Email already exists, please sign in instead". Right?

**Comment by rishabhpoddar** [comment]
> In both scenarios, if true, the user should not be able to see the "Enter OTP" screen. We say in the sign in / sign up form itself that "Email doesn't exist, please sign up instead" or "Email already exists, please sign in instead". Right?

There is a config on the backend that devs can turn on to show email OTP screen anyway to prevent account enumeration attacks.

**Comment by rishabhpoddar** [comment]
Closing cause we have now already made a passwordless recipe.
