### ISSUE TITLE
Hapi.js support

### ISSUE THREAD

**Issue by export-mike** [supertokens/supertokens-core#268]
## 🚀 Feature

notice theres a middleware for express however no hapi version.

## Implementation details

at a high level in userland, something like this ```await server.register(supertokens, options)```

**Comment by rishabhpoddar** [comment]
This is related to https://github.com/supertokens/supertokens-node/issues/123

**Comment by bhumilsarvaiya** [comment]
Hapi.js framework support will be added once PR (https://github.com/supertokens/supertokens-node/pull/146) is merged.
