### ISSUE TITLE
Update user's email in ThirdParty recipe

### ISSUE THREAD

**Issue by dulowski-marek** [supertokens/supertokens-core#276]
### Goal
Developer should be able to update user's email in ThirdParty recipe.

### Questions
- Should we allow changing user email if they are registered with 3rd party provider?
- Should this require signing up with the same/different provider again?
- What is the account email used for? (Essentially what other parts of the system would be influenced by email change)

**Comment by rishabhpoddar** [comment]
> Should we allow changing user email if they are registered with 3rd party provider?

Hmm... probably not. So the CDI spec associated with this may need updating.

> Should this require signing up with the same/different provider again?

I don't think I understand.

> What is the account email used for? (Essentially what other parts of the system would be influenced by email change)

It's only used as "extra" information for the dev, and for email verification purposes. It's not used to ID the user (the third party provider's userId is used for that during sign in / up)

**Comment by dulowski-marek** [comment]
> Hmm... probably not. So the CDI spec associated with this may need updating.

If this is not allowed, we shouldn't probably expose such mechanism in the first place (which invalidates this task).

**Comment by rishabhpoddar** [comment]
Yes. However, the CDI spec may need changing.. so please do so, and then can close this issue.

**Comment by rishabhpoddar** [comment]
I don't think there is an API for this in the CDI spec. So closing this issue.
