### ISSUE TITLE
Fetch ThirdParty users based on email

### ISSUE THREAD

**Issue by dulowski-marek** [supertokens/supertokens-core#277]
### Goal
Developer should be able to fetch multiple users associated with one email.

**Comment by rishabhpoddar** [comment]
- I think you should have a look at the CDI spec first: https://github.com/supertokens/core-driver-interface/blob/master/v2.8.0.md. This API spec is already defined in there.

> What permissions are required to execute this action?

We don't have roles and permissions.. just an optional API key that the core has.

**Comment by rishabhpoddar** [comment]
@dulowski-marek im not sure what to review for this.. the core changes for this have already been merged. The next part of this task is a change in the node SDK, the PR for which is missing..
