### ISSUE TITLE
Typo on migration page

### ISSUE THREAD

**Issue by paustint** [supertokens/supertokens-core#279]
## 📚 Documentation

>You **cna** find the database schema used by SuperTokens by visiting the recipe page > Quick setup > Database setup > And then choosing your db > Scrolling down and expanding the "See table structure" drop down.

Should be :
>You can find...

![image](https://user-images.githubusercontent.com/5461649/126248413-d1516de5-246a-4733-b844-152f768d716b.png)

**Comment by rishabhpoddar** [comment]
hey! Thanks for the issue. This has been fixed in a new version of documentation we will be releasing sometime this week. The PR for that is: https://github.com/supertokens/docs/pull/65. So i'm closing this.
