### ISSUE TITLE
Add config option for email password reset token validity time

### ISSUE THREAD

**Issue by robinsento** [supertokens/supertokens-core#297]
Implement config option to define email password reset token validity time to be other than 1h, analogous to reset_token_validity option.

**Comment by rishabhpoddar** [comment]
This would require:
- [ ] config change (for password reset as well as other constants?)
- [ ] config logic change + emailpassword recipe change
- [ ] tests
- [ ] documentation changes
- [ ] docker env vars changes

## What are all the configs we want to expose
- password reset token lifetime
- TODO

**Comment by rishabhpoddar** [comment]
We have released this in the new core: Version 3.6.0
