### ISSUE TITLE
Change thirdparty userId to be varcahr(255)

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#306]
There was an error where someone was trying to sign up using the thirdparty recipe and postgres rejected the query cause of `value too long for type character varying(128)` - and in the thidparty table, only the `third_party_user_id` column has 128 chars limit.

Error log reference:

[https://app.zenhub.com/files/231921809/8968d6d6-bcdd-48d8-aa60-fd556e934acd/download](https://app.zenhub.com/files/231921809/8968d6d6-bcdd-48d8-aa60-fd556e934acd/download)

**Comment by rishabhpoddar** [comment]
@jscyo progress on this?

**Comment by jscyo** [comment]
Facebook:

**Comment by jscyo** [comment]
Information around user-id size from Oauth providers is not explicitly mentioned in their docs.

I've found these two answers which say that varchar(128) should be fine for Google and Facebook

- [Google Oauth user id size](https://stackoverflow.com/questions/19409030/google-oauth-2-0-user-id-datatype-for-mysql#:~:text=I'm%20implementing%20Google%20OAuth,OAuth%20is%2021%20digits%20long)
- [FaceBook User Id size](https://stackoverflow.com/questions/7566672/whats-the-max-length-of-a-facebook-uid)

Ive contacted Github and Facebook support for more information about this

**Comment by jscyo** [comment]
The OIDC defines that the `sub` claim (the user id) cannot exceed 255 ascii character length, so there is a possibility that some providers are issuing user id's which are more than 128 characters. [source](https://openid.net/specs/openid-connect-core-1_0.html#IDToken)

**Comment by rishabhpoddar** [comment]
@jscyo any updates on this?

**Comment by rishabhpoddar** [comment]
See what schema keycloack uses for this

**Comment by jscyo** [comment]
The schema for storing social providers for keycloak is as follows:
```
       Column       |          Type          | Collation | Nullable | Default 
--------------------+------------------------+-----------+----------+---------
 identity_provider  | character varying(255) |           | not null | 
 realm_id           | character varying(36)  |           |          | 
 federated_user_id  | character varying(255) |           |          | 
 federated_username | character varying(255) |           |          | 
 token              | text                   |           |          | 
 user_id            | character varying(36)  |           | not null | 
Indexes:

```
They use varachar(255) to store their third party user ids.

**Comment by Shashwat121** [comment]
Hi @rishabhpoddar ! Is the bug still open to work? I wish to contribute to this as my first ever contribution to OSS. !

**Comment by rishabhpoddar** [comment]
hey @Shashwat121! Thanks for showing interest. This issue is being worked on in another PR. Please find another issue that you like. We also have issues in our backend and frontend SDKs :)
