### ISSUE TITLE
Build from source

### ISSUE THREAD

**Issue by videv-periyarit** [supertokens/supertokens-core#311]
## 📚 Documentation
Referring to this to find instructions for building from source: https://github.com/supertokens/supertokens-core/wiki/Building-from-source 

Stuck in the 7th step:
To install SuperTokens on your machine, run java -classpath "./cli/*" io.supertokens.cli.Main true $@ (you may need to use sudo, but first try without it)

If someone wants to fully understand the code by git cloning/ building/ installing, what is the documentation one needs to follow?  The one I followed seems to be outdated.  My intention is to pickup the code and contribute by doing enhancements or bug fixes.

**Comment by rishabhpoddar** [comment]
Hi @videv-periyarit , I have updated the building from source instrs (there were some errors in step 6 as well, so you will need to do that again).

For contributing to the core, you can also see this: https://github.com/supertokens/supertokens-core/blob/master/CONTRIBUTING.md if you have not already :)

Closing this issue for now, but feel free to reopen in case you find other issues.
