### ISSUE TITLE
Define DB schemas for passwordless

### ISSUE THREAD

**Issue by porcellus** [supertokens/supertokens-core#321]
Define DB schemas for the upcoming Passwordless feature

**Comment by rishabhpoddar** [comment]
@porcellus 

## Feedback:
- [ ] `passwordless_devices` still has `PRIMARY KEY (code_id)`. It should be `PRIMARY KEY (device_id_hash)`
- [ ] `passwordless_codes` cannot have `device_id_hash` as `UNIQUE`
- [ ] `CREATE INDEX passwordless_codes_email_index ON passwordless_codes USING HASH (email);` needs to change to be on `passwordless_devices` (and same goes for phone number index).
- [ ] Once this is finalized, you should make one version for mysql and sqlite as well. Those won't have the constraint names, and the `created_at` in those will be `BIGINT UNSIGNED`.

**Comment by porcellus** [comment]
```sql
CREATE TABLE IF NOT EXISTS passwordless_users (
    user_id CHAR(36) NOT NULL,
    email VARCHAR(256) UNIQUE,
    phone_number VARCHAR(256) UNIQUE,
    time_joined BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS passwordless_devices (
	device_id_hash CHAR(44) NOT NULL,
        email VARCHAR(256),
	phone_number VARCHAR(256),
	failed_attempts INT UNSIGNED NOT NULL,
	PRIMARY KEY (device_id_hash)
);
CREATE INDEX passwordless_devices_email_index ON passwordless_devices USING HASH (email);
CREATE INDEX passwordless_devices_phone_number_index ON passwordless_devices USING HASH (phone_number);

CREATE TABLE IF NOT EXISTS passwordless_codes (
	code_id CHAR(36) NOT NULL,
        device_id_hash NOT NULL,
	link_code CHAR(44) NOT NULL UNIQUE,
	created_at BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY (code_id),
        FOREIGN KEY (device_id_hash)
          REFERENCES passwordless_devices(device_id_hash) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX passwordless_codes_created_at_index ON passwordless_codes(created_at);
```

**Comment by porcellus** [comment]
Since the implementation started I'll close this. Please refer to the code for the current version.
