### ISSUE TITLE
Config structure definition for the core

### ISSUE THREAD

**Issue by porcellus** [supertokens/supertokens-core#323]
Config structure definition for frontend / backend for Passwordless

**Comment by porcellus** [comment]
Node and frontend config structures are covered under the recipe interface issues (it was easier to include there).
The Core config we have discussed are:

```
# (OPTIONAL | Default: 5) integer value. The maximum number of code input attempts per login before the user needs to restart.
# passwordless_max_user_input_code_attemps:

# (OPTIONAL | Default: 900) integer value. Time in seconds for how long a passwordless code is valid for.
# passwordless_code_lifetime:
```

**Comment by rishabhpoddar** [comment]
# Feedback
- [ ] Change `passwordless_max_user_input_code_attemps` to `passwordless_max_code_input_attemps`.
- [ ] `passwordless_code_lifetime` should be in MS. Default should remain as 15 mins 900000 MS

**Comment by porcellus** [comment]
Since the implementation started I'll close this. Please refer to the code for the current version.
