### ISSUE TITLE
Passwordless Recipe Interface for frontend SDK

### ISSUE THREAD

**Issue by porcellus** [supertokens/supertokens-core#324]
Passwordless Recipe Interface for frontend SDK

**Comment by porcellus** [comment]
```ts
type FeatureBaseProps = {
  /*
   * Children element
   */
  children?: JSX.Element;

  /*
   * History provided by react-router
   */
  history?: any;

  /*
   * Nested Features
   * This is used to avoid reinitialising feature wrapper for nested features.
   */
  isEmbedded?: boolean;
};

export type SignInUpFormProps = {
  recipeImplementation: RecipeInterface;
  config: NormalisedConfig;
  onSuccess: () => void;
};

export type ComponentOverrideMap = {
  PasswordlessSignInUp?: ComponentOverride<typeof SignInUp>;
  PasswordlessSignInUpFooter?: ComponentOverride<typeof SignInUpFooter>;
  PasswordlessSignInUpForm?: ComponentOverride<typeof SignInUpForm>;
  PasswordlessSignInUpHeader?: ComponentOverride<typeof SignInUpHeader>;

  PasswordlessCodeInput?: ComponentOverride<typeof CodeInput>;
  PasswordlessCodeInputFooter?: ComponentOverride<typeof CodeInputFooter>;
  PasswordlessCodeInputForm?: ComponentOverride<typeof CodeInputForm>;
  PasswordlessCodeInputHeader?: ComponentOverride<typeof CodeInputHeader>;

  PasswordlessLinkLanding?: ComponentOverride<typeof LinkLanding>;
};

export type EmailOrPhoneNumber =
  | {
      email: string;
    }
  | {
      phoneNumber: string;
    };

export enum PasswordlessLoginFlowType {
  userInputCode = "USER_INPUT_CODE",
  link = "LINK",
  userInputCodeAndLink = "USER_INPUT_CODE_AND_LINK"
}

export type PasswordlessUser = {
  userId: string;
  email?: string;
  phoneNumber?: string;
};

export type CodeInfo =
  | {
      userInputCode: string;
      deviceId: string;
    }
  | {
      linkCode: string;
    };

export type RecipeInterface = {
  startSignInUp: (
    info: { email: string } | { phoneNumber: string } | { deviceId: string }
  ) => Promise<
    | { status: "OK"; deviceId: string; flowType: PasswordlessLoginFlowType }
    | { status: "GENERIC_ERROR"; message: string }
    | { status: "RESTART_FLOW_ERROR" }
  >;

  finishSignInUp: (
    codeInfo: CodeInfo
  ) => Promise<
    | { status: "OK"; createdUser: boolean; user: PasswordlessUser }
    | { status: "INCORRECT_USER_INPUT_CODE_ERROR"; triesLeft: number }
    | { status: "RESTART_FLOW_ERROR" }
  >;
  clearDeviceInfo: () => void;
};

type StyleInput = {
  style?: string; // Styles
};

export enum ContactInfoType {
  Phone = "PHONE",
  Email = "EMAIL"
}

export type NormalisedConfig = {
  signInUpFeature: {
    disableDefaultImplementation: boolean;

    usePhoneNumberInput: boolean;
    // autoSignInUp?: boolean;
    showLinkLanding: boolean;

    signInUpForm: StyleInput;
    linkLanding: StyleInput;
  };
  override: {
    functions: (originalImplementation: RecipeInterface) => RecipeInterface;
    components: ComponentOverrideMap;
  };
};

// We can create a fully separate type for this
export type UserInput = RecursivePartial<NormalisedConfig>;
```

**Comment by rishabhpoddar** [comment]
# Feedback on the recipe interface

## `verifyCode`
- [ ] We should not be using `triesLeft`.

## `clearDeviceInfo`
- [ ] What is the purpose of this?

**Comment by rishabhpoddar** [comment]
# Feedback on the config

- [ ] We don't need `signInUpFeature`. Instead, here we do it based on forms. So we have the following forms:
   - `enterEmailForm`
   - `enterMobileForm`
   - `linkClickedScren`
   - `enterUserInputCodeForm`
   Each of these will have a `disableDefaultImplementation`, and a style object. The `privacyPolicyLink` and `termsOfServiceLink` will go in the `enterEmailForm` and `enterMobileForm` form.
- [ ] We don't need `linkAutoSignInUp` for now.
- [ ] `usePhoneNumberInput` can be at the root level, and maybe we can change to `inputType: "email" | "phone"`? Not sure..
- [ ] What is `linkLanding` for?

**Comment by porcellus** [comment]
> usePhoneNumberInput can be at the root level, and maybe we can change to inputType: "email" | "phone"? Not sure..

It can be it's actually another option I wanted to suggest (comment right above)
> What is linkLanding for?

`linkLanding` is what would've been shown if `linkAutoSignInUp` is set to false.
This way the user could choose to not consume the code even if they clicked the link and would be directed to instead click the link in the other browser or enter the code if they want to log in there. This is fine to do later.

> linkClickedScren

This is something like the link landing I suppose, what would be on this form?

**Comment by porcellus** [comment]
> clearDeviceInfo: What is the purpose of this?

It clears the `deviceId` and the `loginAttemptId` from localstorage (or wherever we stored it).

**Comment by rishabhpoddar** [comment]
# Feedback
- [ ] `FormConfig` should also contain `disableDefaultImplementation?: boolean`
- [ ] `ContactInfoType` should not be an enum, instead make it `contactInfoType: "PHONE" | "EMAIL"` (same as in backend)
- [ ] For `NormalisedConfig`, things like `style` and `disableDefaultImplementation` are not optional. So they will need different types.
- [ ] In the userinput type, there are several fields missing - `AuthRecipeModuleUserInput` (See emailpassword recipe). This will need to be changed now though cause `AuthRecipeModuleUserInput` adds emailverification to it - which is not needed for this recipe. So for the purpose of this discussion, I think we should just remove the whole `& FormConfig` part.

> This way the user could choose to not consume the code even if they clicked the link and would be directed to instead click the link in the other browser or enter the code if they want to log in there. This is fine to do later.

Yea. We can do it later..

> This is something like the link landing I suppose, what would be on this form? Originally I thought it would be a CTA, a single button, and maybe some text... which can be called a form I suppose.

This would be something similar to what we have in the third party screen when the other provider redirects the user back to the app (just a simple spinner). It would just contain `styles` object.

**Comment by porcellus** [comment]
# RecipeInterface

```ts
export type RecipeInterface = {
  createCode: (
    info:
      | { email: string }
      | { phoneNumber: string }
      | { deviceId: string; loginAttemptId: string }
  ) => Promise<
    | {
        status: "OK";
        deviceId: string;
        loginAttemptId: string;
        flowType: "USER_INPUT_CODE" | "LINK" | "USER_INPUT_CODE_AND_LINK";
      }
    | { status: "GENERIC_ERROR"; message: string }
    | { status: "RESTART_FLOW_ERROR" }
  >;

  verifyCode: (
    codeInfo:
      | {
          userInputCode: string;
          deviceId: string;
          loginAttemptId: string;
        }
      | {
          loginAttemptId: string;
          linkCode: string;
        }
  ) => Promise<
    | {
        status: "OK";
        createdUser: boolean;
        user: {
          userId: string;
          email?: string;
          phoneNumber?: string;
        };
      }
    | {
        status: "INCORRECT_USER_INPUT_CODE_ERROR";
        failedCodeInputs: number;
        maximumCodeInputAttempts: number;
      }
    | { status: "GENERIC_ERROR"; message: string }
    | { status: "RESTART_FLOW_ERROR" }
  >;
};
```

**Comment by porcellus** [comment]
# Components

```ts
export type SignInUpProps = {
  recipeImplementation: RecipeInterface;
  config: NormalisedConfig;
  onSuccess: () => void;
};

export type SignInUpEmailFormProps = {
  recipeImplementation: RecipeInterface;
  config: NormalisedConfig;
  onSignInUpStarted: () => void;
};

export type SignInUpPhoneNumberFormProps = {
  recipeImplementation: RecipeInterface;
  config: NormalisedConfig;
  onSignInUpStarted: () => void;
};

export type SignInUpCodeInputFormProps = {
  recipeImplementation: RecipeInterface;
  config: NormalisedConfig;
  onSuccess: () => void;
};

export type LinkLandingScreenProps = {
  recipeImplementation: RecipeInterface;
  config: NormalisedConfig;
  onSuccess: () => void;
};

declare const SignInUp: React.ComponentType<SignInUpProps>;
declare const SignInUpEmailForm: React.ComponentType<SignInUpEmailFormProps>;
declare const SignInUpPhoneNumberForm: React.ComponentType<SignInUpPhoneNumberFormProps>;
declare const SignInUpCodeInputForm: React.ComponentType<SignInUpCodeInputFormProps>;
declare const SignInUpHeader: React.ComponentType;
declare const SignInUpFooter: React.ComponentType;

declare const LinkLandingScreen: React.ComponentType<LinkLandingScreenProps>;

export type ComponentOverrideMap = {
  PasswordlessSignInUp?: ComponentOverride<typeof SignInUp>;
  PasswordlessSignInUpHeader?: ComponentOverride<typeof SignInUpHeader>;
  PasswordlessSignInUpFooter?: ComponentOverride<typeof SignInUpFooter>;
  PasswordlessSignInUpEmailForm?: ComponentOverride<typeof SignInUpEmailForm>;
  PasswordlessSignInUpPhoneNumberForm?: ComponentOverride<
    typeof SignInUpPhoneNumberForm
  >;
  PasswordlessSignInUpCodeInputForm?: ComponentOverride<
    typeof SignInUpCodeInputForm
  >;
  PasswordlessLinkLandingScreen?: ComponentOverride<typeof LinkLandingScreen>;
};
```

**Comment by porcellus** [comment]
# NormalisedConfig

```ts
type NormalisedBaseConfig = {
  disableDefaultImplementation?: boolean;
  style?: string; // Styles
};

export type NormalisedConfig = {
  enterEmailForm: {
    /*
     * Privacy policy link for the sign-up form.
     */
    privacyPolicyLink?: string;
    /*
     * Terms and conditions link for the sign-up form.
     */
    termsOfServiceLink?: string;
  } & NormalisedBaseConfig;

  enterMobileForm: {
    /*
     * Privacy policy link for the sign-up form.
     */
    privacyPolicyLink?: string;
    /*
     * Terms and conditions link for the sign-up form.
     */
    termsOfServiceLink?: string;
  } & NormalisedBaseConfig;
  enterUserInputCodeForm: NormalisedBaseConfig;
  linkLandingScreen: NormalisedBaseConfig;

  contactInfoType: "PHONE" | "EMAIL";

  override: {
    functions: (originalImplementation: RecipeInterface) => RecipeInterface;
    components: ComponentOverrideMap;
  };
} & NormalisedAuthRecipeModuleConfig; // Without the email verification stuff
```

**Comment by porcellus** [comment]
#UserInput

```ts
type FeatureBaseConfig = {
  disableDefaultImplementation?: boolean;
  style?: string; // Styles
};

export type PreAPIHookContext =
  | AuthRecipeModulePreAPIHookContext
  | {
      /*
       * Pre API Hook action.
       */
      action: "PASSWORDLESS_CREATE_CODE" | "PASSWORDLESS_VERIFY_CODE";

      /*
       * Request object containing query params, body, headers.
       */
      requestInit: RequestInit;

      /*
       * URL
       */
      url: string;
    };

// No new redirects, so the base without the email verifiction related things
export type GetRedirectionURLContext = AuthRecipeModuleGetRedirectionURLContext;

export type OnHandleEventContext =
  | {
      action: "PASSWORDLESS_RESTART_FLOW";
    }
  | {
      action: "PASSWORDLESS_CODE_SENT";
    }
  | AuthRecipeModuleOnHandleEventContext; // Without the email verification stuff

export type UserInput = {
  contactInfoType: "PHONE" | "EMAIL";

  enterEmailForm?: {
    privacyPolicyLink?: string;
    termsOfServiceLink?: string;
  } & FeatureBaseConfig;

  enterMobileForm?: {
    privacyPolicyLink?: string;
    termsOfServiceLink?: string;
  } & FeatureBaseConfig;
  enterUserInputCodeForm?: FeatureBaseConfig;

  linkLandingScreen?: FeatureBaseConfig;

  override?: {
    functions?: (originalImplementation: RecipeInterface) => RecipeInterface;
    components?: ComponentOverrideMap;
  } & AuthRecipeUserInputOverride; // Without the email verification stuff
} & AuthRecipeModuleUserInput<
  // Without the email verification stuff
  GetRedirectionURLContext,
  PreAPIHookContext,
  OnHandleEventContext
>;
```

**Comment by porcellus** [comment]
>  We should also make these for thirdpartypasswordless recipe.

I'll add them after we nail these down (mostly at least). Also, I think I'll create a separate issue for the super recipe since it'll be a bit easier to read.

**Comment by rishabhpoddar** [comment]
# Feedback
- [ ] In `OnHandleEventContext`, `PASSWORDLESS_RESTART_FLOW` should be `PASSWORDLESS_RESTART_FLOW_ERROR`?
- [ ] In `OnHandleEventContext`, when the event is `PASSWORDLESS_CODE_SENT`, should we also provide the associated mobile / email / deviceId? Cause that can be used to know if it was first time code sent or resend.
- [ ] I don't like `linkLandingScreen` name. It should be called `linkClickedScreen`? It's more clear for me that way.

**Comment by rishabhpoddar** [comment]
- [ ] Change `linkLandingScreen` to `linkClickedScreen`

> I think it shouldn't have the error there because the event itself isn't necessarily an error and the only similar event I could find (UNAUTHORISED) didn't have the _ERROR ending. It depends on the UI but the user may also want to restart the flow themselves.

Agreed.

> I'd rather just provide the contact info and if it was a resend instead of the deviceId.

Agreed.

**Comment by rishabhpoddar** [comment]
@porcellus there is a state where the enter OTP screen might be shown, but the user has already signed in via magic link (in case the dev has enabled both). In this case, the enter OTP screen should change to show somethign like sign in sccessfull. how will that screen know about a successfull sign in ?

One way is to query `doesSessionExist` on the frontend periodically and check. This would work for as long as the user has clicked on the magic link in the same browser. Any other ideas?

**Comment by porcellus** [comment]
If it's the same browser we could check if the stored device info is gone. 
If the user logged-in in a different browser, the only way to know about it is to poll the backend (and the core). 
Right now we can't tell the difference between successful or expired/removed logins. We can either: 
1. Instead of deleting the devices store success/failure conditions with dates in the same table (i.e., add a `successDate`, `revokeDate` into the same rows and delete the codes)
2. When deleting the devices create a record of why/when they were deleted in a new table.

I think option 2 is a nice clean solution we can add on top of what we currently have. Do we want this in V1?

**Comment by rishabhpoddar** [comment]
- [ ] We should change `failedCodeInput` to `failedCodeInputAttemptCount`
- [ ] The function `verifyCode` is called `consumeCode` in the backend. Perhaps we should change it to `consumeCode` here too?

**Comment by rishabhpoddar** [comment]
- [ ] The design has a timer for allowing users to resend a code. I know that it requires both frontend and backend changes, but for now, we can just do it on the frontend. This way, we will need a config on the frontend for allowing users to change the time (including setting it to 0 to add no timer). I think we should call this config: `resendCodeTimeGap`

**Comment by makerboiAdi** [comment]
enterEmailForm --> emailInputForm? /  inputEmailForm / inputEmailScreen / inputEmailPage
enterMobileForm --> ''
enterUserInputCodeForm -->  
(we're using 'screen' for linkClicked_Screen_ so ideally have that consistent?)

**Comment by porcellus** [comment]
> (we're using 'screen' for linkClicked_Screen_ so ideally have that consistent?)

These things are named like this for consistency
- Form screens have the same suffix in other recipes
- enterEmailForm is used like this in the emailpassword recipe.
- both enter and input feels a little redundant to me (it's a form!), so I'd just take those off (so `emailForm`, `mobileForm`, `userInputCodeForm`)

**Comment by rishabhpoddar** [comment]
- [ ] We should just remove the prefix `enter` from these. Everything else stays the same.

**Comment by porcellus** [comment]
> We should just remove the prefix enter from these. Everything else stays the same.

I think I did this before the review.

I've renamed `loginAttemptId` to `preAuthSessionId` here as well.

**Comment by rishabhpoddar** [comment]
Sounds good!

**Comment by rishabhpoddar** [comment]
@porcellus we need to change `GENERIC_ERROR` to `GENERAL_ERROR` as that's what's being used in email password recipe (it's not there in the FDI - which is a mistake).

So we need to make this change to the frontend recipe interface, backend's API interface and the FDI spec.

**Comment by porcellus** [comment]
Since the implementation started I'll close this. Please refer to the code for the current version.
