### ISSUE TITLE
Passwordless Recipe Interface and API interface for nodeSDK

### ISSUE THREAD

**Issue by porcellus** [supertokens/supertokens-core#325]
Passwordless Recipe Interface and API interface for nodeSDK

**Comment by porcellus** [comment]
```ts
export type EmailOrPhoneNumber = {
    email: string,
} | {
    phoneNumber: string,
};

export type OptionalContactInfo = {
    email?: string,
    phoneNumber?: string,
}

export type CodeInfo = {
    userInputCode: string,
    deviceId: string,
} | {
    linkCode: string,
};

export type PasswordlessUser = {
    userId: string,
    email?: string,
    phoneNumber?: string,
    joinedAt: string,
}

export type PasswordlessDevice = {
    deviceIdHash: string,
    failedAttempts: number,
    codes: Array<{
        codeId: string,
        createdAt: string,
    }>,
}
export type PasswordlessAPIInterface = {
    signInUpPost:
        | undefined
        | ((input: any) => any),
    consumeCodePost:
        | undefined
        | ((input: any) => any),
};

export type PasswordlessRecipeInterface = {
    // Override to use custom template/contact method
    // TODO: Add info about the request
    createAndSendSignInMessage: (contactInfo: EmailOrPhoneNumber, userInputCode: string, url: string) => Promise<void>,
    // Override to customize information in the url
    // TODO: Add info about the request?
    getCodeUrl: (contactInfo: EmailOrPhoneNumber, linkCode: string) => Promise<string>,
    // Override this to override how user input codes are generated
    // By default (=undefined) it is done in the Core
    getUserInputCode?: () => Promise<string>,
    
    // Called by our API
    startSignInUp: (contactInfo: EmailOrPhoneNumber, deviceId?: string) => void,
    consumeCode: (codeInfo: CodeInfo) => Promise<void>,

    getUserById: (id: string) => Promise<PasswordlessUser | undefined>,
    getUserByContactInfo: (contactInfo: EmailOrPhoneNumber) => Promise<PasswordlessUser | undefined>,
    // getUserByEmail: (email: string) => Promise<PasswordlessUser | undefined>,
    // getUserByPhoneNumber: (phoneNumber: string) => Promise<PasswordlessUser | undefined>,

    updateUserById: (id: string, updatedContactInfo: OptionalContactInfo) => Promise<void>,
    updateUserByContactInfo: (contactInfo: EmailOrPhoneNumber, updatedContactInfo: OptionalContactInfo) => Promise<void>,
    // updateUserByEmail: (email: string, contactInfo: OptionalContactInfo) => Promise<void>,
    // updateUserByPhoneNumber: (phoneNumber: string, contactInfo: OptionalContactInfo) => Promise<void>,

    revokeCodesByContactInfo: (contactInfo: EmailOrPhoneNumber) => Promise<void>,
    // revokeCodesByEmail: (email: string) => Promise<void>,
    // revokeCodesByPhoneNumber: (phoneNumber: string) => Promise<void>,

    listCodesByContactInfo: (contactInfo: EmailOrPhoneNumber) => Promise<PasswordlessDevice[]>,
    // listCodesByEmail: (email: string) => Promise<PasswordlessDevice[]>,
    // listCodesByPhoneNumber: (phoneNumber: string) => Promise<PasswordlessDevice[]>,
}

export type PasswordlessRecipe = {
    init: (config: {
        override?: {
            functions?: (originalImplementation: PasswordlessRecipeInterface) => PasswordlessRecipeInterface,
            apis?: (originalImplementation: PasswordlessAPIInterface) => PasswordlessAPIInterface,
        }
    }) => void,
};

```

**Comment by rishabhpoddar** [comment]
# Feedback for recipe interface:

## `createAndSendCodeMessage`
- [ ] It should not be a part of the recipe interface. Instead, a callback func with a default impl
- [ ] Make `userInputCode` and `url` into an object called `code` which is of type `{userInputCode?: string, codeUrl?: string}`

## `getCodeUrl`
- [ ] It should return just the domain and the path
- [ ] Rename to `getCodeUrlDomainAndPath`

## `getUserInputCode`
- [ ] Should be moved out of the recipe.
- [ ] Rename it to `getCustomUserInputCode`

## `createCode`
- [ ] Should not return `void`

## `consumeCode`
- [ ] Should not return `void`
- [ ] Should not have `loginAttemptId`

## `validateAttemptId `
- [ ] We don't need to provide this. We can do this check in the APIs we provide, before we call the api interface function (return bad input in case this check fails).

## `updateUser`
- [ ] It should not take `info`, but take `userId` instead.
- [ ] The output should not be `void`, but should be each of the possible status outputs

## `revokeCodes`
- [ ] Should return status OK

## `listCodes`
- [ ] Rename `contactInfo` to `info`
- [ ] Should also have status OK

## `EmailOrPhoneNumber`
- [ ] We don't need this type

## `PasswordlessUser`
- [ ] We should call this `User` (like in the other recipes)

## Missing:
- [ ] Add `revokeCode`

**Comment by rishabhpoddar** [comment]
# Feedback for API interface

## `signInUpPost`
- [ ] Rename to `createCodePOST`


## All the Posts and Gets should be like POST and GET etc.

**Comment by rishabhpoddar** [comment]
# Feedback on the user config

## `TypeInput`
- [ ] We should expliclty define these as opposed to using `RecursivePartial`

## `NormalisedTypeInputSignInAndUp`
- [ ] We should have the callback functions in here
- [ ] Change `createAndSendCodeMessage` to `createAndSendCodeMessageOrEmail`
- [ ] Should we assume `USER_INPUT_CODE_AND_LINK` by default or ask the user to explicitly state what they want.
- [ ] We should add a field for if phone or email is being used (which is a compulsory field)
- [ ] We don't need `signInUpFeature`. We can put the fields inside it directly in the root config.

**Comment by rishabhpoddar** [comment]
# Feedback

- [ ]  `getCustomUserInputCode?: () => Promise<string>;` in the input should be `getCustomUserInputCode?: () => Promise<string> | string;`
- [ ] In case of `createCode`, when it returns `RESTART_FLOW_ERROR`, do we need a `message` value as well? Cause `consumeCode` doesn't have `message` when status is `RESTART_FLOW_ERROR`.
- [ ]  All the functions in recipe interface should take one single object called `input` as the param which contains all the fields in them (see existing recipe interfaces in code)
- [ ] Since you have made `flowType` non optional in `TypeInput`, I assume you want the user to pick one for sure. If so, I am OK with that.
- [ ] In normalised input, `createAndSendCodeMessageOrEmail` and `getCodeUrlDomainAndPath` are not optional. If the user has not provided them, then the input normalising function will add our defult impl to them.
- [ ] Instead of `PasswordlessLoginFlowType` being an enum, make it like `flowType: "USER_INPUT_CODE" | "LINK" | "USER_INPUT_CODE_AND_LINK"`. This way we have one less type, and users need to do one less import. (Same goes for `contanctInfoType`)
- [ ] It would be helpful if you split the above one large comments into four comments:
    - Recipe Interface
    - API Interface
    - TypeInput
    - TypeNormalisedInput 
- [ ] We should define all the interfaces and input for thirdpartypasswordless as well (as a different comments)

**Comment by porcellus** [comment]
# RecipeInterface

```ts
export type User = {
  userId: string;
  email?: string;
  phoneNumber?: string;
  joinedAt: string;
};

export type PasswordlessRecipeInterface = {
  createCode: (
    input: (
      | { email: string }
      | { phoneNumber: string }
      | { deviceId: string }
    ) & { userInputCode?: string }
  ) => Promise<
    | {
        status: "OK";
        loginAttemptId: string;
        codeId: string;
        deviceId: string;
        code: string;
        linkCode: string;
        timeCreated: number;
      }
    | { status: "RESTART_FLOW_ERROR" }
    | { status: "USER_INPUT_CODE_ALREADY_USED_ERROR" }
  >;
  consumeCode: (
    input:
      | {
          userInputCode: string;
          deviceId: string;
        }
      | {
          linkCode: string;
        }
  ) => Promise<
    | {
        status: "OK";
        loginAttemptId: string;
        createdNewUser: boolean;
        user: User;
      }
    | {
        status: "INCORRECT_USER_INPUT_CODE_ERROR";
        failedCodeInputs: number;
        maximumCodeInputAttempts: number;
      }
    | {
        status: "RESTART_FLOW_ERROR";
      }
  >;

  getUser: (
    input:
      | {
          email: string;
        }
      | {
          phoneNumber: string;
        }
      | { userId: string }
  ) => Promise<User | undefined>;

  updateUser: (input: {
    userId: string;
    userInfoUpdate: {
      email?: string | null;
      phoneNumber?: string | null;
    };
  }) => Promise<{
    status:
      | "OK"
      | "UNKNOWN_USER_ID_ERROR"
      | "EMAIL_ALREADY_EXISTS_ERROR"
      | "PHONE_NUMBER_ALREADY_EXISTS_ERROR";
  }>;

  revokeCodes: (
    input:
      | {
          email: string;
        }
      | {
          phoneNumber: string;
        }
  ) => Promise<{
    status: "OK";
  }>;

  revokeCode: (input: {
    codeId: string;
  }) => Promise<{
    status: "OK";
  }>;

  listCodes: (
    input:
      | {
          email: string;
        }
      | {
          phoneNumber: string;
        }
      | { deviceId: string }
      | { loginAttemptId: string }
  ) => Promise<{
    status: "OK";
    devices: Array<{
      loginAttemptId: string;

      failedCodeInputs: number;

      email?: string;
      phoneNumber?: string;

      codes: Array<{
        codeId: string;
        createdAt: string;
      }>;
    }>;
  }>;
};
```

**Comment by porcellus** [comment]
# APIInterface

```ts

type APIOptions = {
  recipeImplementation: PasswordlessRecipeInterface;
  config: TypeInput;
  recipeId: string;
  isInServerlessEnv: boolean;
  req: BaseRequest;
  res: BaseResponse;
};

export type PasswordlessAPIInterface = {
  createCodePOST?: (
    input:
      | { email: string }
      | { phoneNumber: string }
      | { deviceId: string; loginAttemptId: string },
    options: APIOptions
  ) => Promise<
    | {
        status: "OK";
        deviceId: string;
        loginAttemptId: string;
        flowType: "USER_INPUT_CODE" | "LINK" | "USER_INPUT_CODE_AND_LINK";
      }
    | { status: "GENERIC_ERROR"; message: string }
    | { status: "RESTART_FLOW_ERROR" }
  >;
  consumeCodePOST?: (
    input:
      | {
          userInputCode: string;
          deviceId: string;
          loginAttemptId: string;
        }
      | {
          linkCode: string;
          loginAttemptId: string;
        },
    options: APIOptions
  ) => Promise<
    | {
        status: "OK";
        createdNewUser: boolean;
        user: { id: string; email?: string; phoneNumber?: string };
      }
    | {
        status: "INCORRECT_USER_INPUT_CODE_ERROR";
        failedCodeInputs: number;
        maximumCodeInputAttempts: number;
      }
    | { status: "GENERIC_ERROR"; message: string }
    | { status: "RESTART_FLOW_ERROR" }
  >;
};
```

**Comment by porcellus** [comment]
# NormalisedTypeInput

```ts
export type NormalisedTypeInput = {
  flowType: "USER_INPUT_CODE" | "LINK" | "USER_INPUT_CODE_AND_LINK";
  contanctInfoType: "PHONE" | "EMAIL";

  // Override to use custom template/contact method
  createAndSendCodeMessageOrEmail: (
    // Where the message should be delivered.
    contactInfo:
      | {
          email: string;
        }
      | {
          phoneNumber: string;
        },
    code: {
      // This has to be entered on the starting device  to finish sign in/up
      userInputCode?: string;
      // Full url that the end-user can click to finish sign in/up
      url?: string;
    },
    // Unlikely, but someone could display this (or a derived thing) to identify the device
    loginAttemptId: string,
    // Access any information about the starting request.
    // This can be useful if devs want to include geographical or browser information in the message
    req: Request
  ) => Promise<void>;

  // Customize information in the URL.
  // By default: `${websiteDomain}/auth/verify`
  // `?rid=passwordless&loginAttemptId=${loginAttemptId}#${linkCode}` will be added after it.
  getCodeUrlDomainAndPath: (
    // A urlsafe code that should be embedded in the hash part of the url
    linkCode: string,
    // This is a necessary part of the
    loginAttemptId: string,
    contactInfo:
      | {
          email: string;
        }
      | {
          phoneNumber: string;
        },
    req: Request
  ) => Promise<string> | string;

  // Override this to override how user input codes are generated
  // By default (=undefined) it is done in the Core
  getCustomUserInputCode?: () => Promise<string> | string;

  override: {
    functions: (
      originalImplementation: PasswordlessRecipeInterface,
      builder: OverrideableBuilder<PasswordlessRecipeInterface>
    ) => PasswordlessRecipeInterface;
    apis: (
      originalImplementation: Required<PasswordlessAPIInterface>,
      builder: OverrideableBuilder<Required<PasswordlessAPIInterface>>
    ) => PasswordlessAPIInterface;
  };
};
```

**Comment by porcellus** [comment]
# TypeInput

```ts
export type TypeInput = {
  flowType: "USER_INPUT_CODE" | "LINK" | "USER_INPUT_CODE_AND_LINK";
  contanctInfoType: "PHONE" | "EMAIL";

  // Override to use custom template/contact method
  createAndSendCodeMessageOrEmail?: (
    // Where the message should be delivered.
    contactInfo:
      | {
          email: string;
        }
      | {
          phoneNumber: string;
        },
    code: {
      // This has to be entered on the starting device  to finish sign in/up
      userInputCode?: string;
      // Full url that the end-user can click to finish sign in/up
      url?: string;
    },
    // Unlikely, but someone could display this (or a derived thing) to identify the device
    loginAttemptId: string,
    // Access any information about the starting request.
    // This can be useful if devs want to include geographical or browser information in the message
    req: Request
  ) => Promise<void>;

  // Customize information in the URL.
  // By default: `${websiteDomain}/auth/verify`
  // `?rid=passwordless&loginAttemptId=${loginAttemptId}#${linkCode}` will be added after it.
  getCodeUrlDomainAndPath?: (
    // A urlsafe code that should be embedded in the hash part of the url
    linkCode: string,
    // This is a necessary part of the
    loginAttemptId: string,
    contactInfo:
      | {
          email: string;
        }
      | {
          phoneNumber: string;
        },
    req: Request
  ) => Promise<string> | string;

  // Override this to override how user input codes are generated
  // By default (=undefined) it is done in the Core
  getCustomUserInputCode?: () => Promise<string> | string;

  override?: {
    functions?: (
      originalImplementation: PasswordlessRecipeInterface,
      builder: OverrideableBuilder<PasswordlessRecipeInterface>
    ) => PasswordlessRecipeInterface;
    apis?: (
      originalImplementation: Required<PasswordlessAPIInterface>,
      builder: OverrideableBuilder<Required<PasswordlessAPIInterface>>
    ) => PasswordlessAPIInterface;
  };
};
```

**Comment by porcellus** [comment]
> Since you have made flowType non optional in TypeInput, I assume you want the user to pick one for sure. If so, I am OK with that

I'm OK with both, so if you prefer this one I'll keep it this way.

**Comment by porcellus** [comment]
>  We should also make these for thirdpartypasswordless recipe.

I'll add them after we nail these down (mostly at least). Also, I think I'll create a separate issue for the super recipe since it'll be a bit easier to read.

**Comment by rishabhpoddar** [comment]
# Feedback
- [ ] If someone wants to add pre sign up logic, they would need to:
   - In the `consumeCode`, call the `listCodes` function with the relevant input, fetch the email / phone. Then check if the user exists using `getUser` and if it does, it's for sign up. While this works, it's a little difficult to communicate. Is there any easier way?
- [ ] In `createCode`, if the input is `deviceId`, we should also provide `loginAttemptId` (as per my slack msg yesterday).
- [ ] In `createCode` we should also return a `GENERIC_ERROR` status
- [ ] In `consumeCode`, we should also provide a `loginAttemptId` and return a `GENERIC_ERROR` status (as per my slack msg yesterday)
- [ ] In `updateUser`, if someone passes both a new email and a number, and it returns `EMAIL_ALREADY_EXISTS_ERROR`, does that mean the number was updated successfully? If no, can we somehow make that more clear?

> I'm OK with both, so if you prefer this one I'll keep it this way.

Yes. Let's keep it this way

> I'll add them after we nail these down (mostly at least). Also, I think I'll create a separate issue for the super recipe since it'll be a bit easier to read.

Cool!

**Comment by porcellus** [comment]
>  If someone wants to add pre sign up logic, they would need to:

Well, consumeCode returns the email address, and if it was a new user so I'd just do it after consuming the code but before returning the session. I mean in a way this isn't pre-sign up since we already have the user in our DB, but also this avoids this check being true for two concurrent sign-in/ups. Filtering is best done before creating the code, but also possible here: just delete the user and throw.

>  In updateUser, if someone passes both a new email and a number, and it returns EMAIL_ALREADY_EXISTS_ERROR, does that mean the number was updated successfully? If no, can we somehow make that more clear?

No, it means the whole operation failed and didn't update the DB. We could make the error name even longer, but just adding an explanation would do as well I think. Besides, I feel like this should be the default everywhere: if we returned an error we should not have updated anything.

**Comment by rishabhpoddar** [comment]
- [ ] Should we consider changing `linkCode` to `magicLinkCode` and `linkClickedScreen` (in frontend) to `magicLinkClickedScreen` etc.. This would also involve changing the names in the CDI and FDI APIs. The reason I bring this up now is cause people in the team better understood the term `magicLinkClickedScreen` as opposed to `linkClickedScreen`. Plus in the docs we will be referring to it as magic links in places..

**Comment by porcellus** [comment]
> Should we consider changing `linkCode` to `magicLinkCode`...?

I'm not sure: it may be just missing context. I think `linkCode` is descriptive enough almost everywhere. E.g., if you are calling `PasswordlessRecipe.consumeCode` or looking at the results of `PasswordlessRecipe.createCode`. It could look weird in a few places of the config, though.

All in all:
- I don't think we should touch the API, but I think we could change it in a few places in the config.
- getCodeUrlDomainAndPath -> getMagicLinkDomainAndPath (also, I've removed `linkCode` and `loginAttemptId` parameters)
- linkClickedScreen -> magicLinkClickedScreen

**Comment by rishabhpoddar** [comment]
We should change getCodeUrlDomainAndPath to getLinkDomainAndPath. Others can stay the same.

-Rishabh Poddar

**Comment by rishabhpoddar** [comment]
@porcellus from the recipe interface, I removed putting in `loginAttemptId` when it's not needed, and also removed returning `GENERIC_ERROR` from those functions. 

I did this because in the recipe design I had written earlier, it said that the input and output to the recipe interface functions should be as minimal as possible. 

Even in the emailpassowrd recipe interface functions, we don't return a `GENERIC_ERROR` or a `FIELD_ERROR` from the recipe functions. Note that in the thirdparty recipe, we do return a `FIELD_ERROR` from `signinup` recipe function, but I think that that should not be there (but can't be bothered to introduce a breaking change for this).

I have made similar changes to the thirdpartypasswordless recipe function.

**Comment by rishabhpoddar** [comment]
- [ ] An optional context object needs to be passed in all the functions (recipe interface and api interface)
- [ ] All things that are "created" an an API interface function must also be returned - for example, a session, or a user etc.

**Comment by porcellus** [comment]
> All things that are "created" an an API interface function must also be returned - for example, a session, or a user etc

This breaks the 1 to 1 mapping of the API interface function to FDI (which isn't necessarily a problem).

**Comment by rishabhpoddar** [comment]
> This breaks the 1 to 1 mapping of the API interface function to FDI (which isn't necessarily a problem).

Not entirely, cause the API does return a new session as well. But sometimes, yea. And that's OK i guess.

**Comment by porcellus** [comment]
> Not entirely, cause the API does return a new session as well.

I was thinking of the third-party case where someone wanted to use the access token of the social login.

**Comment by rishabhpoddar** [comment]
> I was thinking of the third-party case where someone wanted to use the access token of the social login.

True. But that's OK. I guess the design principle should be that the input and output have to at least contain the input / output of the API

**Comment by rishabhpoddar** [comment]
@porcellus we should return the max token lifetime in `createCode` and `listCodes` functions so that the email / SMS can have info that the code is alive for ___ mins.

What do you think?

**Comment by porcellus** [comment]
We are adding more static config values into each request which isn't necessarily a problem, but we could think about setting up a kind of handshake endpoint for these. 
Also, if they save this into a DB, they either have to check/update them on each listing because the config value could change, or the two DBS could get out of sync. They would have to query devices periodically to ensure this happens (a super-long expiration set during testing, then lowered would leave expired devices in their DB).
I'd prefer if the recommended app backend cleanup logic were based on querying (they can record when the device was created, then the cleanup cron job tries querying anything over X mins old and cleans up). 
Maybe we could add a bulk checking endpoint? I'm not sure this is necessary, but

**Comment by rishabhpoddar** [comment]
- [ ] Is `codeLifetime` the same as what's in the core config? Or is this the timestamp of when that specific code will expire? If it feels weird to have this one static value, perhaps we can change it to `timeExpiry` which will be `timeCreated + lifetime of code from core's config`.
- [ ] We need to change `failedCodeInputs` to `failedCodeInputAttemptCount`
- [ ] Now that we have the concept of a `context` object, should we replace `req` object in `getLinkDomainAndPath`, `createAndSendCustomEmail` and `createAndSendCustomTextMessage` with the context object? If a user wants the request object in there, they can add it to the context and it would be available in those functions.

**Comment by makerboiAdi** [comment]
- `{ status: "RESTART_FLOW_ERROR" }` --> `{ status: "GENERAL_ERROR_RESTART_FLOW" }`
- loginAttemptId: string; --> rename to: perLoginId | anonymousId | preAuthId | split into two variables, one for SuperTokens and one for devs and name them accordingly.

**Comment by rishabhpoddar** [comment]
- [ ] We should change `createAndSendCustomTextMessage` to be like `createAndSendCustomTextMessage(input, userContext)` where `input will have all the things in the params now. Same goes for sending email.

**Comment by makerboiAdi** [comment]
- [ ] `{ status: "RESTART_FLOW_ERROR" }` --> `{ status: "GENERAL_ERROR_RESTART_FLOW" }`
- [ ] loginAttemptId: string; --> rename to: perLoginId | anonymousId | preAuthId | split into two variables, one for SuperTokens and one for devs and name them accordingly.
- [ ] `devices: Array<{` --> use square brackets instead
- [ ] APIOptions config should be TypeNormalizedInput
- [ ] In createCodePost: Why is deviceID and loginAttemptID required?
- [ ] flowType: "USER_INPUT_CODE" | "LINK" | "USER_INPUT_CODE_AND_LINK"; --> "LINK" to "MAGIC_LINK"
- [ ] Should "Input_Code" everywhere have some reference to OTP since thats what people call it in normal everyday conversation?
- [ ] ContactInfoType and FlowType can be made more obvious and similar structurally. 
contactInfoType -->  phoneOrEmail | contactMethod | transmitMethod | broadcastMethod |
flowtype --> codeType | smsOrLinkOrBoth | contactForm / contactCodeType | broadcastType / broadcaseCodeType  etc

- [ ] Possible suggestion:
revokeCodes --> revokeAllCodes
revokeCode --> revokeSingleCode
- [ ] Add `USER_INPUT_CODE_EXPIRED_ERROR` status to relevant functions in the frontend / backend + FDI and CDI

**Comment by porcellus** [comment]
@makerboiAdi 

> { status: "RESTART_FLOW_ERROR" } --> { status: "GENERAL_ERROR_RESTART_FLOW" }

All other statuses (besides "OK") end with "_ERROR". I named it like this for consistency, but if we are going to diverge from that, I'd prefer if it was just RESTART_FLOW.

> split into two variables, one for SuperTokens and one for devs and name them accordingly.

I'm not sure if I understand this. 
Besides that, I like `preAuthId` most out of those options, but `loginAttemptId` still feels more descriptive to me. This is intended to be used as a key for storing information about each login attempt during customization or query things about the login attempt from the core.

> devices: Array<{ --> use square brackets instead

I'll rename it if you prefer that, but it makes things less readable for me (I tend to use the "array-simple" option of [this eslint rule](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/array-type.md))

> In createCodePost: Why is deviceID and loginAttemptID required?

- `deviceId` is used for resending codes
- `loginAttemptId` is used can be used for customization while overriding the endpoint.

> Should "Input_Code" everywhere have some reference to OTP since thats what people call it in normal everyday conversation?

I haven't heard anyone refer to it as an OTP in everyday conversation, mostly just SMS code or sometimes verification or login code, but maybe that's just me. 
Anyway, both options are technically a kind of OTP. I know people generally mean what we call "user_input_code" by it, but while the current name is a bit cumbersome, it's also descriptive. If you prefer OTP, I'll go through and rename things.

> ContactInfoType and FlowType can be made more obvious and similar structurally.

I renamed `contactInfoType` to `contactMethod`, because that felt like a definite upgrade, but the `flowtype` alternatives not so much:
- We generally want to avoid broadcast in this sense, these are things that definitely shouldn't be broadcasted.
- `smsOrLinkOrBoth` is kinda weird, it sounds like it should've been multiple bool flags (which we could do, but decided against).
- `contactForm / contactCodeType` could be confused with `contactMethod`.
- `codeType` is an ok alternative, but `codeType: "MAGIC_LINK"` doesn't really work.
- I think the current one expresses that this is about which passwordless flow they want in their app.

> revokeCode --> revokeSingleCode

I only renamed the multiple, because I think it sets them apart enough.

**Comment by rishabhpoddar** [comment]
> Besides that, I like preAuthId most out of those options, but loginAttemptId still feels more descriptive to me. This is intended to be used as a key for storing information about each login attempt during customization or query things about the login attempt from the core.

- [ ] I think we should call it `preAuthSessionId`. Both Advait and I prefer this over everything else that has come before this.
- [ ] In `createAndSendCustomEmail` and `createAndSendCustomTextMessage` we should change `url` to `urlWithLinkCode`.

**Comment by rishabhpoddar** [comment]
https://github.com/supertokens/supertokens-core/issues/324#issuecomment-977553292

**Comment by rishabhpoddar** [comment]
Closing this issue since the types and skeleton for passwordless have been added to the node SDK. A few changes though:
- In `override.apis`, I had to remove `Required<APIInterface>` to just `APIInterface` since I was getting a type error when using the override builder.
