### ISSUE TITLE
supertokens docker image doesn't auto-start from detached mode when Docker is restarted

### ISSUE THREAD

**Issue by cerino-ligutom** [supertokens/supertokens-core#346]
## 🐛 Bug Report

When running [`supertokens/supertokens-postgresql:3.6`](https://hub.docker.com/layers/supertokens/supertokens-postgresql/3.6/images/sha256-e81d3f54acace90ced5785431d0d60ac5e0f65c6f7d091b75d341857b46d6cfb?context=explore) in a docker compose project in detached mode and Docker Desktop restarts, the supertokens container doesn't automatically start.

## Useful informations

OS: Windows 10 Pro 64-bit (10.0, Build 19043)
Docker: 4.2.0 (70708)
Docker Engine: 20.10.10
Docker Compose: 1.29.2

To reproduce:
1. Clone this [repo](https://github.com/cerino-ligutom/GraphQL-Starter)
2. Open a terminal then run the project in detached mode `docker-compose up -d`
3. Double check if the container is running `docker ps`
4. Restart Docker Desktop
5. Check again if the container is running `docker ps`
6. Every other container auto-started except for `supertokens` 

![image](https://user-images.githubusercontent.com/6721822/144716136-9e6e518c-bbc7-4408-913b-865082a1334d.png)

**Comment by bhumilsarvaiya** [comment]
Hey @cerino-ligutom, please add `restart: always` for supertokens also and try it out.

**Comment by rishabhpoddar** [comment]
Closing this issue since it seems to be an error in the docker-compose file config as opposed to an error in the supertokens' docker image.

**Comment by cerino-ligutom** [comment]
Oh, silly me. My bad. That fixed it. Missed adding this flag somehow 😅 Thank you @bhumilsarvaiya @rishabhpoddar !
