### ISSUE TITLE
Getting compatibility error between core (Managed Service), and NodeJS SDK.

### ISSUE THREAD

**Issue by Killian-Smith** [supertokens/supertokens-core#355]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

The core (Managed Service) is running v3.4, and I have a backend server (Express) running a version of supertokens-node v8.0.4. Even though it says they are compatiable on the website found here https://supertokens.io/docs/community/compatibility-table.

When I run it I get an error:

`Error: The running SuperTokens core version is not compatible with this NodeJS SDK. Please visit https://supertokens.io/docs/community/compatibility to find the right versions`

**What I have tried:**

Deleted the node_modules and reinstalled all packages

**Comment by Killian-Smith** [comment]
Chaning the version of supertokens-node to v7.3.1 seems to fix the problem, so possibly it could be listed wrong?

**Comment by rishabhpoddar** [comment]
@Killian-Smith there was a bug in listing the versions in the compatibility table. We have fixed that now. Please have a look again -> 7.3.1 is the version that you should be using :)

Thanks for pointing this out. Closing this issue now.
