### ISSUE TITLE
Provide documentation for Kubernetes deployment

### ISSUE THREAD

**Issue by devpikachu** [supertokens/supertokens-core#358]
## 🚀 Feature

Provide documentation on how to deploy in a Kubernetes envrionment, either through native K8s YAMLs or Helm.

## Implementation details

Hello!

I've recently stumbled across SuperTokens. I was immediately drawn in and want to use it, however, I was surprised to see no docs in regards to how to deploy the OSS self-hosted solution into a Kubernetes cluster. I saw that an attempt at creating a Helm chart was made a year ago (#146 ), but I don't think that got far. Regardless, having such a pointer in the official docs would go a long way, I believe.

Thank you!

**Comment by rishabhpoddar** [comment]
Thank you @devpikachu . We will work on this as and when we get time. Do feel free to make a PR for this if you like :)

**Comment by voidrot** [comment]
I have created a helm chart here for deploying supertokens-core, it supports either PostgreSQL or MySQL as the database.

https://github.com/voidstack-io/charts/tree/main/charts/supertokens

@rishabhpoddar the team is more than welcome to copy the chart into the repo or link to the above repo in the docs.

**Comment by rishabhpoddar** [comment]
Thank you so much @voidrot . We will have a look!

**Comment by rishabhpoddar** [comment]
We have added helm charts to our [PostgreSQL docker](https://github.com/supertokens/supertokens-docker-postgresql/tree/master/helm-chart) and [MySQL docker image](https://github.com/supertokens/supertokens-docker-mysql/tree/master/helm-chart) repos.

Thanks to @voidrot and @bhumilsarvaiya
