### ISSUE TITLE
Typo on Contribution page

### ISSUE THREAD

**Issue by Deepakktripathy** [supertokens/supertokens-core#369]
## 📚 Documentation
![Screenshot (112)_LI](https://user-images.githubusercontent.com/79755187/152936526-3fb3b1ce-25b6-4618-8eeb-bd6fca64b797.jpg)

Should be:
Go **through**...
Please open an issue https://github.com/supertokens/docs/issues instead.

**Comment by rishabhpoddar** [comment]
Fixed. Thank you
