### ISSUE TITLE
LifecycleException error while starting supertokens without docker

### ISSUE THREAD

**Issue by scherbatsky-jr** [supertokens/supertokens-core#370]
## 🐛 Bug Report
I am setting up supertokens core without docker for my NEST JS api on Ubuntu 20 LTS. I downloaded the supertoken-core from **[here](https://supertokens.com/use-oss)** . After the installing the core, I run the following command
`supertokens start`

The database and tables are created but runs into following error immediately.
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/catalina/LifecycleException
	at io.supertokens.Main.init(Main.java:206)
	at io.supertokens.Main.start(Main.java:106)
	at io.supertokens.Main.main(Main.java:86)
Caused by: java.lang.ClassNotFoundException: org.apache.catalina.LifecycleException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 3 more

```
## Useful informations
![Screenshot from 2022-02-11 13-47-18](https://user-images.githubusercontent.com/25346229/153556315-ff7495c5-6421-4d95-84d3-365879943f7d.png)

**Comment by rishabhpoddar** [comment]
hey @scherbatsky-jr 

I tried to setup supertokens on Ubuntu 20.04 with MySQL and it worked as expected.

First I installed MySQL:
```
sudo apt update
sudo apt install mysql-server
```

Then I created a user called `root` with password `root`:
```
sudo mysql
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';
```

Then I created a database called `supertokens`
```
create database supertokens;
```

Then I downloaded the zip from supertokens.com (MySQL version, Linux/x64). Unzipped it and installed supertokens
```
unzip ./supertokens.zip 
cd supertokens/
sudo ./install
```

Then I edited the supertokens config file to add the mysql user info:
```
nano /usr/lib/supertokens/config.yaml
```
- I set `mysql_user: "root"` and `mysql_password: "root"`

Then started supertokens:
```
supertokens start
```

The output I got was:
```
Loading storage layer.
Loading MySQL config.
Loading supertokens config.
Loading supertokens version.yaml file.
Completed config.yaml loading.
Setting up MySQL connection pool.
Starting task: RemoveOldSessions
Starting task: RemoveOldPasswordResetTokens
Starting task: RemoveOldEmailVerificationTokens
Starting task: DeleteExpiredPasswordlessDevices
Starting task: Telemetry
Starting task: DeleteExpiredAccessTokenSigningKeys
Started SuperTokens on localhost:3567 with PID: 3629
```

Furthermore, I confirmed that the database had some info in the `key_value` table + calling the `/hello` API resulted in a Hello:
```
> curl localhost:3567/hello
Hello
```

Can you shed some light on how I can replicate this issue please?

**Comment by scherbatsky-jr** [comment]
I redid the whole process from the start. Its working now. Thanks.
