### ISSUE TITLE
Define DB schema and APIs for UserRoles

### ISSUE THREAD

**Issue by jscyo** [supertokens/supertokens-core#382]
## 🚀 Feature

Define the DB schema and APIs for user roles and permissions

**NOTE :  The delete user API should also call the remove user roles API**
### DB schema
-----------
#### MySQL
```sql
CREATE TABLE IF NOT EXISTS roles (
  role VARCHAR(255) NOT NULL,
  PRIMARY KEY (role)  
);

CREATE TABLE IF NOT EXISTS role_permissions (
  role VARCHAR(255) NOT NULL,
  permission VARCHAR(255) NOT NULL,
  PRIMARY KEY (role, permission),
  FOREIGN KEY (role) REFERENCES roles(role) ON DELETE CASCADE
);

CREATE INDEX role_permissions_permission_index ON role_permissions(permission);

CREATE TABLE IF NOT EXISTS user_roles (
  user_id VARCHAR(128) NOT NULL,
  role VARCHAR(255) NOT NULL,
  PRIMARY KEY (user_id, role),
  FOREIGN KEY (role)  REFERENCES roles (role) ON DELETE CASCADE
);

CREATE INDEX user_roles_role_index ON user_roles(role);
```

#### PSQL
```sql
CREATE TABLE IF NOT EXISTS roles (
  role VARCHAR(255) NOT NULL,
  CONSTRAINT roles_pkey PRIMARY KEY (role)  
);

CREATE TABLE IF NOT EXISTS role_permissions (
  role VARCHAR(255) NOT NULL,
  permission VARCHAR(255) NOT NULL,
  CONSTRAINT role_permissions_pkey PRIMARY KEY (role, permission),
  CONSTRAINT role_permissions_role_fkey FOREIGN KEY (role) REFERENCES roles(role) ON DELETE CASCADE
);

CREATE INDEX role_permissions_permission_index ON role_permissions(permission);

CREATE TABLE IF NOT EXISTS user_roles (
  user_id VARCHAR(128) NOT NULL,
  role VARCHAR(255) NOT NULL,
  CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role),
  CONSTRAINT user_roles_role_fkey FOREIGN KEY (role)  REFERENCES roles (role) ON DELETE CASCADE
);

CREATE INDEX user_roles_role_index ON user_roles(role);
```
-------

### Core API spec
![user_roles_spec](https://user-images.githubusercontent.com/6310783/160826892-7e6ea95d-a86f-4d8a-9c49-d7d73abed497.jpeg)

----------

### Core APIs Psuedo code
-----------

- [x]  PUT     /recipe/user/role: https://app.code2flow.com/oyBIcaFXIf5x
- [x]  POST  /recipe/user/role/remove: https://app.code2flow.com/HUtwAGGHsJpL
- [x] GET    /recipe/user/roles: https://app.code2flow.com/jKKkoUebyxwN
- [x] GET     /recipe/role/users: https://app.code2flow.com/Y29CMz2T9ECw
- [x] PUT     /recipe/role: https://app.code2flow.com/MqlnBFW8t24n
- [x]  GET   /recipe/role/permissions: https://app.code2flow.com/a326jJTajsE6
- [x]  POST  /recipe/role/permissions/remove: https://app.code2flow.com/a08VVz5BZOyC
- [x] GET  /recipe/permission/roles: https://app.code2flow.com/vJMgpSsmpURB
- [x] POST /recipe/role/remove: https://app.code2flow.com/PMRh9ehvJ9y9
- [x] GET /recipe/roles: https://app.code2flow.com/HPxvxOUDqQT8
-----------------

**Comment by rishabhpoddar** [comment]
# Feedback:
- [ ] PUT /recipe/user/role/metadata -> redo 
- [ ] GET /recipe/user/role/metadata -> needs to be optimised
- [ ] POST /recipe/user/role/metada/remove -> optimised
- [ ] GET /recipe/user/role -> redo

**Comment by jscyo** [comment]
- For /recipe/user/role simplify it
- /recipe/user/roles/remove if you cant find docs which talk about consistency then use a transaction with a for loop
- PUT /recipe/user/role/metadata:  check that if you need to check if update returns the number of rows it updates, other wise its fine

**Comment by jscyo** [comment]
## Feedback
- changer permissions to varchar(), 
- check what length to use for this and roleand role.
- make permissions part of primary key for role_permissions
- create an index on role_permissions with role,permissions

**Comment by jscyo** [comment]
-  [ ] POST /recipe/role/permissions/remove: do permissions sanitization

**Comment by rishabhpoddar** [comment]
Looks good.

**Comment by jscyo** [comment]
## Revise API's based on the discussion:

### Problem
- In the current implementation of the APIs, APIs which do things like adding(or removing) permission to roles or roles to users only relay information on whether the action was successful but don't give additional context information. 
- For example:
  - The add role to user API allows you to associate a user with a role. The first case is where a user doesn't have a role and we call this API. This will result in the user getting the role and the API responds with status: "OK". The second case is if the user already has the role and we call the API, it will also respond with status: "OK". The problem is that we don't know if the user already had the role from the response of the API.

### Solution:
Revise the APIs such that APIs which handle UserRole mapping and Role permission mapping (setting and removing) should also return a flag that gives this context information.


- PUT /recipe/user/role:
  - userId, role     =>          { status: "OK", newUserRoleMapping: boolean } |  { status: "UNKNOWN_ROLE_ERROR"  } 
- POST /recipe/user/role/remove:
  - userId, role    =>            {status: "OK", didUserHaveRole: boolean }  | {status: "UNKNOWN_ROLE_ERROR" }
-

**Comment by jscyo** [comment]
## API Spec:
### PUT /recipe/user/role:
 - userId, role => { status: "OK", didUserAlreadyHaveRole: boolean } | { status: "UNKNOWN_ROLE_ERROR" }
 
### POST /recipe/user/role/remove:
 - userId, role => {status: "OK", didUserHaveRole: boolean } | {status: "UNKNOWN_ROLE_ERROR" }
 
### GET /recipe/user/roles:
 - userId => {status: "OK", roles: str[ ] }
 
### GET /recipe/role/users:
 - role => {status: "OK", users: str[ ] } | {status: "UNKNOWN_ROLE_ERROR" }

### PUT /recipe/role:
- role, permissions?: str[ ] => { status: "OK", createdNewRole: boolean }

### GET /recipe/role/permissions
- role => { status: "OK", permissions: str[ ]}  | {status: "UNKNOWN_ROLE_ERROR" }

### POST /recipe/role/permissions/remove:
- role, permissions?: str[ ] => { status: "OK"} | {status: "UNKNOWN_ROLE_ERROR" }

### GET /recipe/permission/roles:
- permission => { status: "OK", roles: str[]}

### POST /recipe/role/remove
- role => { status: OK, didRoleExist: boolean }

### GET /recipe/roles: 
- => { status: "OK", roles: str[ ] }
