### ISSUE TITLE
Vue

### ISSUE THREAD

**Issue by pietru2004** [supertokens/supertokens-core#404]
## 🚀 Feature

It would be nice to see Vue frontend implementation of supertokens.

I tried setting it for testing and it just doesn't wana to work - I guess I did something wrong...

**Comment by rishabhpoddar** [comment]
hey @pietru2004 what issue did you face?

**Comment by pietru2004** [comment]
tries using form to post data to Backend but it always tells it is missing formFields. From what I looked up it takes json, but I not sure how to send it in correct format. I mean making form send json.

**Comment by rishabhpoddar** [comment]
I see. It's not possible to make a form send JSON. You need to use axios or fetch to send the json body. And it should work then.

**Comment by pietru2004** [comment]
ok, thanks I gona try it. :)

**Comment by pietru2004** [comment]
I am new to making app in js so do I only need to add
import axios from "axios";
import SuperTokens from 'supertokens-website'; // I already have this line...
SuperTokens.addAxiosInterceptors(axios);

**Comment by rishabhpoddar** [comment]
Yea. And you need to call the supertokens.init function on app load.

**Comment by pietru2004** [comment]
Got it working I think...
