### ISSUE TITLE
Where do you store the session?

### ISSUE THREAD

**Issue by masterbater** [supertokens/supertokens-core#405]
Where do you guys store the sessions, is it in memory, or the database? 

If its in the memory, is there any way to add redis support for nodejs cluster.

**Comment by rishabhpoddar** [comment]
A session comprises of two tokens:
- Access token
- Refresh token

The access token is a stateless token (similar to a JWT). It is stored as a cookie on the client side. It's sent for all the API requests and verification of them doesn't require any IO. Therefore it's verification is < 1MS

The refresh token is an opaque token that is stored in the db. It's used to generate a new access & refresh token when the older access token has expired (therefore they are not frequently used).

It would make sense to use a cache like redis only for maintaining a blacklist for the access token - in case you want them to be revoked immediately. This can be done independently to our `verifySession` middleware. The idea here is to have your own middleware which runs after SuperTokens' `verifySession` middleware succeeds. In your middleware, you can get the userId / session handle of the session and check your redis cache to see if the user / session has been blacklisted.

Closing this for now. But feel free to repoen to ask more questions.
