### ISSUE TITLE
phoneNumber is stored into email field in PasswordLess strategy

### ISSUE THREAD

**Issue by gstvoantonio** [supertokens/supertokens-core#416]
## 🐛 Bug Report
I'm using the `PasswordLess` strategy with only OTP and phoneNumber.

When I completed the flow, I saw that the `phoneNumber` is stored in the `email` field in the `consume` endpoint.

I exported a CSV of my users to confirm it, and it it's true, is stored in the email field.

**Comment by rishabhpoddar** [comment]
This has been fixed in python SDK version >= 0.6.2 which has now been released.
