### ISSUE TITLE
OAuth with apple: save scope-specific data

### ISSUE THREAD

**Issue by manu-urba** [supertokens/supertokens-core#451]
## 🚀 Feature

It would be **very** useful if SuperTokens (core) would store scope information requested on database in order to expose them later via APIs and SDKs.
That's because Apple returns those information once. It is impossible to get them a second time.
As you can see, in the Apple callback (using supertokens) I get this payload https://prnt.sc/1g73RdEZcCEH
The user, however, won't be included again unless I **revoke** the oauth for that specific apple service.
So I am able to get this data only the first time.

Apple refused our app to be published to the store because of an issue related to this: they want you to not ask for user information that you could already retrieve from login with Apple.
That's not a big issue because I'll now save the user data in some sort of user metadata somehow, but it would be great for you to include anything included in that response, maybe into Database.thirdparty_users.

**Comment by rishabhpoddar** [comment]
(Assuming that you are using thirdpartyemailpassword with nodejs)

The info is returned as part of the call to `thirdPartySignInUp` API function. This means that you can override that API and read the user object like this:

```ts
ThirdPartyEmailPassword.init({
    override: {
        apis: (oI) => {
            return {
                ...oI,
                thirdPartySignInUpPOST: async function (input) {
                    if (oI.thirdPartySignInUpPOST === undefined) {
                        throw new Error("Should never come here")
                    }
                    let resp = await oI.thirdPartySignInUpPOST(input);
                    if (resp.status === "OK") {
                        let user = resp.user;
                        let email = user.email;
                        let userId = user.id;
                        if (user.thirdParty?.id === "apple") {
                            let appUserId = user.thirdParty?.userId
                        }
                    }
                    return resp;
                }
            }
        }
    }
})
```

**Comment by manu-urba** [comment]
@rishabhpoddar I've been able to build a workaround of this in the following way:

```ts
thirdPartySignInUp: async (input: {
  thirdPartyId: string;
  thirdPartyUserId: string;
  email: { id: string; isVerified: boolean };
  userContext: any;
}): Promise<
  | {
      status: 'OK';
      createdNewUser: boolean;
      user: ThirdPartyPasswordless.User;
    }
  | { status: 'FIELD_ERROR'; error: string }
> => {
  const response =
    await originalImplementation.thirdPartySignInUp(input);
  if (response.status === 'OK') {
    if (response.createdNewUser) {
      await this.authUserService.create({
        stId: response.user.id,
      });
    }
  }
  return response;
},
```
👆 Overriding `thirdPartySignInUp`, I create an "AuthUser" instance in my database, which will store later the apple scope data.

```ts
thirdPartySignInUpPOST: async function (input: {
  provider: TypeProvider;
  code: string;
  redirectURI: string;
  authCodeResponse?: any;
  clientId?: string;
  options: ThirdPartyAPIOptions;
  userContext: any;
}) {
  try {
    const response =
      await originalImplementation.thirdPartySignInUpPOST(
        input,
      );
    if (response.status === 'OK') {
      const authUserId = (
        response.session.getAccessTokenPayload() as AccessTokenPayload
      ).authUser.id;
      const authUser = await authUserServiceP.findById(
        authUserId,
        void 0,
        false,
      );
      if (response.createdNewUser || !authUser.oAuthData) {
        let appleData = null;
        try {
          appleData = JSON.parse(
            decodeURIComponent(
              (await input.options.req.getJSONBody()).userData,
            ),
          );
        } catch (e) {}

        await authUserServiceP.update({
          id: (
            response.session.getAccessTokenPayload() as AccessTokenPayload
          ).authUser.id,
          oAuthData: {
            strategy: input.provider.id,
            appleData,
          },
        });
      }
    }
    return response;
  } catch (e) {
    //console.warn(e.response.data);
    //throw e;
  }
},
```
👆 Overriding this API, I am able to access the apple data I only have access the first time. Which I am passing as a body parameter in the signinup request.

**Comment by manu-urba** [comment]
Exactly. Apple's scope data is known for [being returned only the first time](https://developer.apple.com/forums/thread/123642).
That's why I absolutely need to save that in the database in the time of user creation.

Also, from the official Apple documentation:
> Utilize the user identifier instead of an email address to identify the user. If you request the user’s full name, Sign in with Apple collects the information to pass along to your app. The name defaults to the user’s name from their Apple ID, but the user can change their name. The modified name is only shared with your app and not with Apple, and hence isn’t included in the ID token.

https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/authenticating_users_with_sign_in_with_apple

**Comment by manu-urba** [comment]
`(await input.options.req.getJSONBody()).userData` is being populated manually, overriding signinup API on frontend level.
Even there, I get that user data data only once from apple callback.

**Comment by rishabhpoddar** [comment]
So the id_token would contain the full name as well right?

**Comment by manu-urba** [comment]
You mean the first time? No, you can't get the full name even from the first time retrieved user_id.

**Comment by rishabhpoddar** [comment]
So how do you get userData on the frontend?
