### ISSUE TITLE
Supertokens with Postgraphile

### ISSUE THREAD

**Issue by 1x-eng** [supertokens/supertokens-core#460]
## 🚀 Feature

Given this backend setup for graphql with supertokens - https://supertokens.com/docs/emailpassword/graphql-integration/backend-setup, How can you best integrate with postgraphile (ref: https://www.graphile.org/postgraphile/usage-library/) 

An example to work with both JWT tokens & Session based auth (using cookies) in the context of postgraphile + supertokens will be very helpful. Thanks

**Comment by rishabhpoddar** [comment]
Hey @1x-eng - I had a look at postgraphile, however their docs are not very easy to follow and so it's not very clear what they actually do. 

Would you mind sharing some resources that explain postgraphile well? Thanks

**Comment by 1x-eng** [comment]
Hey @rishabhpoddar surprising to learn that postgraphile is foriegn! 

Anyways, I see supertokens support Hasura, Postgraphile is simply FOSS of Hasura in the context of postgres. 

And, this - https://www.graphile.org/postgraphile should be sufficiently brief to summarize what it does?

**Comment by rishabhpoddar** [comment]
Thanks!

So from what I see, you will need to use their JWT auth feature: https://www.graphile.org/postgraphile/security/

Essentially, setup SuperTokens to have JWT enabled in the session. You can extract the JWT from the SuperTokens' session from the frontend and backend. Either way, you then send the JWT to Postgraphile which can then be verified by them.

For verification purpose, it seems that they do not accept a JWKs URL. Therefore, you will have to give them the public key to verify the JWT. You can get the public key from SuperTokens by following these steps: https://supertokens.com/docs/session/common-customizations/sessions/with-jwt/get-public-key

Hope this helps! For now, I am closing this issue, but feel free to reopen it if you have more questions.
