### ISSUE TITLE
UserId Mapping Feature

### ISSUE THREAD

**Issue by jscyo** [supertokens/supertokens-core#463]
## Related Issues
https://github.com/supertokens/supertokens-node/issues/198

## Description
Adds userId mapping feature where a user does not have to override all the functions and can simply override the mapper and get done with this.

## Recipe ID
`useridmapping`

## DB schema

PostgreSQL

```sql
CREATE TABLE IF NOT EXISTS userid_mapping (
    supertokens_user_id CHAR(36) NOT NULL UNIQUE,
    external_user_id VARCHAR(128) NOT NULL UNIQUE,
    external_user_id_info TEXT,
    CONSTRAINT userid_mapping_pkey PRIMARY KEY(supertokens_user_id, external_user_id),
    CONSTRAINT userid_mapping_user_id_fkey FOREIGN KEY (supertokens_user_id) REFERENCES all_auth_recipe_users (user_id) ON DELETE CASCADE
);
```

MySQL

```sql
CREATE TABLE IF NOT EXISTS userid_mapping (
    supertokens_user_id CHAR(36) NOT NULL UNIQUE,
    external_user_id VARCHAR(128) NOT NULL UNIQUE,
    external_user_id_info TEXT,
    PRIMARY KEY (supertokens_user_id, external_user_id),
    FOREIGN KEY (supertokens_user_id) REFERENCES all_auth_recipe_users (user_id) ON DELETE CASCADE
);
```

### POST  `/recipe/userid/map`
codeflow: https://app.code2flow.com/iWVMxbYowTTk

**Body**
```ts
{
   superTokensUserId: string,
   externalUserId: string,
   externalUserIdInfo?: string
}
```

**Response**

```ts
{
  status: "OK" | "UNKNOWN_SUPERTOKENS_USER_ID_ERROR"
} |  {
 status: "USER_ID_MAPPING_ALREADY_EXISTS_ERROR",
 doesSuperTokensUserIdExist: boolean,
 doesExternalUserIdExist: boolean
}
```

### POST `/recipe/userid/map/remove`
codeflow: https://app.code2flow.com/PgmY2PcDEXnS

**Body**
```ts
{
 userId: string,
 userIdType?: "SUPERTOKENS" | "EXTERNAL" | "ANY"
}
```

**Response**
```ts
{
 status: "OK",
 didMappingExist: boolean
}

```

### GET `/recipe/userid/map`
codeflow: https://app.code2flow.com/rtJH1uEeHnHZ

**Query params**

```ts
{
 userId: string,
 userIdType?: "SUPERTOKENS" | "EXTERNAL" | "ANY"
}
```

**Response**
```ts
{
 status: "OK",
 superTokensUserId: string,
 externalUserId: string,
 externalUserIdInfo: string | undefined
} | {
 status: "UNKNOWN_MAPPING_ERROR"
}

```

### PUT `/recipe/userid/external-user-id-info`
codeFlow: https://app.code2flow.com/5x0OMcSOduof

**Body**
```ts
{
 userId: string,
 userIdType?: "SUPERTOKENS" | "EXTERNAL" | "ANY",
 externalUserIdInfo: string | null
}
```

**Response**
```ts
{
  status: "OK"  | "UNKNOWN_MAPPING_ERROR"
} 

```

## Remaining TODO's:
- [x] check whether it's better for the `userid_mapping` table to  have both `supertokens_user_id` and `external_user_id`as unique or `external_user_id` as unique and `supertokens_user_id` as the primary key
- [x] make superTokensUserId a foreign key on allAuthUsers userid
- [x] make sanitization more specific specify empty strings not allowed etc...
- [x] make supertokensUserId and externalUserId composite keys and check how specific the duplicate key exceptions are
- [x] create new API to update externalUserId info, should take userId, userIdtype and externalUserIdInfo
- [x] where we are doing any(apis take userIdType), for the query in that condition we want to check if its a supertokens userID, update row with supertokens userId check. Otherwise update with external userId
- [x] For the GET API we will use the SELECT query with the OR condition and then filter out only the row with the supertokensUserId = userId result. For the UPDATE and DELETE queries we will have a function that checks if it is a supertokens userId.

**Comment by rishabhpoddar** [comment]
Reopening since we need to make changes to all the APIs to resolve based on the map as well - in the core, and not in the backend SDK side.
