### ISSUE TITLE
Unexpected 500 error in email verify API

### ISSUE THREAD

**Issue by Qdea** [supertokens/supertokens-core#464]
Bug is that when i signout from normal mode, go to incognito and try to sign in with the same credentials, go to endpoint of email verify or try to send a code with yours default email delivery for passwordless login by phoneNumber i see exceptions on 1, 2 and 3 photo respectively 
![image](https://user-images.githubusercontent.com/58660439/177752935-2b957b43-ce07-4e0d-811a-ee2d7a345446.png)
![image](https://user-images.githubusercontent.com/58660439/177752991-29d322ff-7af1-41e1-9d84-394c91c476f8.png)
![image](https://user-images.githubusercontent.com/58660439/177753031-ee300885-5e8f-4b25-81a0-f46437705266.png)
I use version postgresql 13 with postgis image. When i run it locally - everything works fine, but when i send requests from dev.domain.com and another from test.domain.com to one instance of supertokens container running by registry.supertokens.io/supertokens/supertokens-postgresql image it goes throwing these eroors, maybe this information can help

**Comment by rishabhpoddar** [comment]
> default email delivery for passwordless login by phoneNumber

Phone number does not use email delivery. Can I see the backend SDK config?

Can you please give the full stack trace in text form? The above seems to be an incomplete stack trace.

**Comment by rishabhpoddar** [comment]
Also which API returns a 500 error? The APi from the core or the API from the backend SDK (when called from the frontend)?

**Comment by Qdea** [comment]
> > default email delivery for passwordless login by phoneNumber
> 
> Phone number does not use email delivery. Can I see the backend SDK config?
> 
> Can you please give the full stack trace in text form? The above seems to be an incomplete stack trace.

sms delivery, sorry misprint

**Comment by Qdea** [comment]
> Also which API returns a 500 error? The APi from the core or the API from the backend SDK (when called from the frontend)?

API from core 
![image](https://user-images.githubusercontent.com/58660439/177755141-c597b2bd-4efc-4bd9-9b24-ef886b6223e7.png)

**Comment by rishabhpoddar** [comment]
> and another eroors with the same text but different path

Which APi would that be?

**Comment by rishabhpoddar** [comment]
The issue seemed to be fixed, and we can't replicate it on our end. So closing it. But please feel free reopen in case it comes back
