### ISSUE TITLE
SOLVED: jwt issued in future Hasura and Supertokens

### ISSUE THREAD

**Issue by RobSchilderr** [supertokens/supertokens-core#467]
## 📚 Documentation

Hey guys, I was getting the error: `jwt issued in future`. Now I have recently moved to another timezone, so that might be it. It only happens locally on my Hasura instance. 

Solution:

adding `allowed_skew` to the JWT issuer fixes it.

such as this in my `docker-compose.yml` for Hasura:

`      HASURA_GRAPHQL_JWT_SECRET: '{"jwk_url":"JWT_ISSUER_URL/api/auth/jwt/jwks.json", "allowed_skew": 86400}'
`

[Link](https://github.com/hasura/graphql-engine/issues/2109) to similar issue by Hasura.

**Comment by rishabhpoddar** [comment]
Thanks for the solution @RobSchilderr

**Comment by arslanakhtar61** [comment]
Amazing. Thanks for the solution
