### ISSUE TITLE
Session with JWT always defaults to 1hr in-spite of adding the env variable ACCESS_TOKEN_VALIDITY

### ISSUE THREAD

**Issue by doraig** [supertokens/supertokens-core#482]
## 🐛 Bug Report

Session with JWT always defaults to 1hr  in-spite of adding the env variable ACCESS_TOKEN_VALIDITY=500.

## Useful Information
I was testing out the session with jwt enabled and noticed that the jwt expiry always defaults to 1hr in-spite of adding the env variable ACCESS_TOKEN_VALIDITY=60 when running super token core docker image.

Below is a example JWT with the invalid expiry date
```
{
  "sub": "a4572611-b5e6-45c7-914e-b6c8f8e0bd44",
  "https://hasura.io/jwt/claims": {
    "x-hasura-user-id": "5617",
    "x-hasura-session-id": "d48a0f3c-be0a-49eb-8d80-662432a66753"
  },
  "iss": "http://localhost:3100/api",
  "exp": 1658644557, //This is 1 hr which is not right based access token expiry time.
  "iat": 1658640927
}
```
and the Access token has the right expiry date 
```
{
  "sessionHandle": "d48a0f3c-be0a-49eb-8d80-662432a66753",
  "userId": "a4572611-b5e6-45c7-914e-b6c8f8e0bd44",
  "refreshTokenHash1": "1e779393c3de296fdcbba172c7c1bd94108c9e0e44b3ab8121705c5885891e86",
   
    "jwt": <Removed  for readability purpose>
    "_jwtPName": "jwt"
  },
  "expiryTime": 1658640986879, //This is like 1 min expiry which is correct based on the env config
  "timeCreated": 1658640928024,
  "lmrt": 1658640928014
}
```

**Comment by rishabhpoddar** [comment]
Which backend SDK are you using?

**Comment by doraig** [comment]
> Which backend SDK are you using?

Nodejs

**Comment by doraig** [comment]
Apologies, i jumped the gun, the issue was with my config and the backend super token core instance i was connected too.
This is not an issue. Re verified it works fine.

**Comment by doraig** [comment]
Apologies, i jumped the gun, the issue was with my config and the backend super token core instance i was connected too.
This is not an issue. Re verified it works fine.

**Comment by renyijiu** [comment]
@doraig I also encountered the same problem, accesstoken has a short expiration time, but jwt keeps an hour expiration time, may I ask what configuration you modified?

**Comment by rishabhpoddar** [comment]
@renyijiu im not too sure if this will solve your issue, but try restarting the backend golang server and the core, and creating a new session - then inspect the JWT's lifetime. I am reopening this issue in favour of the one you created.

**Comment by renyijiu** [comment]
> @renyijiu im not too sure if this will solve your issue, but try restarting the backend golang server and the core, and creating a new session - then inspect the JWT's lifetime. I am reopening this issue in favour of the one you created.

I found the problem, after changing the configuration, just restart the core server, the cookie immediately took effect, the jwt expiration time will not change, after restarting the back-end services can be.

**If others are experiencing the same problem, they need to restart both core and backend**
