### ISSUE TITLE
jwt's expiration time setting is inconsistent with the cookie's accessToken expiration time

### ISSUE THREAD

**Issue by renyijiu** [supertokens/supertokens-core#488]
## 🐛 Bug Report

jwt's expiration time setting is inconsistent with the cookie's accessToken expiration time. jwt has an expiration time of one hour, but accessToken sets an expiration time of 5 minutes.

## Useful informations

![image](https://user-images.githubusercontent.com/8318266/181904894-c1d3be79-17d5-4823-9930-e0733a7d515e.png)

### 1. cookie show accessToken sets an expiration time of 5 minutes.

![image](https://user-images.githubusercontent.com/8318266/181904957-0a337fc7-ef91-4137-a26a-ee27baf1274e.png)

### 2. Get session info by cookie, where the jwt expiration time is shown as one hour later.

![image](https://user-images.githubusercontent.com/8318266/181905056-eb0d8d53-20cf-4f6f-943f-e987bacffcd7.png)

### 3. The core server configuration file shows `access_token_validity: 300`

core server deployment via helm, using golang sdk

**Comment by rishabhpoddar** [comment]
Duplicate - closing in favour of https://github.com/supertokens/supertokens-core/issues/482
