### ISSUE TITLE
Support request auth via methods other than native fetch or axios library

### ISSUE THREAD

**Issue by makeitcount** [supertokens/supertokens-core#493]
## 🚀 Feature

There are multiple reasons to use other http clients than axios or fetch. Or even when using fetch, changing the way it works.
So it will be great if the developer can have

1. Give finer control to developer to customize http client interceptor behavior
2. Support for other http clients e.g. XMLHTTPClient, Angular's httpClient

**Comment by makeitcount** [comment]
Some more context to the issue - https://github.com/supertokens/docs/issues/429#issuecomment-1214956890

**Comment by rishabhpoddar** [comment]
Closing this issue in favour of https://github.com/supertokens/supertokens-website/issues/154
