### ISSUE TITLE
Add ability to disable DEBUG level logs or select preferred log level

### ISSUE THREAD

**Issue by vyobukhov** [supertokens/supertokens-core#494]
## 🚀 Feature

Right now supertokens containers produce a lot of junk logs like notifications of `/hello` api health check and etc. Even not loaded system produces more than 200 messages every minute that have zero value in production env.

## Implementation details

Please add the ability to disable DEBUG level logs or, better, to set preferred log level via env variable so we can only see `warn` and `error` logs in production, maybe `info` in dev/staging and debug in development.

Thank you

**Comment by rishabhpoddar** [comment]
Thanks for the issue. At the moment, we have:
L1) DEBUG
L2) INFO
L3) WARN
L4) ERROR

We can have a config which sets the level of the logging. So if WARN is  set, we will logout warn + error logs. If INFO is set, we will print out INFO + WARN + ERROR.

Finally, we can have a silent mode which will print out nothing.

**Comment by rishabhpoddar** [comment]
This feature has been released now in version >= `3.16`. You can set a config value in the config.yaml file called `log_level` whose values are:
- DEBUG
- INFO
- WARN
- ERROR
- NONE

Setting it to `WARN` means that it will print out `WARN` and `ERROR` logs. Default is `INFO`
