### ISSUE TITLE
CONTRIBUTING.md mentions the supertokens-root repo to be cloned for core changes

### ISSUE THREAD

**Issue by itsmenikhill** [supertokens/supertokens-core#498]
## 📚 Documentation

Changes in the CONTRIBUTING.md file:
1. For forking the core repo, it advises to clone the supertokens-root repo. Is it supposed to be supertokens-core repo?
2.  It mentions the modules.txt file which is not in the supertokens-core repo.

**Comment by rishabhpoddar** [comment]
The supertokens-root repo is used to setup the dev env for the core with the db plugins. So you need to clone the supertokens-root repo and inside that, clone your forked supertokens-core repo.

**Comment by rishabhpoddar** [comment]
Closing this since it's not really an issue. But feel free to reopen
