### ISSUE TITLE
Docker versioning

### ISSUE THREAD

**Issue by bert2002** [supertokens/supertokens-core#505]
## 🚀 Feature

The documentation is pointing only for the `latest` tag of the docker container and I tried to find (compare release tags in Github with container tag) proper container tags, but could not find them.

## Implementation details

Release docker tags with the same version as releases and make them publicly browsable. 
This allows for proper releases and users can be sure to always use the same docker container and not get an unwanted feature upgrade when pulling master.

Thanks,
bert

**Comment by VivM1** [comment]
Hey, I am new to docker and all. This seems good to start from. Can I Start from this....?

**Comment by rishabhpoddar** [comment]
The docs now point to the latest released tag version. This should solve the problem of automatically getting the latest version across docker image updates.
