### ISSUE TITLE
Can we auto add the refresh API for all the supported drivers?

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#51]
This information will also be used to determine how we can add a proxy function to the driver to help the sign in / up form communicate with the core

- [x] NodeJS
- [x] Flask
- [x] Javalin
- [x] Golang
- [x] FastAPI
- [x] Laravel

**Comment by rishabhpoddar** [comment]
For NodeJS, we can add an API by adding a middleware via `app.use()`

**Comment by rishabhpoddar** [comment]
@bhumilsarvaiya , can you please advise on Flask + Laravel (since you made those SDKs)

@NkxxkN , can you please advice on Javalin & FastAPI

@jscyo, can you please advice on Golang (mux + http + gin)

**Comment by rishabhpoddar** [comment]
@bhumilsarvaiya this is a test notif

**Comment by NkxxkN** [comment]
# Javalin

> For NodeJS, we can add an API by adding a middleware via app.use()

It would essentially work the same way with javalin (See [before-handlers docs](https://javalin.io/documentation#before-handlers)). 

Though it would require to pass the app to SuperTokens constructor (for both node and javalin).

**Comment by rishabhpoddar** [comment]
@NkxxkN thanks. For node, we can add a middleware into `app.use()` which would do the refreshing. This is already being done now. So we don't need to add pass the app to SuperTokens since we do `app.use(supertokens.ini(...))`. Here, the `init` function returns a middleware.

I guess we can do the same thing in Javalin?
```
supertokenBeforeHandler = supertokens.init(...);
app.before(supertokenBeforeHandler);
```

**Comment by jscyo** [comment]
### Gorilla mux
For gorilla mux, the middleware is executed in the [order of which it is added](https://github.com/gorilla/mux#middleware), when defining the router we could add the middleware before handling the routes
   ```
   r := mux.NewRouter()
   r.Use(refreshMiddleware)
   r.HandleFunc("route", handler)
   ```

### Http
In http it seems that you would have to manually add the middleware to each route
   ```
   mux := http.NewServeMux()
   mux.Handle("route", refreshMiddleware(handler))
   ```
### Gin
Adding middleware to gin is similar to Gorilla mux as seen in its [usage](https://github.com/gin-gonic/gin#using-middleware)
   ```
   r := gin.New()
   r.Use(refreshMiddleware)
   r.GET("route", handler)
   ```

**Comment by rishabhpoddar** [comment]
@jscyo , in your examples for Gin and Mux, if the middleware does not want to do anything, and just pass the request onto the next handler, is that possible?

**Comment by jscyo** [comment]
@rishabhpoddar  yes its possible

**Comment by NkxxkN** [comment]
@rishabhpoddar 
It seems that we are already doing this, i.e:
```
supertokenBeforeHandler = supertokens.init(...);
app.before(supertokenBeforeHandler);
```

See the code in the example app in [supertokens-javalin](https://github.com/supertokens/supertokens-javalin/blob/master/Example/src/main/java/example/Main.java#L62) and [middleware code](https://github.com/supertokens/supertokens-javalin/blob/da8b88a7fc15fa0dabd0b5c9da929a35f466c23e/src/main/java/io/supertokens/javalin/SuperTokens.java#L198)

Even though we are asking to add the specific route `session/refresh` in the [SDK doc](https://supertokens.io/docs/javalin/usage/setup) as follows:

```
import io.supertokens.javalin.*;

app.before("/session/refresh", SuperTokens.middleware());
(...)
```

The docs could simply be replaced by:

```
import io.supertokens.javalin.*;

app.before("/", SuperTokens.middleware());
(...)
```

And we would handle the rest in `SuperTokens.middleware()`.

**Comment by rishabhpoddar** [comment]
@NkxxkN this means that we can implicitly define multiple API endpoints via just one middleware right?

**Comment by NkxxkN** [comment]
> @NkxxkN this means that we can implicitly define multiple API endpoints via just one middleware right?

Yes

**Comment by rishabhpoddar** [comment]
@bhumilsarvaiya in case you missed this question.

**Comment by bhumilsarvaiya** [comment]
For Flask and FastAPI, we can pass the app to the Supertokens constructor and then assign the required routes.

Example for Flask:
```python3
app = Flask()

Supertokens(app)

### in supertokens constructor

class Supertokens
    def __init__(app):
        @app.route("/")
        def func():
            #logic for the route
```

Similarly for FastAPI
```python3
app = FastAPI()

Supertokens(app)

### in supertokens constructor

class Supertokens
    def __init__(app):
        @app.post("/")
        def func():
            #logic for the route
```

For Laravel:
In the middleware we can check for the specific route and run execute the logic. For this, the middleware needs to be listed in the `$middleware` property of your `app/Http/Kernel.php` class by the user
