### ISSUE TITLE
`Host`s Whitelist

### ISSUE THREAD

**Issue by ITenthusiasm** [supertokens/supertokens-core#511]
## 🚀 Feature

It would be really awesome if SuperTokens Core supported a whitelist for hosts that could interact with it.

**Example**: Someone has a standalone Web App that hosts everything -- including their databases, SuperTokens Core, etc. It would be helpful for security reasons if we could tell SuperTokens Core to accept requests _only_ from `localhost`. :smile:

## Implementation Details

Perhaps something like an `allowed_hosts` option could be added to the `config.yaml` file? :thinking: :thought_balloon:

**Comment by rishabhpoddar** [comment]
This has been implemented and released in core version >= 4.1

You can pass in the config `ip_allow_regex` (in config.yaml file) whose value is a regex. When a request comes to the core, it will match that the IP address of that request meets the regex criteria, and only then allow it, else it will reject the request with a 403.

To allow the core to only accept requests from localhost, you can set the value of that config to `127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1` (without any quotes, or with single quotes)

If using docker, the env var is IP_ALLOW_REGEX. Note that setting this var to the above value in case of docker will prevent the host machine from querying the core, as the IP of of the host machine is not considered localhost to services running inside the docker container.
