### ISSUE TITLE
Use GCM instead of CTR for AES encryption

### ISSUE THREAD

**Issue by Baptiste-Leterrier** [supertokens/supertokens-core#524]
## 🚀 Feature

In ```src/main/java/io/supertokens/emailpassword/PasswordHashingUtils.java```, the AES part rely on 

```
// encrypting with aes
        byte[] signerBytes = Base64.decodeBase64(base64_signer_key.getBytes(StandardCharsets.US_ASCII));

        try {
            String CIPHER = "AES/CTR/NoPadding";
            Key key = new SecretKeySpec(hashedBytes, 0, 32, "AES");
            IvParameterSpec ivSpec = new IvParameterSpec(new byte[16]);
            Cipher c = Cipher.getInstance(CIPHER);
```

AES/CTR does not provide integrity and using GCM would be faster and more secure.

## Implementation details

Implementation could follow:

```
private byte[] encrypt(String plaintext, SecretKey secretKey, byte[] associatedData) throws Exception {

        byte[] iv = new byte[GCM_IV_LENGTH]; //NEVER REUSE THIS IV WITH SAME KEY
        secureRandom.nextBytes(iv);
        final Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
        GCMParameterSpec parameterSpec = new GCMParameterSpec(128, iv); //128 bit auth tag length
        cipher.init(Cipher.ENCRYPT_MODE, secretKey, parameterSpec);
```
[source for example](https://gist.github.com/patrickfav/7e28d4eb4bf500f7ee8012c4a0cf7bbf)

NIST also provide good documentation on the best practice that could be used: [here](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf)

**Comment by jscyo** [comment]
Hey @Baptiste-Leterrier , the code mentioned is part of a function used for verifying password hashes generated using [Firebase Auth's implementation of Scrypt](https://firebaseopensource.com/projects/firebase/scrypt/). We are following their recommended Java implementation found [here](https://github.com/SmartMoveSystems/firebase-scrypt-java/blob/master/src/main/java/com/smartmovesystems/hashcheck/FirebaseScrypt.java). In our testing when we use GCM we seem to be getting different values.
