### ISSUE TITLE
Atomicity issue during signup due to account linking changes

### ISSUE THREAD

**Issue by bhumilsarvaiya** [supertokens/supertokens-core#531]
This is an issue which we need to think on regarding account linking

- During the signup API, after the recipe user is created, if the process fails in between due to any reason, it can lead to one of the following problems:
  - primaryUserId was supposed to be created for the recipe user but didn't happen. Now if the user signs in, primaryUserId won't get created for the recipe user
  - if the account was supposed to be linked with another account, the linking won't happen as the process failed after the recipe user was created

The above scenario can be solved if we somehow are able to find a solution that can be atomic right from the recipe user being created till either the primaryUserId is created or the accounts are linked. Currently it is not possible as the recipeUser gets created during one core call and the primaryUserId (or account linking) happens during another core API call. One of the possible way to counter the issue would be to store some information in database regarding till what stage the account creation successfully happened during signup

**Comment by rishabhpoddar** [comment]
This issue is solved cause we attempt account linking even during sign in
