### ISSUE TITLE
`signup / signin / reset password` using telephone number OR other `metadata` adding is support using API?

### ISSUE THREAD

**Issue by Bhautik0110** [supertokens/supertokens-core#537]
I have seen email is used for signup, signing, and password reset, Is that any way to add telephone number?
I have seen the APIs of signup.
```md
POST /receipe/signup
body (json)
{
  email: "",
  password: ""
}
```
It only supports email and password, and the user created. Is that any way to add `metadata information` such as (email verification status, and other things)?

**Comment by rishabhpoddar** [comment]
See our guide for phone number and password login here: https://supertokens.com/docs/phonepassword/introduction

This isn't really a bug in supertokens, so closing this issue

**Comment by Bhautik0110** [comment]
I knew this is not a bug, In API documentation I cannot find signup using telephone number, or add extra data.

**Comment by rishabhpoddar** [comment]
There is no API for sign up with telephone number in email password recipe.
