### ISSUE TITLE
[RELEASE] CSS change for social login button

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#540]
# 📅 Checklist

### Dev Tag
 - [x] [supertokens-auth-react:X.Y](https://github.com/supertokens/supertokens-auth-react/tree/X.Y)
    - [x] check FDI list
    - [x] check web-js interface version
    - [x] Updated dependencies to use supertokens-web-js in package.json from npm registry
    - [x] Various browsers - Safari, Firefox, Chrome, Edge
    - [x] Mobile responsiveness
    - [x] Make sure using with-typescript example that types are correct for every new configs exposed to users
    - [x] Make sure frontend login UI shows even if backend is not working.

### Others

-  [x] Example apps in create-supertokens-app CLI
 - [x] Examples apps in supertokens-auth-react
 - [x] [next.js:canary](https://github.com/supertokens/next.js/tree/canary/examples/with-supertokens)
 - [ ] RedwoodJS and playground-auth
 - [x] Run on netlify (and hence AWS lambda) to check if it works fine there
 - [x] Test on vercel (with-emailpassword-vercel app) 
 - [x] SuperTokens Jackson SAML example update
 - [x] Supabase example app

### 📚 Documentation (test site)

- [ ] All recipe main documentation update

- [ ] community documentation update

- [ ] website changes (supertokens.io)

- [ ] blog changes

### 💻 NPM and core release

 - [x] [supertokens-auth-react:X.Y](https://github.com/supertokens/supertokens-auth-react/tree/X.Y)

### 📚 Documentation

- [x] Pushed to production
- [x] Post message on discord about new update
- Auto generate release note on github:
   - [x] supertokens-auth-react

**Comment by alisher-aituarov** [comment]
Example apps in create-supertokens-app CLI (done)
 Examples apps in supertokens-auth-react (created PR)
 [next.js:canary](https://github.com/supertokens/next.js/tree/canary/examples/with-supertokens)
 RedwoodJS and playground-auth
 Run on netlify (and hence AWS lambda) to check if it works fine there
 Test on vercel (with-emailpassword-vercel app)
 SuperTokens Jackson SAML example update
 Supabase example app
