### ISSUE TITLE
Create first user account automatically when starting Supertokens

### ISSUE THREAD

**Issue by itsjef** [supertokens/supertokens-core#543]
## 🚀 Feature

When starting a Supertokens service instance, I want to automatically populate its database with a default user account.

For example, with [Keycloak](https://www.keycloak.org/getting-started/getting-started-docker) I can create the default admin account using `KEYCLOAK_ADMIN` and `KEYCLOAK_ADMIN_PASSWORD` environment variables when starting the service Docker container:

```bash
$ docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:20.0.2 start-dev
```

One of the suggested method is to use a separate one-off Docker container to seed the database, as shown in [this SO answer](https://stackoverflow.com/a/33397913/6026378), however I don't want to go that way to reduce possibility of human error and risks to my system with dangling container.

**Comment by itsjef** [comment]
A second method is to mount config files containing initial data, similar to Authelia:
- config file: https://github.com/authelia/authelia/blob/v4.37.4/examples/compose/lite/authelia/configuration.yml#L26-L28
- data file: https://github.com/authelia/authelia/blob/v4.37.4/examples/compose/lite/authelia/users_database.yml#L9-L18

**Comment by rishabhpoddar** [comment]
Hey @itsjef i believe this refers to creating a default account to access the keycloak dashboard (as opposed to an end user account)?

**Comment by itsjef** [comment]
@rishabhpoddar you are correct, I meant to ask about creating an end user account but with a similar method to Keycloak's.

**Comment by rishabhpoddar** [comment]
Ah i see. That's a bit of an edge case for us to handle honestly. I don't think we will make this happen anytime soon anyway. For now, your best best is to seed the SuperTokens core post backend SDK initialisation.

**Comment by itsjef** [comment]
I see, thank you for your response.
