### ISSUE TITLE
Docker compose file should use health check.

### ISSUE THREAD

**Issue by joshxyzhimself** [supertokens/supertokens-core#557]
#### Bug Report

Docker compose file at https://supertokens.com/use-oss should use health check.

#### Useful Information

Instead of:

```docker
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:4.3
    depends_on:
      - db
```

It should be:

```docker
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:4.3
    depends_on:
      db:
        condition: service_healthy
```

#### References

- https://docs.docker.com/compose/compose-file/#depends_on

**Comment by rishabhpoddar** [comment]
pushed this change to prod.

**Comment by rishabhpoddar** [comment]
This has been added to the docs and /use-oss page on our site. Thanks
