### ISSUE TITLE
[RELEASE]: Remove emotion

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#558]
# 📅 Checklist

### Dev Tag
 - [x] [supertokens-web-js:X.Y](https://github.com/supertokens/supertokens-web-js/X.Y)
   - [x] check FDI list
   - [x] check web-js interface version
   - [x] Update dependency version of supertokens-website in package.json  from npm registry
 - [x] [supertokens-auth-react:X.Y](https://github.com/supertokens/supertokens-auth-react/tree/X.Y)
    - [x] check FDI list
    - [x] check web-js interface version
    - [x] Updated dependencies to use supertokens-web-js in package.json from npm registry
    - [x] Various browsers - Safari, Firefox, Chrome, Edge
    - [x] Mobile responsiveness
    - [x] Make sure using with-typescript example that types are correct for every new configs exposed to users
    - [x] Make sure frontend login UI shows even if backend is not working.

### Others

-  [x] Example apps in create-supertokens-app CLI
 - [x] Example apps in supertokens-auth-react
 - [x] Example apps in supertokens-web-js
 - [x] [next.js:canary](https://github.com/supertokens/next.js/tree/canary/examples/with-supertokens)
 - [ ] RedwoodJS and playground-auth
 - [x] Run on netlify (and hence AWS lambda) to check if it works fine there
 - [x] Test on vercel (with-emailpassword-vercel app) 
 - [x] SuperTokens Jackson SAML example update
 - [x] Supabase docs

### 📚 Documentation (test site)

- [x] All recipe main documentation update

### 💻 NPM and core release
 - [x] [supertokens-web-js:X.Y](https://github.com/supertokens/supertokens-web-js/tree/X.Y)
 - [x] [supertokens-auth-react:X.Y](https://github.com/supertokens/supertokens-auth-react/tree/X.Y)

### 📚 Documentation

- [x] Pushed to production
- [x] Post message on discord about new update
- Auto generate release note on github:
   - [x] supertokens-website
   - [x] supertokens-web-js
   - [x] supertokens-auth-react

**Comment by alisher-aituarov** [comment]
set to latest in create-supertokens-app CLI
