### ISSUE TITLE
SvelteKit

### ISSUE THREAD

**Issue by NelminDev** [supertokens/supertokens-core#584]
## 🚀 Feature

Support for SvelteKit

## Implementation details

I would like to use SuperTokens in my other Projects that use SvelteKit

**Comment by Coinhexa** [comment]
If you are not planning to add this feature immediately, atleast some documentation of how to build your own svelte component that handles login with supertokens would also be very helpful

**Comment by rishabhpoddar** [comment]
Here is an example app that uses sveltekit and our pre built ui: https://github.com/supertokens/supertokens-auth-react/tree/master/examples/with-svelte-react-thirdpartyemailpassword
