### ISSUE TITLE
For all components, change ./addDev and ./addReleaseTag

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#59]
- [x] Add an empty commit with the latest build so that we are sure that the latest build is being released
   - For all java based projects, we want to rebuild the JARs 
   - For all typescript based projects, we want to rebuild so that all `ts` is converted to `js`
- [x] Enforce that there are no updates to master that are not applied to this branch
- [x] In `./addReleaseTag`, remove the `--ours` in the merge command when merging into master

---------
- [x] core
- [x] plugin interface
- [x] mysql
- [x] postgresql
- [x] mongodb
- [x] nodejs
- [x] website
- [x] auth-react

**Comment by rishabhpoddar** [comment]
@NkxxkN I have made changes to the core's script for this, so you can simply take from there. The commit is above

**Comment by rishabhpoddar** [comment]
@NkxxkN the above commit is for node. You can do the exact same changes for your the other two repos, and they should work.

**Comment by NkxxkN** [comment]
Last PR for supertokens-auth-react ^ 

Thanks for taking care of supertokens-node and website! I was caught in testing for supertokens-auth-react
