### ISSUE TITLE
Help needed - Cloud deployment empty signup error.

### ISSUE THREAD

**Issue by kumkee** [supertokens/supertokens-core#612]
I am following the [thirdpartyemailpassword guide](https://supertokens.com/docs/thirdpartyemailpassword/custom-ui/email-password-login) to experiment with my [Elm frontend and fastapi backend combo](https://github.com/kumkee/SupertokensElm).

It works perfectly on my localhost when signing up a new user but the core returns an empty error to me when the frontend is deployed in the cloud.

I tried [outputting the error message by stringification](https://github.com/kumkee/SupertokensElm/blob/main/frontend/src/js/stks_sdk.js#L38) but the message is empty `{}`.

What should I do next to find out what went wrong, please?

**Comment by rishabhpoddar** [comment]
The frontend shouldn't query the core directly. The error is coming from your fastapi backend. Do you see any error logs in there?

**Comment by kumkee** [comment]
> The frontend shouldn't query the core directly. 

But it is coming from your frontend SDK function `supertokensThirdPartyEmailPassword.emailPasswordSignUp()` in [this line](https://github.com/kumkee/SupertokensElm/blob/main/frontend/src/js/stks_sdk.js#L3)

> The error is coming from your fastapi backend. Do you see any error logs in there?

```
[WARNING] 2023-03-31T07:04:31.550Z unable to cache publicsuffix.org-tlds.{'urls': ('https://publicsuffix.org/list/public_suffix_list.dat', 'https://raw.githubusercontent.com/publicsuffix/list/master/public_suffix_list.dat'), 'fallback_to_snapshot': True} in /opt/python/tldextract/.suffix_cache/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json. This could refresh the Public Suffix List over HTTP every app startup. Construct your `TLDExtract` with a writable `cache_dir` or set `cache_dir=False` to silence this warning. [Errno 30] Read-only file system: '/opt/python/tldextract/.suffix_cache'
/opt/python/supertokens_python/utils.py:197: RuntimeWarning: Inconsistent mode detected, check if you are using the right asgi / wsgi mode
warnings.warn(
```
It is a warning and it doesn't look vital.

**Comment by KShivendu** [comment]
Hi again @kumkee, 

Can you check the network tab of developer tools and share the response of the emailpassword signup API when you try to signup? Also, see if there are any error in the Devtools console.

**Comment by kumkee** [comment]
Hi @KShivendu,
Great tip.
> Can you check the network tab of developer tools and share the response of the emailpassword ...

The network tab gave me the following error (URLs are hidden in this public discussion for security consideration)
```
Access to fetch at '[BACKEND URL]' from origin '[FRONTEND URL]' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

It looks like it is to do with my [CORS middleware setting](https://github.com/kumkee/SupertokensElm/blob/main/backend/main.py#L63) but I'd double check my [FRONTEND_URL](https://github.com/kumkee/SupertokensElm/blob/main/backend/main.py#L29) there is correct.

**Comment by KShivendu** [comment]
If the setup is correct, Deta might be altering the headers. 

`Access-Control-Allow-Origin` header seems to be missing. See if there's any setting/config from deta that you need to alter. Also, put this route before adding the CORS middleware:
```
@app.get('/')
async def root():
    """Return dummy message."""
    return {'message': 'Hello World'}
```

and tell me if you're able to access it or not.

**Comment by kumkee** [comment]
It turns out that there is an extra `/` at the end of my frontend URL. Without that `/`, it now works!
I didn't know fastapi's URL rule is so strict. 
I couldn't have done this without your hints, @KShivendu - I love SuperTokens.
