### ISSUE TITLE
`updateEmailOrPassword` with password without email 500s

### ISSUE THREAD

**Issue by cyrilchapon** [supertokens/supertokens-core#620]
## 🐛 Bug Report

When sending such a payload to `updateEmailOrPassword` :
```json5
{
  userId: 'd6d62489-69d3-41a0-b2e5-7af6c78b249f',
  password: 'testPass124'
}
```
(password update without email)

Supertokens fails with a 500.

## Useful informations

Stacktrace :

> > mtn-supertokens-supertokens-1  | 03 Apr 2023 21:59:27:070 +0000 | ERROR | pid: c62d4d6a-d784-48c2-a219-1b95683eeff3 | [http-nio-0.0.0.0-3567-exec-7] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:170) | java.lang.NullPointerException: Cannot invoke "String.trim()" because "email" is null
mtn-supertokens-supertokens-1  | 	at io.supertokens.utils.Utils.normaliseEmail(Utils.java:54)
mtn-supertokens-supertokens-1  | 	at io.supertokens.webserver.api.emailpassword.UserAPI.doPut(UserAPI.java:132)
mtn-supertokens-supertokens-1  | 	at io.supertokens.webserver.RecipeRouter.doPut(RecipeRouter.java:91)
mtn-supertokens-supertokens-1  | 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:734)
mtn-supertokens-supertokens-1  | 	at io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:168)
mtn-supertokens-supertokens-1  | 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814)
mtn-supertokens-supertokens-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
mtn-supertokens-supertokens-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
mtn-supertokens-supertokens-1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
mtn-supertokens-supertokens-1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
mtn-supertokens-supertokens-1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
mtn-supertokens-supertokens-1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
mtn-supertokens-supertokens-1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
mtn-supertokens-supertokens-1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
mtn-supertokens-supertokens-1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
mtn-supertokens-supertokens-1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400)
mtn-supertokens-supertokens-1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
mtn-supertokens-supertokens-1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
mtn-supertokens-supertokens-1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1739)
mtn-supertokens-supertokens-1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
mtn-supertokens-supertokens-1  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
mtn-supertokens-supertokens-1  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
mtn-supertokens-supertokens-1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
mtn-supertokens-supertokens-1  | 	at java.base/java.lang.Thread.run(Thread.java:832)
mtn-supertokens-supertokens-1  |

**Comment by nkshah2** [comment]
Hi @cyrilchapon 

Thanks for the issue, what version of SuperTokens core are you using? If it is below 4.4.2 you will need to upgrade, this issue was solved in that version. If you are already using a version greater than that do let us know. Refer to https://github.com/supertokens/supertokens-node/issues/514#issuecomment-1471565136

Closing this issue for now, feel free to re-open
