### ISSUE TITLE
MFA design

### ISSUE THREAD

**Issue by KShivendu** [supertokens/supertokens-core#648]
# 🚀 Multi Factor Authentication (MFA)

## SQL Table Schema:

```sql
CREATE TABLE IF NOT EXISTS mfa_enabled_factors (
    user_id VARCHAR(128) NOT NULL,  -- Could be primary user ID (based on account linking) OR first factor user ID
    factor VARCHAR(16) NOT NULL, -- Can be "totp", "passwordless", "biometric", etc.
    PRIMARY KEY (user_id, factor_id)
);

-- Index isn't required since PRIMARY KEY already creates an index
```

### GET /mfa/factors/list?userId=userId

Output:
```js
{
  status: "OK",
  factors: ["totp", "biometric", "passwordless"] // list is empty if no user/factor is found
}
```

### POST /mfa/factors/enable

Input:
```js
{
    userId: "<userId>",
    factor: "totp" 
}
```

Output:
```js
{
   status: "OK",
   wasAlreadyEnabled: bool
}
```

### POST /mfa/factors/disable

Input:

```js
{
    userId: "<userId>",
    factor: "totp" 
}
```

Output:

```js
{
  status: "OK",
  didExist: bool
}
```

**Comment by rishabhpoddar** [comment]
## Architecture aim:
- [ ] Need to have a separate API for MFA account linking which is enabled if the MFA feature is enabled and account linking is not. This API will only allow account linking for the purpose of MFA. So you need to enforce that, somehow.
- [ ] Devs should be able to set MFA settings for tenants via an API call (similar to how they configure third party providers for tenants via an API call). This should be as flexible as possible.

**Comment by rishabhpoddar** [comment]
Closing this in priority of: https://github.com/supertokens/supertokens-core/issues/554
