### ISSUE TITLE
Please use github Discussions

### ISSUE THREAD

**Issue by hrstoyanov** [supertokens/supertokens-core#675]
## 🚀 Feature

Please use Github Discussions instead of Discord - forcing developers to create Disord accounts just so they can request a features is unreasonable. Github Discussions, in contrast is  readily available without friction.

**Comment by rishabhpoddar** [comment]
hey @hrstoyanov appreciate the feedback. But this is a company choice and we aren't going to move away from discord anytime soon. If you have any questions, you can open issues about it on github instead. You can even email us or use our website chat.
