### ISSUE TITLE
Multi-tenancy logout session issue (one login per domain)

### ISSUE THREAD

**Issue by underfisk** [supertokens/supertokens-core#718]
## 🐛 Bug Report

I've been back and forth with @rishabhpoddar in Discord regarding this issue but essentially having 2 React applications where application A signs in and application B(In this example application B shares the same session)  attempts to sign out will leave a stuck state because the cookies are never being cleared. 

### Example of our initialization
````typescript
SuperTokens.init({
  appInfo: config.superTokensAppInfo,
  recipeList: [
    Session.init({})
  ],
});
````

For more context/information here's [Discord thread](https://discord.com/channels/603466164219281420/644849840475602944/1118616688766759033)

**Comment by rishabhpoddar** [comment]
This issue has now been solved in the latest versions of the sdks (see below). The sign out API now requires a session, and if missing, it results in a 401, which will trigger a refresh.
- node >= 17.0.7
- python >=0.19.0
- golang >= 0.18.0
