### ISSUE TITLE
Migration script in changelog is wrong.

### ISSUE THREAD

**Issue by crro** [supertokens/supertokens-core#734]
## 🐛 Bug Report

In the changelog the migrations script to start using version 6 fails with the error below. 

## Useful informations

(Write what happened. Add screenshots, stacktraces, videos, anything that can help)
```
ALTER TABLE dashboard_users
  ADD COLUMN IF NOT EXISTS app_id VARCHAR(64) DEFAULT 'public';

ALTER TABLE dashboard_users
  DROP CONSTRAINT dashboard_users_pkey CASCADE;

ALTER TABLE dashboard_users
  ADD CONSTRAINT dashboard_users_pkey
    PRIMARY KEY (app_id, user_id);
ERROR:  relation "dashboard_users" does not exist
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

**Comment by rishabhpoddar** [comment]
Hey @crro which version are you upgrading from?

**Comment by crro** [comment]
I went from 4.2 to 5 and then to 6. I just realized that I missed the db migrations from 4.4 https://github.com/supertokens/supertokens-core/blob/cb1c795bffc9575731ecd7247c42c536b3a7f97f/CHANGELOG.md#database-changes-2 but there is not script for those. Could you provide them? What fields and constraints should those tables have?

**Comment by crro** [comment]
oh and this ones too: https://github.com/supertokens/supertokens-core/blob/cb1c795bffc9575731ecd7247c42c536b3a7f97f/CHANGELOG.md#database-changes-1 

where can I see these migrations?

**Comment by crro** [comment]
Actually, just saw these: https://supertokens.com/docs/passwordless/custom-ui/init/database-setup/postgresql are these up to date? It would be great to have the migrations available to be able to run them ourselves.

**Comment by rishabhpoddar** [comment]
They are all up to date indeed. You just have to make sure to do it step by step from one version to another.

Im closing this issue for now since there doesn't seem to be any issue with the scripts provided.
