### ISSUE TITLE
[Website] : Horizontal scrolling bug in testimonials carousel

### ISSUE THREAD

**Issue by MenaiAla** [supertokens/supertokens-core#794]
First,

Thank you so much for this project and your documentation.

While  I was discovering your website, I found that I could not see the first example ( it does not appear fully ) : 

![image](https://github.com/supertokens/supertokens-core/assets/20143684/d7569896-357c-446e-a553-ced61be1f646)

**Comment by Chakravarthy7102** [comment]
Hey @MenaiAla, Thanks for reporting this. I have checked this it seems to work fine. can you give more information like what device you are using (maybe a video would be more helpful) to understand this better.

**Comment by MenaiAla** [comment]
Yes, @Chakravarthy7102. I checked it out this morning and it looks normal, however, I still see this horizontal scrollbar:

![image](https://github.com/supertokens/supertokens-core/assets/20143684/da6f9f1a-5df3-41fc-a573-861d9735dabf)

I mean it is better to hide the horizontal scrollbar. What do you think?

**Comment by Chakravarthy7102** [comment]
yepp, It's a fair point. will do it sometime in this week.
Thank you!

**Comment by Chakravarthy7102** [comment]
Hey @MenaiAla, I fixed this issue you check at [supertokens.com](https://supertokens.com).
Thanks!
