### ISSUE TITLE
React Native - Checking if email is unique

### ISSUE THREAD

**Issue by Maciej-Siara** [supertokens/supertokens-core#827]
## 🐛 Bug Report

(A clear and concise description of what the bug is)
Documentation says that 
`curl --location --request GET 'http://localhost:3101/api/signup/email/exists?email=john@example.com' \
--header 'rid: thirdpartyemailpassword'`
Should give response as described below:
status: "OK": The response will also contain a doesExist boolean which will be true if the input email already belongs to an email password user.
In real world the response is different, It gives fields _exists_ instead of field _doesExist_
`{"exists": true, "status": "OK"}`

## Useful informations
Checked for "supertokens-react-native": "^4.0.7",

(Write what happened. Add screenshots, stacktraces, videos, anything that can help)

**Comment by nkshah2** [comment]
Hi @Maciej-Siara 

Thanks for the issue, can you link to where in the documentation you are referring to?

**Comment by rishabhpoddar** [comment]
This has been fixed now on our site.
