### ISSUE TITLE
Invalid condition in if statement

### ISSUE THREAD

**Issue by Taz03** [supertokens/supertokens-core#831]
## 🐛 Bug Report

In `InputParser` some method throws NPE when nullable is true and the value is null, while it should be when nullable is false and value is null

## Useful informations

https://github.com/supertokens/supertokens-core/blob/95024498ff968adf9ecff4ed2827829b02ef782d/src/main/java/io/supertokens/webserver/InputParser.java#L51

https://github.com/supertokens/supertokens-core/blob/95024498ff968adf9ecff4ed2827829b02ef782d/src/main/java/io/supertokens/webserver/InputParser.java#L67

**Comment by rishabhpoddar** [comment]
I see that both the places you have highlighted have the `!nullable` check. So it throws when it's should not be nullable and it is null in both the places. Am i missing something?

**Comment by Taz03** [comment]
hmm no, my bad
