### ISSUE TITLE
Unable to instantiate supertokens-mysql:7.0 in docker

### ISSUE THREAD

**Issue by hopinheimer** [supertokens/supertokens-core#863]
## 🐛 Bug Report

```
Tenant(, public, public) | What caused the crash: io.supertokens.pluginInterface.exceptions.DbInitException: java.sql.SQLTransientConnectionException: (conn=41) Failed to add the foreign key constraint. Missing column 'app_id' for constraint 'emailpassword_user_to_tenant_ibfk_1' in the referenced table 'all_auth_recipe_users'
```
the core never instantiates and fails after this message. 

## Useful informations
running on docker engine: 24.0.5

**Comment by Shivam24Shukla** [comment]
Could you please specify the software application you're having trouble with, the particular task you wish to verify by double-clicking, and which form details are not updating correctly? Providing detailed information will help us assist you more effectively

**Comment by hopinheimer** [comment]
this was a migration issue @rishabhpoddar helped me resolving this. thanks anyways! closing the issue for now
