### ISSUE TITLE
Allow logging of core HTTP requests

### ISSUE THREAD

**Issue by jamalaberque** [supertokens/supertokens-core#865]
## 🚀 Feature

Logging HTTP requests sent to the core allows users to monitor what traffic they send to SuperTokens, avoid flooding it for no reason, and comply with the new rate limits.

This should be functional for users of SuperTokens SaaS as well as self-hosted.

## Implementation details

(Please outline any details about how this feature would e implemented. If you don't know, you can just skip this section.)

## Discord thread
[https://discord.com/channels/603466164219281420/1166656686644277259](https://discord.com/channels/603466164219281420/1166656686644277259)

**Comment by IamMayankThakur** [comment]
We've added support for a hook that intercepts all outgoing traffic from the SDK. This can be used to intercept as well as modify the request to the core. This feature has been added in all three sdks: 
- python - [v0.16.8](https://github.com/supertokens/supertokens-python/releases/tag/v0.16.8)
- go - [v0.16.6](https://github.com/supertokens/supertokens-golang/releases/tag/v0.16.6)
- node - [v16.5.0](https://github.com/supertokens/supertokens-node/releases/tag/v16.5.0)

Here's a `node` example for how to use it. Detailed docs for all sdks will be up soon.

```typescript
SuperTokens.init({
            supertokens: {
                connectionURI,
                // new hook
                networkInterceptor: (request: HttpRequest, userContext: any) => {
                    console.log("http request to core: ", request)                    
                    return request; // this can also return a modified request object.
                },
            },
            appInfo: {
                apiDomain: "api.supertokens.io",
                appName: "SuperTokens",
                websiteDomain: "supertokens.io",
            },
            recipeList: [
                EmailPassword.init(),
            ],
        });
```
