### ISSUE TITLE
The verified field of the user login methods doesn't take the external user id mapping into account

### ISSUE THREAD

**Issue by DavidHackettSME** [supertokens/supertokens-core#872]
## 🐛 Bug Report

`getUser` function in `supertokens-node` is returning `emailpassword` login methods as unverified even though they have been verified already.

This appears to just be happening for users that have an external mapped user id.
 

## Useful informations

When verifying a user with an external user id mapping, we're passing in the external id as the recipeUserId and userId as this is what is returned by `getUser` after updating the mapping. The simplified logic in our `emailPasswordSignUp` function override is as so:

```
const response =
  await originalImplementation.emailPasswordSignUp(input);

await supertokens.createUserIdMapping({
  superTokensUserId: response.user.id,
  externalUserId: input.userContext.externalUserId,
});

const updatedUser = await supertokens.getUser(
  input.userContext.externalUserId,
);

// With the mapping update, the id and login methods have changed so update the response so that the session creation after this succeeds
response.user = updatedUser;
response.recipeUserId = supertokens.convertToRecipeUserId(
  input.userContext.externalUserId,
);

await EmailVerification.sendEmailVerificationEmail(
  "public",
  response.user.id,
  response.recipeUserId,
);

return response
```

After the email is verified by this we have an entry in the `emailverification_verified_emails` table with the external user id as the `user_id`. This seems to be working as the `st-ev` validation claim in the access token is `true` and the result of `isEmailVerified(externalUserId)` also returns true.

However, `getUser` continues returning `false` for the `verified` field in the login methods when I would expect it to return true instead.

As an example where '2377' is the external mapped id for a user where `st-ev` is `true` and the logged lines are from the login methods of `getUser` and the response of `isEmailVerified(externalUserId)`:
<img width="580" alt="Screenshot 2023-10-31 at 15 05 36" src="https://github.com/supertokens/supertokens-core/assets/99645396/10e38d60-e505-4534-b832-09638d7c0232">

If the email verification is updated to use the supertokens user id then the `verified` field in `getUser` is `true` but `isEmailVerified` and the `st-ev` claim become false.

**Comment by rishabhpoddar** [comment]
This has been fixed in core version >= 7.0.9.

The docker image tag is still `7.0` (you have to remove and re pull the image).
