### ISSUE TITLE
Phone Number Normalization Discrepancy in SDKs and APIs

### ISSUE THREAD

**Issue by anku255** [supertokens/supertokens-core#880]
## 🐛 Bug Report

Currently, phone number normalization relies on SDKs, leading to a potential disparity between the queried phoneNumber and the actual stored value in the database. Consider the following scenario: 

```
input phoneNumber -> 555-123-4567

The createUser function in the SDK doesn't normalize this input, storing it as-is in the Database.

input phoneNumber -> 555-123-4567

searchUserByPhoneNumber normalizes the input to +5551234567, but it is unable to locate the user as the phone number doesn't match.

```

## Suggestion Solution

Implement phone number normalization at the core level for every API. This approach would ensure consistent behavior across all APIs and SDKs.

## Backwards Compatibility

To maintain compatibility, we propose adding a cron job to normalize all stored phone numbers in the database. This cron job would also introduce a flag, such as `isPhoneNumberNormalized`, ensuring that phone numbers are normalized only once.

The default flag value for any new user would be true since the APIs would have already normalized it during the initial processing.

## TODO:
- [x] add test where input is not a phone number
- [x] migration script
- [ ] update saas infra migration code to run the custom script

**Comment by rishabhpoddar** [comment]
This has been fixed in core version >= 7.0.12. For users migrating to this and using the passwordless recipe, please be sure to checkout [the changelog](https://github.com/supertokens/supertokens-core/blob/master/CHANGELOG.md), for migration instructions that normalises existing phone numbers in the database.
