### ISSUE TITLE
Can not delete own account or change data

### ISSUE THREAD

**Issue by coderbm1** [supertokens/supertokens-core#883]
## 🐛 Bug Report

Can not delete own account

## Useful informations

As logged in user go to your Settings and similar - see no possibility to remove own account. The same with - no way to change own data from Register step (what about typos/mistakes)

Kind regards,

**Comment by coderbm1** [comment]
Hey @ rishabhpoddar sure, sorry. I am focused here on the https://supertokens.com/auth

**Comment by rishabhpoddar** [comment]
Ah right. So this isn't really an issue with the core. So this is the wrong place to open the issue. I'll instead add it to our internal issue (since the website is closed source).

Thanks.

**Comment by coderbm1** [comment]
Thank you so much! Have a nice day
