### ISSUE TITLE
Add `primary_or_recipe_user_id` index to `app_id_to_user_id`

### ISSUE THREAD

**Issue by DavidHackettSME** [supertokens/supertokens-core#887]
## 🐛 Bug Report

I think postgresql table `app_id_to_user_id` should have an index to get rows by `(app_id, primary_or_recipe_user_id)`

(Apologies if raising as the wrong issue type, wasn't certain if more of a feature or bug)

## Useful informations

Hello there, I've got a potential bug regarding the postgresql database setup, specifically for getting a user please. 

From the database setup and the db query made as part of the `/user/id` API, specifically

```
SELECT au.user_id, au.primary_or_recipe_user_id, au.is_linked_or_is_a_primary_user, au.recipe_id, aaru.tenant_id, aaru.time_joined 
FROM supertokens.app_id_to_user_id as au 
LEFT JOIN supertokens.all_auth_recipe_users as aaru 
ON au.app_id = aaru.app_id 
AND au.user_id = aaru.user_id 
WHERE au.primary_or_recipe_user_id IN (
    SELECT primary_or_recipe_user_id
    FROM supertokens.app_id_to_user_id
    WHERE (user_id IN ($1) OR primary_or_recipe_user_id IN ($2)) AND app_id = $3) 
AND au.app_id = $4;
```

it looks like it's scanning  `app_id_to_user_id` by `primary_or_recipe_user_id` which has no index so it's reading 10000s of lines which I don't think it needs to when trying to get a user.

<img width="919" alt="Screenshot 2023-11-20 at 16 00 21" src="https://github.com/supertokens/supertokens-core/assets/99645396/8135daee-58c0-44b9-a133-54f852dedd40">

Not sure if an index has been considered before but I think it'd help to add an index as part of the database set up to make the query more efficient and reduce database load.

**Comment by rishabhpoddar** [comment]
Hey @DavidHackettSME thanks for finding this. We have added the index to the postgresql plugin. You can add it to your db as well:

```
CREATE INDEX IF NOT EXISTS app_id_to_user_id_primary_user_id_index ON app_id_to_user_id (primary_or_recipe_user_id, app_id);
```

I am keeping this issue open because we are still seeing slow queries for our mysql integration.

**Comment by rishabhpoddar** [comment]
Thank you @DavidHackettSME  👍

**Comment by rishabhpoddar** [comment]
For MySQL users please add the following index:
```
CREATE INDEX app_id_to_user_id_primary_user_id_index ON app_id_to_user_id (primary_or_recipe_user_id);
CREATE INDEX app_id_to_user_id_user_id_index ON app_id_to_user_id (user_id);
```
