### ISSUE TITLE
Unhandled exception error in backend when connecting core to aws RDS postgresql

### ISSUE THREAD

**Issue by tenghuil** [supertokens/supertokens-core#903]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

![image](https://github.com/supertokens/supertokens-core/assets/131498603/0cc87f27-246f-4428-bb74-a4e5b9f1333b)

The exception only happens when i connect core to RDS postgresql. If I use in memory mysql or postgresql, everything works fine. I have verified that core is writing data successfully into my RDS postgresql but I don't quite understand why the exception happens.

## Useful informations

(Write what happened. Add screenshots, stacktraces, videos, anything that can help)
I'm following demo [doc](https://supertokens.com/docs/session/quick-setup/database-setup/postgresql) to run the e2e flow.

**My test frontend is react:**

```
import React from 'react';

import { EmailPasswordPreBuiltUI } from "supertokens-auth-react/recipe/emailpassword/prebuiltui";
import { canHandleRoute, getRoutingComponent } from "supertokens-auth-react/ui";

import SuperTokens, { SuperTokensWrapper } from "supertokens-auth-react";
import EmailPassword from "supertokens-auth-react/recipe/emailpassword";
import Session from "supertokens-auth-react/recipe/session";

SuperTokens.init({
    appInfo: {
        // learn more about this on https://supertokens.com/docs/emailpassword/appinfo
        appName: "imagegen",
        apiDomain: "http://localhost:8000",
        websiteDomain: "http://localhost:3000",
        apiBasePath: "/auth",
        websiteBasePath: "/auth",
    },
    recipeList: [
        EmailPassword.init(),
        Session.init()
    ]
});

class App extends React.Component {
    render() {
        if (canHandleRoute([EmailPasswordPreBuiltUI])) {
            // This renders the login UI on the /auth route
            return getRoutingComponent([EmailPasswordPreBuiltUI])
        }

        return (
            <SuperTokensWrapper>{/*Your app*/}</SuperTokensWrapper>
        );
    }
}
```

**My backend is using flask:**

```
from flask import Flask, abort
from supertokens_python import init, InputAppInfo, SupertokensConfig
from supertokens_python.recipe import emailpassword, session, dashboard
from supertokens_python import get_all_cors_headers
from flask_cors import CORS
from supertokens_python.framework.flask import Middleware

init(
    app_info=InputAppInfo(app_name="imagegen",
                          api_domain="http://localhost:8000",
                          website_domain="http://localhost:3000",
                          api_base_path="/auth",
                          website_base_path="/auth"),
    supertokens_config=SupertokensConfig(
        # https://try.supertokens.com is for demo purposes. Replace this with the address of your core instance (sign up on supertokens.com), or self host a core.
        connection_uri="http://localhost:3567",
        # api_key=<API_KEY(if configured)>
    ),
    framework='flask',
    recipe_list=[
        session.init(),  # initializes session features
        emailpassword.init(),
        dashboard.init(),
    ])

app = Flask(__name__)

Middleware(app)

CORS(
    app=app,
    origins=["http://localhost:3000"],
    supports_credentials=True,
    allow_headers=["Content-Type"] + get_all_cors_headers(),
)


@app.route('/', defaults={'u_path': ''})
@app.route('/<path:u_path>')
def catch_all(u_path: str):
    abort(404)
```

I'm starting core with docker using the following command:

```
docker run \
  -p 3567:3567 \
  -e POSTGRESQL_USER="my_db_name"\
  -e POSTGRESQL_HOST="my_host" \
  -e POSTGRESQL_PORT="5432" \
  -e POSTGRESQL_PASSWORD="my_pwd" \
  -e POSTGRESQL_DATABASE_NAME="my_db_name" \
  -d registry.supertokens.io/supertokens/supertokens-postgresql


```

**Comment by rishabhpoddar** [comment]
Do you see any error logs in the core? You can run `docker logs <CONTAINER_ID>` to get more info.

**Comment by tenghuil** [comment]
> Do you see any error logs in the core? You can run `docker logs <CONTAINER_ID>` to get more info.

No errors in the core. The data is even written into the db

**Comment by rishabhpoddar** [comment]
Does the core log have something like - ended API /recipe/signup? Cause if there is no error in the core, im not quite sure why the python sdk is indicating that there is an error whilst querying the core.

**Comment by tenghuil** [comment]
> Does the core log have something like - ended API /recipe/signup? Cause if there is no error in the core, im not quite sure why the python sdk is indicating that there is an error whilst querying the core.
> 
> Could you share the core logs as well?

Loading supertokens config.
Completed config.yaml loading.
Loading storage layer.
Loading PostgreSQL config.
Loading supertokens version.yaml file.
05 Jan 2024 02:57:36:061 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [main] thread | io.supertokens.storage.postgresql.ConnectionPool.initPool(ConnectionPool.java:136) | Setting up PostgreSQL connection pool.

Setting up PostgreSQL connection pool.
05 Jan 2024 02:57:49:631 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [main] thread | io.supertokens.cronjobs.CronTask.<init>(CronTask.java:59) | Tenant(, public, public) | Starting task: EELicenseCheck

05 Jan 2024 02:57:55:876 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [main] thread | io.supertokens.cronjobs.CronTask.<init>(CronTask.java:69) | Tenant(, public, public) | Starting task: SyncCoreConfigWithDb

05 Jan 2024 02:57:55:878 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [main] thread | io.supertokens.cronjobs.CronTask.<init>(CronTask.java:59) | Tenant(, public, public) | Starting task: RemoveOldSessions

05 Jan 2024 02:57:55:879 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [main] thread | io.supertokens.cronjobs.CronTask.<init>(CronTask.java:59) | Tenant(, public, public) | Starting task: RemoveOldPasswordResetTokens

05 Jan 2024 02:57:55:880 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [main] thread | io.supertokens.cronjobs.CronTask.<init>(CronTask.java:59) | Tenant(, public, public) | Starting task: RemoveOldEmailVerificationTokens

05 Jan 2024 02:57:55:881 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [main] thread | io.supertokens.cronjobs.CronTask.<init>(CronTask.java:59) | Tenant(, public, public) | Starting task: DeleteExpiredPasswordlessDevices

05 Jan 2024 02:57:55:882 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [main] thread | io.supertokens.cronjobs.CronTask.<init>(CronTask.java:59) | Tenant(, public, public) | Starting task: DeleteExpiredTotpTokens

05 Jan 2024 02:57:55:883 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [main] thread | io.supertokens.cronjobs.CronTask.<init>(CronTask.java:59) | Tenant(, public, public) | Starting task: RemoveExpiredDashboardSessions

05 Jan 2024 02:57:55:884 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [main] thread | io.supertokens.cronjobs.CronTask.<init>(CronTask.java:59) | Tenant(, public, public) | Starting task: Telemetry

05 Jan 2024 02:57:55:885 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [main] thread | io.supertokens.cronjobs.CronTask.<init>(CronTask.java:59) | Tenant(, public, public) | Starting task: DeleteExpiredAccessTokenSigningKeys

05 Jan 2024 02:57:55:885 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [pool-1-thread-1] thread | io.supertokens.cronjobs.CronTask.run(CronTask.java:78) | Tenant(, public, public) | Cronjob started: Telemetry

Started SuperTokens on 0.0.0.0:3567 with PID: 39
05 Jan 2024 02:57:56:442 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [main] thread | io.supertokens.Main.init(Main.java:271) | Tenant(, public, public) | Started SuperTokens on 0.0.0.0:3567 with PID: 39

05 Jan 2024 02:57:57:604 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [pool-1-thread-1] thread | io.supertokens.cronjobs.CronTask.run(CronTask.java:168) | Tenant(, public, public) | Cronjob finished: Telemetry

05 Jan 2024 02:58:09:454 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [http-nio-0.0.0.0-3567-exec-1] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:436) | Tenant(, public, public) | API called: /recipe/session/refresh. Method: POST. Version: 3.0

05 Jan 2024 02:58:11:083 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [http-nio-0.0.0.0-3567-exec-1] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:482) | Tenant(, public, public) | API ended: /recipe/session/refresh. Method: POST

05 Jan 2024 02:58:33:255 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [http-nio-0.0.0.0-3567-exec-2] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:436) | Tenant(, public, public) | API called: /public/recipe/user. Method: GET. Version: 3.0

05 Jan 2024 02:58:34:870 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [http-nio-0.0.0.0-3567-exec-2] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:482) | Tenant(, public, public) | API ended: /public/recipe/user. Method: GET

05 Jan 2024 02:58:38:848 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [http-nio-0.0.0.0-3567-exec-3] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:436) | Tenant(, public, public) | API called: /public/recipe/signup. Method: POST. Version: 3.0

05 Jan 2024 02:58:47:433 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [http-nio-0.0.0.0-3567-exec-3] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:482) | Tenant(, public, public) | API ended: /public/recipe/signup. Method: POST

05 Jan 2024 02:58:55:877 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [pool-1-thread-2] thread | io.supertokens.cronjobs.CronTask.run(CronTask.java:78) | Tenant(, public, public) | Cronjob started: SyncCoreConfigWithDb

05 Jan 2024 02:58:56:955 +0000 | INFO | pid: a49bbb7a-580f-4348-80c9-2768daf298f2 | [pool-1-thread-2] thread | io.supertokens.cronjobs.CronTask.run(CronTask.java:168) | Tenant(, public, public) | Cronjob finished: SyncCoreConfigWithDb

**Comment by rishabhpoddar** [comment]
`API ended: /public/recipe/signup. Method: POST` indicates that the api finished successfully. So im not sure that the error is from connecting to rds psql. It's strange cause based on the python stack trace, it seems that the error is from the core cause it's at the line where the python sdk calls the core. But the core has no errors... Could you step through the code and see what error message is thrown when querying the core?

**Comment by tenghuil** [comment]
> `API ended: /public/recipe/signup. Method: POST` indicates that the api finished successfully. So im not sure that the error is from connecting to rds psql. It's strange cause based on the python stack trace, it seems that the error is from the core cause it's at the line where the python sdk calls the core. But the core has no errors... Could you step through the code and see what error message is thrown when querying the core?

Sure, I can take a deeper look later. But what's strange is that the exception only happens when I use my AWS RDS postgresql, everything works well is I just use in memory postgresql.

**Comment by rishabhpoddar** [comment]
Yea.. quite strange. Especially since the you are saying the db has the data. Also, we use RDS psql for our managed service, and it works just fine..

**Comment by tenghuil** [comment]
> Yea.. quite strange. Especially since the you are saying the db has the data. Also, we use RDS psql for our managed service, and it works just fine..

Could it be a problem with my backend setup? Since I have all my frontend/backend code pasted here, do you mind give it a try on your side with your RDS psql?

**Comment by rishabhpoddar** [comment]
The config seems to be fine.

**Comment by tenghuil** [comment]
> The config seems to be fine.

It's so weird.. what else can i do?

**Comment by rishabhpoddar** [comment]
Try and step through the python code to see why it fails?

**Comment by tenghuil** [comment]
> Try and step through the python code to see why it fails?

Not lucky.. from the backend side, the response is always None. For the core side, I tried to run without docker but I was not able to configure it to run with my DB instead of the in-memory db. The docker logs barely provide any useful debuggign information.

**Comment by rishabhpoddar** [comment]
So it seems that the core's reply isn't getting to the python SDK? Is there something in the middle of the two that might be causing issues?

**Comment by tenghuil** [comment]
> So it seems that the core's reply isn't getting to the python SDK? Is there something in the middle of the two that might be causing issues?
nothing in the middle backend calls core directly

**Comment by rishabhpoddar** [comment]
Hmm. Im not quite sure. Can you try our managed service core and see if it works with that? Im ont sure this is a bug in our sdk or core.. especially since we can't reproduce the issue.
