### ISSUE TITLE
Vulnerabilities in latest supertokens-mysql Docker image

### ISSUE THREAD

**Issue by michael-pxr** [supertokens/supertokens-core#926]
## 🐛 Bug Report

When inspecting the latest `supertokens-mysql` Docker image with Docker desktop, I noticed there are vulnerabilities (see screenshot)

![Screenshot 2024-02-12 at 16 07 53](https://github.com/supertokens/supertokens-core/assets/46559823/5c3605b0-8896-4162-ae4e-4d0c8be7bb38)

## Useful informations

- Docker image: `registry.supertokens.io/supertokens/supertokens-mysql@sha256:b580b4552f3118ca6fa52414934b9141b438d740321229eb1cc82cb80c09c92b`

**Comment by rishabhpoddar** [comment]
This has been fixed for docker images for core version >= 6.0
