### ISSUE TITLE
 ':supertokens-plugin-interface' could not be found

### ISSUE THREAD

**Issue by sjtuzhaoxh** [supertokens/supertokens-core#952]
## 🐛 Bug Report

(A clear and concise description of what the bug is)
A problem occurred evaluating root project 'supertokens-core-master'.
> Project with path ':supertokens-plugin-interface' could not be found in root project 'supertokens-core-master'.

## Useful informations

(Write what happened. Add screenshots, stacktraces, videos, anything that can help)

**Comment by rishabhpoddar** [comment]
If you are following the contributing guide, make sure to setup `supertokens-root` as mentioned in the guide. This issue has no futher detail, so i am closing it.
