### ISSUE TITLE
Create emailpassword tables & change default db name to supertokens

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#96]
This issue is related to: https://github.com/supertokens/supertokens-core/issues/78

The below is thanks to @bhumilsarvaiya 

# MySQL
```sql
CREATE TABLE email_password_users (
  user_id CHAR(36) NOT NULL,
  email VARCHAR(256) NOT NULL UNIQUE,
  password_hash VARCHAR(128) NOT NULL,
  time_joined BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (user_id),
  INDEX email_password_user_pagination (time_joined DESC, user_id DESC)
);

CREATE TABLE email_password_pswd_reset_tokens (
  user_id CHAR(36) NOT NULL,
  token VARCHAR(128) NOT NULL UNIQUE,
  token_expiry BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (user_id, token),
  FOREIGN KEY (user_id) REFERENCES email_password_users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
  INDEX email_password_token_expiry_index (token_expiry)
);
```
### User table properties
- Retrieving info based on `user_id` or `email` will use an index.

### Password reset table properties
- Retrieving info based on `user_id` or `token` will use an index.
- Deleting rows based on `user_id` will use an index.
- Range querying based on token_expiry uses the index.
- Doing `SELECT ... FOR UPDATE` on `user_id` may lock more rows than needed since `user_id` is not unique. These locks will only affect `INSERT` statements.
- When deleting from this table based on token_expiry, if there the where clause is a `< __` and a there is a transaction going on with `FOR UPDATE` based on `user_id`, then this delete statement may block.

# PostgreSQL tables
```sql
CREATE TABLE email_password_users ( 
  user_id CHAR(36) NOT NULL, 
  email VARCHAR(256) NOT NULL UNIQUE, 
  password_hash VARCHAR(128) NOT NULL, 
  time_joined BIGINT NOT NULL, 
  PRIMARY KEY (user_id)
);

CREATE INDEX email_password_user_pagination ON email_password_users(time_joined DESC, user_id DESC);

CREATE TABLE email_password_pswd_reset_tokens (
  user_id CHAR(36) NOT NULL,
  token VARCHAR(128) NOT NULL UNIQUE,
  token_expiry BIGINT NOT NULL,
  PRIMARY KEY (user_id, token),
  FOREIGN KEY (user_id) REFERENCES email_password_users(user_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX email_password_token_expiry_index ON email_password_pswd_reset_tokens(token_expiry);
```
### User table properties
- Retrieving info based on `user_id` or `email` will use an index.

### Password reset table properties
- Retrieving info based on `user_id` or `token` will use an index.
- Deleting rows based on `user_id` will use an index.
- Range querying based on token_expiry does not use the index.
- The following that happen for MySQL, do not happen for PostgreSQL:
   - Doing `SELECT ... FOR UPDATE` on `user_id` may lock more rows than needed since `user_id` is not unique. These locks will only affect `INSERT` statements.
   - When deleting from this table based on token_expiry, if there the where clause is a `< __` and a there is a transaction going on with `FOR UPDATE` based on `user_id`, then this delete statement may block.

# SQLite tables
```sql
CREATE TABLE email_password_users (
  user_id CHAR(36) NOT NULL,
  email VARCHAR(256) NOT NULL UNIQUE,
  password_hash VARCHAR(128) NOT NULL,
  time_joined BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (user_id)
);

CREATE INDEX email_password_user_pagination ON email_password_users(time_joined DESC, user_id DESC);

CREATE TABLE password_reset_tokens (
  user_id CHAR(36) NOT NULL,
  token VARCHAR(128) NOT NULL UNIQUE,
  token_expiry BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (user_id, token),
  FOREIGN KEY (user_id) REFERENCES email_password_users(user_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX token_expiry_index ON email_password_pswd_reset_tokens(token_expiry);
```
- The performance of this doesn't really matter as it's only for non dev / non prod apps
- The locking for this also doesn't matter as we will take exclusive locks in java.
------------
- [x] MySQL
- [x] PostgreSQL
- [x] MongoDB (only refactoring part. Not table creation)
- [x] SQLite
- [x] Add user pagination index (Related to https://github.com/supertokens/supertokens-core/issues/127)
   - [x] SQLite
   - [x] Postgresql
   - [x] MySQL

**Comment by rishabhpoddar** [comment]
@bhumilsarvaiya please confirm that the above is OK

**Comment by bhumilsarvaiya** [comment]
> is there a difference between creating a unique index and adding unique at the end of the column name?

No, there is no difference. When a unique constraint is created a corresponding unique index is automatically created on the column(s).

> From a querying point of view, would the password_reset_token be better like this

Yes, this is better. But one thing I don't like is the size of the token column as it is part of the primary key.

**Comment by bhumilsarvaiya** [comment]
> What should be the token length in the password reset table?

VARCHAR(80)

**Comment by bhumilsarvaiya** [comment]
For postgres range index query, following test was done:

Table:
```sql
CREATE TABLE test
(
    t bigint,
    "userId" character varying(64) NOT NULL,
    CONSTRAINT test_pkey PRIMARY KEY ("userId")
)
CREATE INDEX pagination
    ON test USING btree
    (t ASC NULLS LAST);
```

When the table was empty:
 - ```select * from test where t > 0; ``` performed a sequential scan.
 - ```select * from test where t > 0 and t < 100;``` performed an index scan

If sequential scan was turned off by setting `enable_seqscan = 0`,  ```select * from testing.test where t > 0; ``` performed an index scan.

After inserting 100,000 rows (value of **t** varying from 0 to 199):
 - ```select * from test where t > 0; ``` performed a sequential scan.
 - ```select * from test where t > 0 and t < 100;``` performed a sequential scan

If sequential scan was turned off by setting `enable_seqscan = 0`,  both ```select * from testing.test where t > 0; ``` and ```select * from testing.test where t > 0 and t < 100;``` performed an index scan.

Truncating the table and inserting 100,000 rows (value of **t** varying from 0 to 19000):
 - ```select * from test where t > 0; ``` performed a sequential scan.
 - ```select * from test where t < 100;``` performed a sequential scan on first run and performed an index scan thereafter
 - ```select * from test where t > 0 and t < 100;``` performed an index scan

If sequential scan was turned off by setting `enable_seqscan = 0`,  ```select * from testing.test where t > 0; ``` performed an index scan.

Based on the above test and this [stackoverflow post](https://stackoverflow.com/questions/53066221/postgresql-range-query-index), we can summerize:
> Postgres is likely not sure exactly how many rows are in your table, but knows it's small. Therefore, the threshold for when to use an index is high, hence your first query does a table scan. With the second date check, it is likely figuring the query will match a smaller number of rows when it checks the primary key index, so it goes for the index.

**Comment by bhumilsarvaiya** [comment]
For MySQL, until [version 5.7](https://dev.mysql.com/doc/refman/5.7/en/create-index.html), having ASC or DESC for a column while creating index was permitted for future extensions for specifying ascending or descending index value storage. They are parsed but ignored; index values are always stored in ascending order.

Since [MySQL 8.0](https://dev.mysql.com/doc/refman/8.0/en/descending-indexes.html), DESC in an index definition is no longer ignored but causes storage of key values in descending order. Previously, indexes could be scanned in reverse order but at a performance penalty.

**Comment by bhumilsarvaiya** [comment]
For pagination testing, following table structure was used:

#### MySQL
```sql
CREATE TABLE `test_pagination` (
  `uid` char(36) NOT NULL,
  `time_joined` bigint unsigned NOT NULL,
  PRIMARY KEY (`uid`),
  KEY `time_join` (`time_joined` DESC,`uid`)
)
```

#### PostgreSQL
```sql
CREATE TABLE test_pagination
(
    uid character(36) NOT NULL,
    time_joined bigint NOT NULL,
    CONSTRAINT test_pagination_pkey PRIMARY KEY (uid)
)

CREATE INDEX time_join
    ON testing.test_pagination USING btree
    (time_joined DESC NULLS LAST, uid ASC NULLS LAST)
```

First query: (no uid info known)
```sql
SELECT
	time_joined, uid FROM test_pagination
ORDER BY
	time_joined DESC,
        uid ASC
LIMIT 5;
```

For next successive query, when the uid info was available, the query was:
```sql
SELECT
	time_joined, uid FROM test_pagination
WHERE
	time_joined < 188
    OR
    (
		time_joined = 188 AND uid > '307d1538-1e76-11eb-9403-89925f1908e2'
    )
ORDER BY
	time_joined DESC,
        uid ASC
LIMIT 5;
```
> Here, 188 and '307d1538-1e76-11eb-9403-89925f1908e2' was the last row returned by the first query

The queries have been successfully tested and they yield correct results.
