### ISSUE TITLE
Should we allow the user to override the try refresh token error in the error handler?

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#98]
While writing this issue, I do not see any value in allowing the user to overwrite that. It only adds confusion and increases scope of error.

**Comment by NkxxkN** [comment]
I don't see any good reason why a user would like to use this middleware  either.

**Comment by rishabhpoddar** [comment]
So I will remove it. Thanks

**Comment by rishabhpoddar** [comment]
@NkxxkN please make sure that `onTryRefreshToken` callback is not used for testing in the `auth-react` SDK anywhere
