### ISSUE TITLE
Custom OTP lifetime never expires

### ISSUE THREAD

**Issue by EricChristensen** [supertokens/supertokens-core#989]
## 🐛 Bug Report

When we manually set the OTP lifetime to 5 minutes, we are finding that the OTP never expires. The text message indicates the correct amount of time (5 minutes), but the actual OTP can be used after 5 minutes and after the default of 15. When we do not specify a custom OTP lifetime, the OTP expires correctly after the default time of 15 minutes.

## Useful informations

Using 
registry.supertokens.io/supertokens/supertokens-postgresql:7.0
Of the core service

**Comment by sattvikc** [comment]
@EricChristensen I was unable to reproduce this issue. Could you provide more detailed steps to reproduce this?
