### ISSUE TITLE
Should we run any pre normalisation on input fields before running any validators on them?

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#99]
- Should we trim them (removes white spaces before and after the string)?
- If yes, should we do this on all input or just the ones we control (email and / or password)?

**Comment by rishabhpoddar** [comment]
@NkxxkN I think we should trim just the email.

**Comment by NkxxkN** [comment]
Yes we can do it on `email`. We shouldn't trim on password as we said last time when talking about validators implementation.
It's the user's responsibility to trim custom fields.
Our role regarding custom fields is only to run customer's validators and to forward them on successful signup.

**Comment by rishabhpoddar** [comment]
Sounds good. So just going to run trim on email then.

**Comment by rishabhpoddar** [comment]
Another clarification: This will be required on the frontend and backend, before the email validator is called

**Comment by rishabhpoddar** [comment]
@NkxxkN please feel free to close this issue once you have added the trimming on the frontend
